# -*- coding: utf-8 -*-
"""Semana_05-Practica_05_resuelta.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GX3L8iuVPoNCf2J-deIKG8pV_C1bYSJX

`IMPORTANTE: utilizar funciones.`

# Ejercicio 1

Se deben ingresar las medidas de 3 lados y verificar si con dichos lados puedo formar un triángulo.

Para su vewrificación utilizaremos el teorema de la desigualdad del triánglo, que plantea que la suma de dos de sus lados debe ser mayor a la longitud del tercer lado.

Ejemplos:

| Lado 1 | Lado 2 | Lado3 | Respuesta |
| :---: | :---: | :---: | :---: |
| 5 | 4 | 8 | True |
| 3 | 4 | 10 | False |
"""



#@title Solución
def e1_ingreso_dato(posicion:int) -> float:
  """ Ingreso de datos.

  Args:
    posicion (int): Contiene la posición a ingresar.

  Returns:
    float: Retorna el dato ingresado
  """
  return float(input(f'Ingrese la medida del lado {posicion}:'))


def e1_verificar(lado_1:float, lado_2:float, lado_3:float) -> bool:
  """ Verifica el teorema de desigualdad del triángulo.

  Args:
    lados_1 (float): Contiene el valor del lado.
    lados_2 (float): Contiene el valor del lado.
    lados_3 (float): Contiene el valor del lado.

  Returns:
    bool: Retorna True si cumple con el teorema.
  """

  return (lado_1 + lado_2 > lado_3) \
    and (lado_1 + lado_3 > lado_2) \
    and (lado_2 + lado_3 > lado_1)

lado_1:float=e1_ingreso_dato(1)
lado_2:float=e1_ingreso_dato(2)
lado_3:float=e1_ingreso_dato(3)

if e1_verificar(lado_1=lado_1, lado_2=lado_2, lado_3=lado_3):
  print('Los lados forman un triángulo.')
else:
  print('Con los lados ingresado no se puede formar un triángulo.')

"""# Ejercicio 2

Ingrese un valor númerico N entero y calcule la suma de los valores pares que van en el intervalo 0 a N, N es el extremo superior del intervalo y debe ser considerado para la suma. Tener en cuenta que si el número es negativo también se deberá obtener la suma.
"""



#@title Solución

def e2_ingreso_dato() -> int:
  """ Ingreso de datos.

  Returns:
    float: Retorna el dato ingresado
  """
  return int(input(f'Ingrese el valor:'))


def e2_sumar(n:int) -> int:
  """ Función que suma valores pares.

  Args:
    n (int): Extremo superior del intervalor.

  Returns:
    int: Retorna el valor de la suma.
  """
  signo:int = 1 if n > 0 else -1
  return sum(range(0, ((1 * signo) + n), (2 * signo)))

n:int = e2_ingreso_dato()
print(f'La suma de los números pares dentro del intervalo es: {e2_sumar(n=n)}')

"""# Ejercicio 3

Escribir un programa que me permita ingresar un año y determinar si es bisiesto.

Un año bisiesto es aquel que es divisible por 4, excepto los años que son divisibles por 100 pero no por 400.
"""



#@title Solución

def e3_ingreso_dato() -> int:
  """ Ingreso de datos.

  Returns:
    int: Retorna el dato ingresado
  """
  return int(input(f'Ingrese el año:'))


def e3_es_bisiesto(anio:int) -> int:
  """ Función que determina si un año es bisiesto.

  Args:
    n (int): Extremo superior del intervalor.

  Returns:
    int: Retorna el valor de la suma.
  """
  return (anio % 4 == 0 and anio % 100 != 0) or (anio % 400 == 0)

anio:int = e3_ingreso_dato()
print(f'El año {anio} es biciesto? {e3_es_bisiesto(anio=anio)}')

"""# Ejercicio 4

Escribir un programa donde tengo que adivinar que número seleccionó python. El número está entre 0 y 999.

En cada pregunta se debe mostrar el rango de posibles valores a seleccionar, de esta forma el usuario puedo descartar números y se le hace más sencillo encontrar el número.

Ayuda: trabajar con range y comparaciones menor, mayor e igual.
"""

#######
# no modificar, genera un número entre 0 y 9999 aleatoreo
from random import randint
NUMERO_SELECCIONADO:int = randint(0, 1000) # numero que tengo que adivinar
#######

#@title Solución

#######
# no modificar, genera un número entre 0 y 9999 aleatoreo
from random import randint
NUMERO_SELECCIONADO:int = randint(0, 1000) # numero que tengo que adivinar
#######

def e4_encontrar_numero():
  """ Función para adivinar un número
  """
  maximo:int = 999
  minimo:int = 0
  while (n:=int(input(f'Ingrese el número a verificar dentro del intervalo [{minimo}:{maximo}]:'))) \
    and n != NUMERO_SELECCIONADO:
    if n < NUMERO_SELECCIONADO:
      print(f'El número seleccionado por python es mayor a {n}.')
      minimo=n
    else:
      print(f'El número seleccionado por python es menor a {n}.')
      maximo=n
  else:
    print(f'El número secreto fue encontrado y es {n}')


e4_encontrar_numero()

"""# Ejercicio 5

Crear un programa que elimine las vocales de una frase. El usuario debe ingresar una frase y se devuelve la frase sin vocales.

Ejemplo:

> Entrada: La señora LILIANA no se encuentra disponible.

> Salida: L sñr LLN o s ncntr dspnbl.
"""



#@title Solución
def e5_ingreso_dato() -> str:
  """ Ingreso de datos.

  Returns:
    str: Retorna el dato ingresado
  """
  return input(f'Ingrese la frase:')


def e5_quitar_vocales(frase:str) -> str:
  """ Función que elimina vocales.

  Args:
    frase (str): Contiene la frase.

  Returns:
    str: Retorna la nueva frase sin vocales.
  """
  respuesta:str = ''
  vocales:list[str] = ['a', 'e', 'i', 'o', 'u', 'á', 'é', 'í', 'í', 'ú']
  for caracter in frase:
    if caracter.lower() not in vocales:
      respuesta += caracter
  return respuesta

frase:str = e5_ingreso_dato()
print(f'La nueva frase es:\n\t{e5_quitar_vocales(frase=frase)}')

"""# Ejercicio 6

Crear un programa que elimine las letras mayúsculas de una frase. El usuario debe ingresar una frase y se devuelve la frase sin las letras mayúsculas.

Ejemplo:

> Entrada: La señora LILiaNA no se encuentra disponible.

> Salida: a señora ia no se encuentra disponible.

`Ayuda: ver la función ord y tabla ascii`
"""



#@title Solución

def e6_ingreso_dato() -> str:
  """ Ingreso de datos.

  Returns:
    str: Retorna el dato ingresado
  """
  return input(f'Ingrese la frase:')


def e6_quitar_mayuscukas(frase:str) -> str:
  """ Función que elimina vocales.

  Args:
    frase (str): Contiene la frase.

  Returns:
    str: Retorna la nueva frase sin vocales.
  """
  respuesta:str = ''

  for caracter in frase:
    valor:int = ord(caracter)
    if not(65 <= valor <= 90 or valor == 209):
      respuesta += caracter
  return respuesta

frase:str = e6_ingreso_dato()
print(f'La nueva frase es:\n\t{e6_quitar_mayuscukas(frase=frase)}')

"""# Ejercicio 7

Escribir un programa para verificar la hipótesis intrigante (aún no se ha comprobado) formulado por el Alemán Lothar Collatz:

* Toma cualquier número entero que no sea negativo y que no sea cero y asígnale el nombre $c$.
* Si es par, evalúa un nuevo $c$ como $c//2$ (división entera).
* De lo contrario, si es impar, evalúe un nuevo $c$ como $3 * c + 1$.
* Si $c$ != 1, salta al punto 2.

La hipótesis dice que, independientemente del valor inicial de $c$, el valor siempre tiende a 1.
"""



#@title Solución

def e7_ingreso_dato() -> int:
  """ Ingreso de datos.

  Returns:
    int: Retorna el dato ingresado
  """
  return int(input(f'Ingrese el valor de c:'))


def e7_intrigande(c:int):
  """ Función que prueba la hipótesiss.

  Args:
    c (int): Contiene el valor de c.

  """

  if c > 1:
    paso = 0
    while c != 1:
      if c % 2 != 0:
        c = 3 * c + 1
      else:
        c = c // 2
      print(f'Paso {paso:04d}: {c}')
      paso += 1

    print(f'Paso {paso:010d}: {c}')

    print(f'Se necesitaron {paso} pasos.')
  else:
    print('Valor de c es incorrecto')

e7_intrigande(c=e7_ingreso_dato())