# -*- coding: utf-8 -*-
"""Semana_05-01_Operadores_aritmeticos.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xUJ7hxZeBNby-9B2bNeL5q5rpSw5-8gL

## Operador =
El operador `=` prácticamente no necesita explicación, simplemente asigna a la variable de la izquierda el contenido que le ponemos a la derecha. Recordá que ya comentamos cuales es la forma de nombrar variables.
"""

x=2       # Uso correcto del operador =
print('El valor de x es', x)

"""## Operadores aritméticos
Los operadores aritméticos o arithmetic operators son los más comunes que nos podemos encontrar, y nos permiten realizar operaciones aritméticas sencillas, como pueden ser la suma, resta o exponente.

A continuación, condensamos en la siguiente tabla todos ellos con un ejemplo, donde `x=10` y `y=3`.

| Operador | Nombre         | Ejemplo       |
|:--------:|:--------------:|:-------------:|
| +        | Suma           | x + y = 13    |
| \-       | Resta          | x \- y = 7    |
| \*       | Multiplicación | x \* y = 30   |
| /        | División       | x/y = 3.333   |
| %        | Módulo         | x%y = 1       |
| \*\*     | Exponente      | x \*\* y = 1000 |
| //       | Cociente       | 3             |

"""

x = 7; y = 3
print("Operadores aritméticos")
print("x+y =", x+y)
print("x-y =", x-y)
print("x*y =", x*y)
print("x/y =", x/y)
print("x%y =", x%y)
print("x**y =", x**y)
print("x//y =", x//y)

"""## Operador +
El operador `+` suma los números presentes a la izquierda y derecha del operador. Recalcamos lo de números porque no tendría sentido sumar dos cadenas de texto, o dos listas, pero en Python es posible hacer este tipo de cosas.
"""

print(f'La operación ({x} + {y}) es igual a {x+y}')

"""Es posible sumar también dos cadenas de texto, pero la suma no será aritmética, sino que se unirán ambas cadenas en una. También se pueden sumar dos listas, cuyo resultado es la unión de ambas."""

print('La suma de dos str "2" + "2" es:', ("2" + "2"))
print('La suma de dos listas [1, 3] + [6, 7] es', [1, 3] + [6, 7])

"""## Operador -
El operador `-` resta los números presentes a la izquierda y derecha del operador. A diferencia el operador + en este caso no podemos restar cadenas o listas.
"""

print(f'La operación ({x} - {y}) es igual a {x-y}')

"""## Operador *
El operador `*` multiplica los números presentes a la izquierda y derecha del operador.
"""

print(f'La operación ({x} * {y}) es igual a {x*y}')

"""Como también pasaba con el operador `+` podemos hacer cosas “raras” con `*`. Explicar porque pasan estas cosas es un poquito más complejo, por lo que lo dejamos para otro capítulo, donde explicaremos como definir el comportamiento de determinados operadores para nuestras clases."""

print("Hola" * 3) #HolaHolaHola

"""## Operador /
El operador `/` divide los números presentes a la izquierda y derecha del operador. Un aspecto importante a tener en cuenta es que si realizamos una división cuyo resultado no es entero (es decimal) podríamos tener problemas. En Python 3 esto no supone un problema porque el mismo se encarga de convertir los números y el resultado que se muestra si es decimal.
"""

print(f'La operación ({x} / {y}) es igual a {x/y}')
print(f'La operación ({1} / {2}) es igual a {1/2}')

"""Sin embargo, en Python 2, esto hubiera tenido un resultado diferente. El primer ejemplo 10/3=3 y el segundo 1/2=0. El comportamiento realmente sería el de calcular el cociente y no la división.

Para saber más: Si quieres saber más acerca de este cambio del operador de división, puedes leer la la [PEP238](https://www.python.org/dev/peps/pep-0238/)

## Operador %
El operador `%` realiza la operación módulo entre los números presentes a la izquierda y la derecha. Se trata de calcular el resto de la división entera entre ambos números. Es decir, si dividimos 10 entre 3, el cociente sería 3 y el resto 1. Ese resto es lo que calcula el módulo.
"""

print(f'La operación ({x} % {y}) es igual a {x%y}')
print(f'La operación ({x} % {2}) es igual a {x%2}')

"""Una curiosidad a tener en cuenta, es que el operador módulo tiene diferentes comportamientos en Python del que tiene en otros lenguajes como C cuando se usan números negativos tanto de dividendo como de divisor. Así que ten cuidado si haces cosas como las siguientes."""

print(f'La operación  7%3  da un resultado de  { 7%3} | [en otros lenguajes daría  1]') # en otros lenguajes daría 1
print(f'La operación -7%3  da un resultado de  {-7%3} | [en otros lenguajes daría -1]') # en otros lenguajes daría -1
print(f'La operación  7%-3 da un resultado de { 7%-3} | [en otros lenguajes daría  1]') # en otros lenguajes daría 1
print(f'La operación -7%-3 da un resultado de {-7%-3} | [en otros lenguajes daría -1]') # en otros lenguajes daría -1

"""*Por qué ocurre esto?*

En Python, el cálculo del módulo se relaciona con la fórmula de la división entera:

\begin{equation}
a\%b = a - ((a//b) * b)
\end{equation}

Donde `//` es la división entera que redondea hacia abajo (hacia el entero menor). Veamos un ejemplo:

Ejemplo:

\begin{equation}
−7\%−3
\end{equation}

Calcula la división entera:

\begin{equation}
−7//−3=2
\end{equation}

Esto es porque `−3×2=−6` y esto es el entero más cercano hacia abajo.

Sustituye en la primer fórmula que mencionamos:
\begin{equation}
−7\%−3=−7−(−3×2)=−7+6=−1
\end{equation}
Así, el resultado es `−1`, que tiene el mismo signo que el divisor (`−3`).

*Regla de signo*

El módulo en Python (y en muchos lenguajes como Ruby o Perl) no es estrictamente un resto matemático, sino una operación definida para garantizar que el resultado tenga el mismo signo que el divisor.

En matemáticas puras, el resto puede no cumplir esta regla, lo que a veces causa confusión.

Ejemplos en otros lenguajes aplicando la fórmula (a %  b  =  a  - ((a//b) * b))
$$
 7 \%  3  =  7 - ((  7 //  3) *  3) =  7 - (( 2) *  3) =  7 - 6 =  1
$$
$$
-7 \%  3  = -7 - (( -7 //  3) *  3) = -7 - ((-2) *  3) = -7 + 6 = -1
$$
$$
 7 \% -3  =  7 - ((  7 // -3) * -3) =  7 - ((-2) * -3) =  7 - 6 =  1
$$
$$
-7 \% -3  = -7 - (( -7 // -3) * -3) = -7 - (( 2) * -3) = -7 + 6 = -1
$$

Ejemplos en python aplicando la fórmula (a %  b  =  a  - ((a//b) * b))
$$
 7 \%  3  =  7 - ((  7 //  3) *  3) =  7 - (( 2) *  3) =  7 - 6 =  1
$$
$$
-7 \%  3  = -7 - (( -7 //  3) *  3) = -7 - ((-3) *  3) = -7 + 9 =  2 [**]
$$
$$
 7 \% -3  =  7 - ((  7 // -3) * -3) =  7 - ((-3) * -3) =  7 - 9 = -2 [**]
$$
$$
-7 \% -3  = -7 - (( -7 // -3) * -3) = -7 - (( 2) * -3) = -7 + 6 = -1
$$
**El menor número más cercano en `-3` por ser negativo y no `-2`. Ver en el operador `//`

## Operador **
El operador `**` realiza el exponente del número a la izquierda elevado al número de la derecha.
"""

print(f'La operación ({x} ** {y}) es igual a {x**y}')

"""Si ya has usado alguna vez Python, tal vez hayas oido hablar de la librería math. En esta librería también tenemos una función llamada `pow` que es equivalente al operador `**`."""

import math
print(f'La operación ({x} % {y}) es igual a {math.pow(x, y)}')

"""Para saber más: Puedes consultar más información de la librería math en la [documentación](https://docs.python.org/3/library/math.html) oficial de Python

## Operador //
Por último, el operador `//` calcula el cociente de la división entre los números que están a su izquierda y derecha.
"""

print(f'La operación ({x} // {y}) es igual a {x//y}')
print(f'La operación ({x} // {x}) es igual a {x//x}')

"""Debemos tener en cuenta que en python, este operador siempre va al número siguiente más pequeño, por lo tanto cuando estamos en la banda negativa de los números esto es al contrario que en la banda positiva de los números.

Vamos a ver los ejemplos:
"""

a=7
b=3

print(f'a // b = {a} // {b} = {a//b}')
print(f'Si lo hacemos por pasos {a/b:.4f} -> {math.floor(a/b)}')

a=-7
b=3
print('\nNuevos valores de a y b')
print(f'a // b = {a} // {b} = {a//b}')
print(f'Si lo hacemos por pasos {a/b:.4f} -> {math.floor(a/b)}')
print('Notar que el resultado es -2.3333 y como lo lleva a 3 cuando otros lenguajes van a mostrar -2.')
print('Esto es una particularidad única de Python.')

a=7
b=-3
print('\nNuevos valores de a y b')
print(f'a // b = {a} // {b} = {a//b}')
print(f'Si lo hacemos por pasos {a/b:.4f} -> {math.floor(a/b)}')
print('Notar que el resultado es -2.3333 y como lo lleva a 3 cuando otros lenguajes van a mostrar -2')
print('Esto es una particularidad única de Python.')

a=-7
b=-3
print('\nNuevos valores de a y b')
print(f'a // b = {a} // {b} = {a//b}')
print(f'Si lo hacemos por pasos {a/b:.4f} -> {math.floor(a/b)}')

"""Tal vez te hayas dado cuenta que el operador cociente `//` está muy relacionado con el operador módulo `%`. Volviendo a las lecciones del colegio sobre la división, recordaremos que el Dividendo `D` es igual al divisor `d` multiplicado por el cociente `c` y sumado al resto `r`, es decir `D=d*c+r`.

Se puede ver como en el siguiente ejemplo, `10//3` es el cociente y `10%3` es el resto. Al aplicar la fórmula, verificamos que efectivamente `10` era el dividendo.


"""

D = 10 # Número que queremos dividir
d = 3  # Número entre el que queremos dividir
print(3 * (10//3) + 10%3) # 10

"""## Orden de aplicación
En los ejemplos anteriores simplemente hemos aplicado un operador a dos números sin mezclarlos entre ellos. También es posible tener varios operadores en la misma línea de código, y en este caso es muy importante tener en cuenta las prioridades de cada operador y cual se aplica primero. Ante la duda siempre podemos usar paréntesis, ya que todo lo que está dentro de un paréntesis se evaluará conjuntamente, pero es importante saber las prioridades.

El orden de prioridad sería el siguiente para los operadores aritméticos, siendo el primero el de mayor prioridad:

* () Paréntesis
* ** Exponente
* -x Negación
* \* / // % Multiplicación, División, Cociente, Módulo
* \+ - Suma, Resta
"""

print(10*(5+3)) # Con paréntesis se realiza primero la suma
# 80
print(10*5+3)   # Sin paréntesis se realiza primero la multiplicación
# 53

print(3*3+2/5+5%4) # Primero se multiplica y divide, después se suma
#10.4
print(-2**4)       # Primero se hace la potencia, después se aplica el signo
#-16

"""Para saber más: Si quieres saber más sobre el orden de prioridad de diferentes operadores, aquí tienes la [documentación](https://docs.python.org/3/reference/expressions.html) oficial de Python"""