# -*- coding: utf-8 -*-
"""Semana_05-08_Operadores_walrus.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15c28NYiHdVHZKqV1ziwPuRYwG53haN-i

## Operador Walrus

El operador walrus o walrus operator se introdujo con la [PEP572](https://www.python.org/dev/peps/pep-0572) en Python 3.8, y se trata de un operador de asignación con una funcionalidad extra que veremos a continuación.

El operador se representa con dos puntos seguidos de un igual `:=`, lo que tiene cierto parecido a una morsa, siendo `:` los ojos y `=` los colmillos, por lo que de ahí viene su nombre (walrus significa morsa en Inglés).

El problema que dicho operador intenta resolver es el siguiente. Podemos simplificar las siguientes tres líneas de código.
"""

x = "Python"
print(f'La variable x tiene el valor {x} y su tipo es {type(x)}')

"""Ahora vamos a utilizar el operador `:=` para resolver el problema anterior en 1 solo línea.


"""

print('La variable x tiene el valor {} y su tipo es {}'.format(y:="Python", type(y)))

"""Para gente que venga de otros lenguajes de programación como C, tal vez le resulte raro este operador, ya que C permite realizar lo siguiente. Podemos ver como (x = 5) puede ser comparado con == 5. Sin embargo esta sintaxis no es válida en Python, y el operador wallrus es precisamente lo que intenta resolver.

```
#include <stdio.h>
int main(){
    int x;
    if ((x = 5) == 5) {
        printf("Hola");
    }
    return 0;
}
```

## Ejemplos Operador Walrus
En el siguiente programa vamos a leer un archivo línea por línea.
"""

# Commented out IPython magic to ensure Python compatibility.
# %%writefile test.txt
# 1 - línea
# 2 - línea
# 3 - línea

file = '/content/test.txt'
with open(file) as f:
    line = f.readline()
    while line:
      print(line, end='')
      line = f.readline()

"""Sin embargo aprovechando que el operador walrus `:=` devuelve el contenido que es asignado, podemos usar entrada para comparar con != None. Es decir, podemos unir la asignación = y la comparación en la misma línea. Esto nos permite ahorrar alguna línea de código."""

with open(file) as f:
    while line := f.readline():
      print(line, end='')

"""También nos podemos ahorrar una línea de código si queremos primero asignar a una variable y luego emplear dicha variable en, por ejemplo, un if."""

a = 20*[1]
print(f'La variable a tiene {a} \n\ty su longitud es {len(a)}')
if (n := len(a)) > 10:
    print(f"La lista tiene {n} elementos (>10)")

"""Por otro lado puede ser útil cuando usemos list comprehensions donde el valor que usamos para filtrar es modificado y se necesita también en el cuerpo del bucle."""

datos:list[int] = list(range(10))

def f(x:int) -> int:
  """ Función que devuelve x si es par y -x si es impar.

  Args:
    x (int): número entero
  Returns:
    int: Retorna x si es par y -x si es impar.
  """
  return x if (x % 2 == 0) else -x

print(f'La variable datos tiene {datos}')

resultado:list[int] = [(x, y, x/y) for x in datos if (y := f(x)) > 0]
print(f'La variable resultado tiene {resultado}')

"""Notesé como se eliminaron los valores `impares` y el valor `0` del resultado.

Este mismo código sin `walrus` podría ser así.
"""

print(f'La variable datos tiene {datos}')

resultado:list[int] = []
for x in datos:
  y:int = f(x)
  if y > 0:
    resultado.append((x, y, x/y))
print(f'La variable resultado tiene {resultado}')

"""De manera similar, podemos reutilizar el resultado de una expresión evitando tener que volver a computarla."""

resultado:list[int] = [[y := f(x), x/y] for x in datos if x > 0]
print(f'La variable resultado tiene {resultado}')

"""Puedes encontrar otros ejemplos en los siguientes enlaces:

* En la [documentación oficial de Python](https://docs.python.org/3/whatsnew/3.8.html#assignment-expressions)
* En la propia sección de ejemplos de la [PEP572](https://peps.python.org/pep-0572/).
* Y en este [pull request](https://github.com/python/cpython/pull/8122/files).

## Críticas Al Operador Walrus
El operador `walrus` ha recibido muchas críticas entre los desarrolladores de Python, principalmente porque aunque sea cierto que su uso puede ahorrarnos alguna línea de código, a veces empeora la legibilidad. No siempre menos código implica una mejora, sobre todo si se hace más complicado de leer.

Por otro lado, aunque el operador walrus sea muy similar al operador de asignación `=`, su uso no es consistente.

Por ejemplo, el siguiente código no es correcto usando `:=`.

```
# Incorrecto
class Example:
    [(j := i) for i in range(5)]
# SyntaxError: assignment expression within a comprehension cannot be used in a class body
```

De hecho, el propio creador Christoph Groth sugirió en el siguiente [hilo](https://mail.python.org/pipermail/python-ideas/2018-March/049409.html) que tal vez sería conveniente implementar el uso de `=` como en C/C++ (recuerda el ejemplo que hemos visto anteriormente). Si esto se llega a producir, no sabemos que podría pasar con el operador walrus, pero tal vez ya no sería necesario.
"""