# -*- coding: utf-8 -*-
"""Semana_05-02_Operadores_relacionales.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CiT3zckkw2GRfc6EZ232wVTzxolZ7xXD

## Operadores relacionales
Los operadores relacionales, o también llamados comparison operators nos permiten saber la relación existente entre dos variables. Se usan para saber si por ejemplo un número es mayor o menor que otro. Dado que estos operadores indican si se cumple o no una operación, el valor que devuelven es `True` o `False`.

Veamos un ejemplo con `x=2` e `y=3`

| Operador | Nombre        | Ejemplo  | Resultado |
|:--------:|:-------------:|:--------:|:---------:|
| ==       | Igual         | x == y   | False     |
| !=       | Distinto      | x != y   | True      |
| >        | Mayor         | x > y    | False     |
| &lt;     | Menor         | x &lt; y | True      |
| >=       | Mayor o igual | x >= y   | False     |
| &lt;=    | Menor o igual | x &lt; y | True      |
"""

x=2; y=3
print("Operadores Relacionales")
print(f"x == y -> {x} == {y} =", x==y)
print(f"x != y -> {x} != {y} =", x!=y)
print(f"x >  y -> {x} >  {y} =", x> y)
print(f"x <  y -> {x} <  {y} =", x< y)
print(f"x >= y -> {x} >= {y} =", x>=y)
print(f"x <= y -> {x} <= {y} =", x<=y)

"""## Operador ==
El operador `==` permite comparar si las variables introducidas a su izquierda y derecha son iguales. Muy importante no confundir con `=`, que es el operador de asignación.
"""

print('La comparación 4==4 es', 4==4)
print('La comparación 4==5 es', 4==5)
print('La comparación 4==4.0 es', 4==4.0)
print('La comparación 0==False es', 0==False)
print('La comparación "asd"=="asd" es', "asd"=="asd")
print('La comparación "asd"=="asdf" es', "asd"=="asdf")
print('La comparación 2=="2" es', 2=="2")
print('La comparación [1, 2, 3] == [1, 2, 3] es', [1, 2, 3] == [1, 2, 3])

"""## Operador !=
El operador `!=` devuelve `True` si los elementos a comparar son iguales y `False` si estos son distintos. De hecho, una vez definido el operador `==`, no sería necesario ni explicar `!=` ya que hace exactamente lo contrario. Definido primero, definido el segundo. Es decir, si probamos con los mismos ejemplo que el apartado anterior, veremos como el resultado es el contrario, es decir `False` donde era `True` y viceversa.
"""

print('La comparación 4!=4 es', 4!=4)
print('La comparación 4!=5 es', 4!=5)
print('La comparación 4!=4.0 es', 4!=4.0)
print('La comparación 0!=False es', 0!=False)
print('La comparación "asd"!="asd" es', "asd"!="asd")
print('La comparación "asd"!="asdf" es', "asd"!="asdf")
print('La comparación 2!="2" es', 2!="2")
print('La comparación [1, 2, 3] != [1, 2, 3] es', [1, 2, 3] != [1, 2, 3])

"""## Operador >
El operador `>` devuelve `True` si el primer valor es mayor que el segundo y `False` de lo contrario.
"""

print(f"x > y -> {x} > {y} =", x>y)
print(f"y > x -> {y} > {x} =", y>x)

"""Algo bastante curioso, es como Python trata al tipo booleano.

Por ejemplo, podemos ver como True es igual a 1, por lo que podemos comprar el tipo True como si de un número se tratase.
"""

print('El valor True==1 es', True==1)
print('El valor True>0.999 es', True>0.999)

"""Para saber más: De hecho, el tipo bool en Python hereda de la clase int. Si quieres saber más acerca del tipo bool en Python puedes leer la [PEP285](https://www.python.org/dev/peps/pep-0285/)

También se pueden comparar listas. Si los elementos de la lista son numéricos, se comparará elemento a elemento.
"""

print('La comparación [1, 2] > [10, 10] es', [1, 2] > [10, 10])
print('La comparación [10, 10] > [1, 2] es', [10, 10] > [1, 2])

print()
print('Que pasa si las listas tienen diferente tamaño.')
print('La comparación [10, 10, 11] > [1, 2] es', [10, 10, 11] > [1, 2])
print('La comparación [10, 10] > [1, 2, 22] es', [10, 10] > [1, 2, 22])


print()
print('Que pasa si las listas tienen diferente tamaño.')
print('La comparación [1, 2] > [10, 10, 11] es', [1, 2] > [10, 10, 11])
print('La comparación [1, 2, 22] > [10, 10] es', [1, 2, 22] > [10, 10])

"""En el caso de que las listas sean de diferente tamaño, solo se comparan las posiciones que coinciden y el resto de los valores se descartan.

## Operador <
El operador `<` devuelve True si el primer elemento es mayor que el segundo. Es totalmente válido aplicar operadores relacionales como `<` sobre cadenas de texto, pero el comportamiento es un tanto difícil de ver a simple vista.

Por ejemplo abc es menor que abd y A es menor que a
"""

print('Vamos a comparar "abc" < "abd":', "abc" < "abd")
print('Vamos a comparar "A" < "a":', "A"<"a")

"""Para el caso de A y a la explicación es muy sencilla, ya que Python lo que en realidad está comparando es el valor entero Unicode que representa tal caracter. La función `ord` nos da ese valor. Por lo tanto cuando hacemos "A"<"a" lo que en realidad hacemos es comprar dos números."""

print('El valor ordinal de A es', ord('A'))
print('El valor ordinal de a es', ord('a'))

"""Para saber más: En el siguiente [enlace](http://docs.python.org/tutorial/datastructures.html#comparing-sequences-and-other-types) tienes más información de como Python compara variables que no son números.

## Operador >=
Similar a los anteriores, `>=` permite comparar si el primer elemento es mayor o igual que es segundo, devolviendo True en el caso de ser cierto.
"""

print('La comparación 3>=3 es',3>=3)
print('La comparación [3,4] >= [3,5] es', [3,4] >= [3,5])

"""## Operdor <=
De la misma manera, `<=` devuelve True si el primer elemento es menor o igual que el segundo. Nos podemos encontrar con cosas interesantes debido a la precisión numérica existente al representar valores, como el siguiente ejemplo.
"""

print('La comparación 3<=2.99999999999999999 es', 3<=2.99999999999999999)
print('La comparación 3<=2.999 es', 3<=2.999)