# -*- coding: utf-8 -*-
"""Semana_05-06_Operadores_membresia.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UfDG8JFPrUyTUAP26ucccwiFAH4schdz

## Operadores de membresía
Los operadores de membresía o membership operators son operadores que nos permiten saber si un elemento esta contenido en una secuencia. Por ejemplo si un número está contenido en una lista de números.

| Operador | Nombre                                 | Ejemplo |
|:--------:|:--------------------------------------:|:-------:|
| in       | `True` si el elemento esta contenido     | xxx     |
| not in   | `False` si el elemento no esta contenido | xxx     |

## Operador in
El operador `in` nos permite ver si un elemento esta contenido dentro de una secuencia, como podría ser una lista. En el siguiente ejemplo se ve un caso sencillo donde se verifica si 3 esta contenido en la lista [1, 2, 3]. Como efectivamente lo está, el resultado es True.
"""

a=3
b=[1, 2, 3]
print(f'El valor {a} in {b}: {a in b}')

"""Vamos a complicar las cosas un poco y explorar los límites del operador. Que pasaría si intentásemos hacer algo como lo que se ve en el siguiente ejemplo. Podría ser lógico pensar que `3 in 3` sería `True`, porque realmente si que parece que el 3 esta contenido en el segundo 3. Pues no, el siguiente código daría un error, diciendo que la clase int no es iterable. En otros capítulos exploraremos más acerca de esto. Por ahora nos basta con decir que el elemento a la derecha del in debe ser un objeto tipo lista"""

import traceback

try:
  print(3 in 3) # Error!
except TypeError:
  traceback.print_exc()

"""Vamos a darle una última vuelta de tuerca. Podríamos también ver si una lista está contenida en otra lista. En este caso, la lista de la derecha del `in` es una lista embebida dentro de otra lista. Como [1, 2] está dentro de la segunda lista, el resultado es `True`"""

c = [1, 2]
d = [4, [1, 2], 7]

print(f'El id de c ({c}) es {id(c)}')
print(f'El id de d ({d}) es {id(d)}')
print(f'El id de d ({d[1]}) es {id(d[1])}')
print(f'El valor {c} in {d}: {c in d}')

"""Como podemos observar está comparando cada elemento de la lista y verifica que sea una lista.

Ahora vamos a agregar un elemento a la variable `d` para demostrar que verifica que la variable `c` este completa.
"""

c = [1, 2]
d = [4, [1, 2, 3], 7]

print(f'El id de c ({c}) es {id(c)}')
print(f'El id de d ({d}) es {id(d)}')
print(f'El id de d ({d[1]}) es {id(d[1])}')
print(f'El valor {c} in {d}: {c in d}')

"""## Operador not in
Por último, el operador `not in` realiza lo contrario al operador `in`. Verifica que un elemento no está contenido en otra secuencia. En el siguiente ejemplo se puede ver como 3 no es parte de la secuencia, por lo que el resultado es False
"""

a=4
b=[1, 2, 3]
print(f'El valor {a} not in {b}: {a not in b}')

"""La verdad que ambos operadores in y not in son muy útiles y nos ahorran mucho trabajo. Es importante tenerlo en cuenta, porque no otros lenguajes de programación no existen tales operadores, y debemos escribir código extra para obtener tal funcionalidad. Una forma de implementar nuestro operador in y is not con una función sería la siguiente. Simplemente iteramos la lista y si encontramos el elemento que estábamos buscando devolvemos True, de lo contrario False."""

a=3
lista=[1, 2, 3, 4, 5]

# Función que implementa "is" y "is not"
def estaContenido(a, lista):
  for l in lista:
    if a==l:
      return True
  return False

print(estaContenido(a, lista))

"""Para saber más: Te dejamos un [enlace](https://docs.python.org/3/reference/expressions.html#membership-test-operations) a la documentación oficial acerca de los operadores de membresía."""