# -*- coding: utf-8 -*-
"""Semana_05-05_Operadores_identidad.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oAutLnsRbsaiF-JDAe0kGRd_Lj2TtXvf

## Operadores de Identidad
El operador de identidad o identity operator `is` nos indica si dos variables hacen referencia al mismo objeto. Esto implica que si dos variables distintas tienen el mismo `id`, el resultado de aplicar el operador `is` sobre ellas será booleano.

| Operador | Nombre                                                  |
|:--------:|:-------------------------------------------------------:|
| is       | Devuelve `True` si hacen referencia a el mismo objeto     |
| is not   | Devuelve `False` si no hacen referencia a el mismo objeto |

## Operador is
El operador `is` comprueba si dos variables hacen referencia a el mismo objeto. En el siguiente ejemplo podemos ver como al aplicarse sobre a y b el resultado es `True`.
"""

a = 10
b = 10

print(f'El valor de a es {a} y su id es {id(a)}')
print(f'El valor de b es {b} y su id es {id(b)}')
print(f'La operación a is b es {a is b}')

"""Esto es debido a que Python reutiliza el mismo objeto que almacena el valor 10 para ambas variables. De hecho, si usamos la función id(), podemos ver que el objeto es el mismo.

Esto se debe a una optimización de la memoria y el uso de cpu porque el tipo de dato es inmutable.

En el siguiente ejemplo, podemos ver como a y b almacenan el mismo valor, por lo que `==` nos indica `True`.
"""

print(f'La operación a == b es {a == b}')

a = [1, 2, 3]
b = [1, 2, 3]

print(f'El valor de a es {a} y su id es {id(a)}')
print(f'El valor de b es {b} y su id es {id(b)}')
print(f'La operación a is b es {a is b}')

"""Sin embargo, por como Python funciona por debajo, almacena el contenido en dos objetos diferentes. Al tratarse de objetos diferentes, esto hace que el operador `is` devuelva `False`.

A diferencia de antes, podemos ver como la función `id` en este caso nos devuelve un valor diferente.

Esta diferencia puede resultar algo liosa, por lo que te recomendamos que leas más acerca de la [mutabilidad](https://ellibrodepython.com/mutabilidad-python) en Python.

Para saber más: Si quieres saber más acerca del operador id() te dejamos este enlace a la documentación oficial.

## Operador is not
Una vez definido `is`, es trivial definir `is not` porque es exactamente lo contrario. Devuelve `True` cuando ambas variables no hacen referencia al mismo objeto.
"""

# Python crea dos objetos diferentes, uno
# para cada lista. Las listas son mutables.
a = [1, 2, 3]
b = [1, 2, 3]

print(f'El valor de a es {a} y su id es {id(a)}')
print(f'El valor de b es {b} y su id es {id(b)}')
print(f'La operación a is not b es {a is not b}')

# Python reutiliza el objeto que almacena 5
# por lo que ambas variables apuntan a el mismo
a = 5
b = 5

print(f'El valor de a es {a} y su id es {id(a)}')
print(f'El valor de b es {b} y su id es {id(b)}')
print(f'La operación a is not b es {a is not b}')

"""Para saber más: Te dejamos un [enlace](https://docs.python.org/3/reference/expressions.html#is) muy interesante con más información sobre el is y is not."""