# -*- coding: utf-8 -*-
"""Semana_05-07_Operadores_asignacion.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NRp74F9jmn8C9s6i4YcV5MaqaMy9sDJI

## Operadores de asignación
Anteriormente hemos visto los operadores aritméticos, que usaban dos números para calcular una operación aritmética (como suma o resta) y devolver su resultado. En este caso, los operadores de asignación o assignment operators nos permiten realizar una operación y almacenar su resultado en la variable inicial. Podemos ver como realmente el único operador nuevo es el `=`. El resto son abreviaciones de otros operadores que habíamos visto con anterioridad.

Ponemos un ejemplo con `x=7`

Operadores artiméticos.

| Operador | Ejemplo | Equivalente |
| :---: | :---: | :---: |
| =                | x=7                | x=7                      |
| +=               | x+=2               | x=x+2 = 9                |
| -=               | x-=2               | x=x-2 = 5                |
| *=               | x*=2               | x=x*2 = 14               |
| /=               | x/=2               | x=x/2 = 3.5              |
| %=               | x%=2               | x=x%2 = 1                |
| //=              | x//=2              | x=x//2 = 3               |
| **=              | x**=2              | x=x**2 = 49              |




Operadores binarios.

Para cada caso `x=7`

La representación de los números binarios es:

- 28 = 11100
-  7 =  1111
-  5 =  0111
-  2 =  0010
-  1 =  0001

| Operador | Ejemplo | Equivalente |
| :---: | :---: | :---: |
| &amp;=           | x&amp;=2           | x=x&amp;2 = 2            |
| \|=               | x\|=2               | x=x\|2 = 7                |
| ^=               | x^=2               | x=x^2 = 5                |
| &gt;&gt;=        | x&gt;&gt;=2        | x=x&gt;&gt;2 = 1         |
|  &lt;&lt;= |  x&lt;&lt;=2 |  x=x&lt;lt;2 = 28 |
"""

a=7; b=2
print("Operadores artiméticos")
x=a; x+=b;  print(f"El valor x es: {a}, el valor a operar es {b}, por lo tanto x+={b} -> {x}")
x=a; x-=b;  print(f"El valor x es: {a}, el valor a operar es {b}, por lo tanto x-={b} -> {x}")
x=a; x*=b;  print(f"El valor x es: {a}, el valor a operar es {b}, por lo tanto x*={b} -> {x}")
x=a; x/=b;  print(f"El valor x es: {a}, el valor a operar es {b}, por lo tanto x/={b} -> {x}")
x=a; x%=b;  print(f"El valor x es: {a}, el valor a operar es {b}, por lo tanto x%={b} -> {x}")
x=a; x//=b;  print(f"El valor x es: {a}, el valor a operar es {b}, por lo tanto x//={b} -> {x}")
x=a; x**=b;  print(f"El valor x es: {a}, el valor a operar es {b}, por lo tanto x**={b} -> {x}")

print("Operadores binarios")

x=a; x&=b;  print(f"El valor x es: {a}, el valor a operar es {b}, por lo tanto x&={b} -> {x}")
x=a; x|=b;  print(f"El valor x es: {a}, el valor a operar es {b}, por lo tanto x|={b} -> {x}")
x=a; x^=b;  print(f"El valor x es: {a}, el valor a operar es {b}, por lo tanto x^={b} -> {x}")
x=a; x>>=b;  print(f"El valor x es: {a}, el valor a operar es {b}, por lo tanto x>>={b} -> {x}")
x=a; x<<=b;  print(f"El valor x es: {a}, el valor a operar es {b}, por lo tanto x<<={b} -> {x}")

"""## Operador +=

Como podemos ver, todos los operadores de asignación no son más que atajos para escribir otros operadores de manera más corta, y asignar su resultado a la variable inicial. El operador `+=` en `x+=1` es equivalente a `x=x+1`.

Sabiendo esto, sería justo preguntarse ¿realmente merece la pena crear un operador nuevo que hace algo que ya podemos hacer pero de manera mas corta? Bien, la pregunta no es fácil de responder y en cierto modo viene heredado de lenguajes como C que en los años 1970s introdujeron esto.

"""

x=5      # Ejemplo de como incrementar
x+=1     # en una unidad x
print('El valor de x es', x)

"""*Para saber más:* Aunque se podría decir que el operador `x+=1` es igual que `x=x+1`, no es del todo cierto. De hecho el operador que Python invocado por debajo es `__iadd__` en el primer caso frente a `__add__` para el segundo. A efectos prácticos, se podría considerar lo mismo, pero [aquí](https://docs.python.org/3/reference/datamodel.html#object.__iadd__) puedes leer más sobre esto

Se puede jugar un poco con el operador `+=` y aplicarlo sobre variables que no necesariamente son números. Como vimos en otros capítulos, se podría emplear sobre una lista.
"""

x=[1,2,3] # En este caso la x es una lista
x+=[4,5]  # Se aplica el operador sobre otra lista
print('El valor de x es', x)

"""Es muy importante, que si `x` es una lista, no podemos aplicar el operador `+=` con un elemento que no sea una lista, como por ejemplo, un número. El siguiente código daría error porque el operador no esta definido para un elemento lista y otro entero."""

import traceback

x=[1,2,3]
try:
  x+=3 # Error
except TypeError:
  traceback.print_exc()

"""## Operador -=
El operador `-=` es equivalente a restar y asignar el resultado a la variable inicial. Es decir, `x-=1` es equivalente a `x=x-1`. Si vienes de otros lenguajes de programación, tal vez conozcas la forma `x--`, pero en Python no existe. El operador es muy usado para decrementar el valor de una variable.
"""

i = 5
i -= 1
print('El valor de i es', i)

"""Y algo que nunca se haría en la realidad, pero nos permite explorar los límites del lenguaje, sería restar -1, lo que equivale a sumar uno. Pero de verdad, no hagas esto, en serio."""

i = 0
i-=-1    # Aumenta el contador
print('El valor de i es', i)

"""## Operador *=
El operador `*=` equivale a multiplicar una variable por otra y almacenar el resultado en la primera, es decir `x*=2` equivale a `x=x*2`. Hasta ahora hemos usado todos los operadores de asignación con una variable y un número, pero es totalmente correcto hacerlo con dos variables.
"""

a=10; b=2 # Inicializamos a 10 y 20
a*=b      # Usando dos variables
print('El valor de a es', a)

"""## Operador /=
El operador `/=` equivale a dividir una variable por otra y almacenar el resultado en la primera, es decir, `x/=2` equivale a `x=x/2`. Acuérdate que en otros capítulos vimos como `5/3` en versiones antiguas de Python, podía causar problemas ya que el resultado no era un numero entero. En el siguiente ejemplo podemos ver como Python hace el trabajo por nosotros, y cambia el tipo de la variable `x` de lo que inicialmente era `int` a un `float` con el objetivo de que el nuevo valor pueda ser almacenado.
"""

x = 10
print('El valor de x es', x, ' y el tipo es', type(x))
x/=3
print('El valor de x es', x, ' y el tipo es', type(x))

"""## Operador %=
El operador %= equivale a hacer el módulo de la división de dos variables y almacenar su resultado en la primera.
"""

x = 3
x%=2
print('El valor de x es', x)

"""## Operador //=
El operador `//=` realiza la operación cociente entre dos variables y almacena el resultado en la primera. El equivalente de `x//=2` sería `x=x//2`.
"""

x=5      # El resultado es el cociente
x//=3    # de la división
print('El valor de x es', x)

"""## Operador **=
El operador `**=` realiza la operación exponente del primer número elevado al segundo, y almacena el resultado en la primera variable. El equivalente de `x**=2` sería `x=x**2`.


"""

x=5      # Eleva el número al cuadrado
x**=2    # y guarda el resultado en la misma
print('El valor de x es', x)

"""Otro ejemplo similar, sería empleando un exponente negativo, algo que es totalmente válido y equivale matemáticamente al inverso del número elevado al exponente en positivo. Dicho de otra forma, $x^{-2}$ equivale a $1/x^2$."""

x=5      # Elevar 5 a -2 equivale a dividir
x**=-2   # uno entre 25.
print('El valor de x es', x)

"""## Operador &=
El operador `&=` realiza la comparación `&` bit a bit entre dos variables y almacena su resultado en la primera. El equivalente de `x&=1` sería `x=x&1`
"""

a = 0b101010 # número 42
a&= 0b111111 # número 63
print('El valor de a es', bin(a), 'o su equivalente decimal', a)

"""## Operador |=
El operador `|=` realiza el operador `|` elemento a elemento entre dos variables y almacena su resultado en la primera. El equivalente de `x|=2` sería `x=x|2`
"""

a = 0b101010 # número 42
a|= 0b111111 # número 63
print('El valor de a es', bin(a), 'o su equivalente decimal', a)

"""## Operador ^=
El operador `^=` realiza el operador `^` elemento a elemento entre dos variables y almacena su resultado en la primera. El equivalente de `x^=2` sería `x=x^2`
"""

a = 0b101010 # número 42
a^= 0b111111 # número 63
print('El valor de a es', bin(a), 'o su equivalente decimal', a)

"""## Operador >>=
El operador `>>=` es similar al operador `>>` pero permite almacenar el resultado en la primera variable. Por lo tanto `x>>=3` sería equivalente a `x=x>>1`
"""

a = 0b10 # número 2
a>>=1
print('El valor de a es', bin(a), 'o su equivalente decimal', a)

"""Es importante tener cuidado y saber el tipo de la variable x antes de aplicar este operador, ya que se podría dar el caso de que `x` fuera una variable tipo `float`. En ese caso, tendríamos un error porque el operador `>>` no esta definido para `float`."""

x=10.0         # Si la x es float
print('El tipo de la variable es:', type(x))
try:
  x>>=1         # ERROR!
except TypeError:
  traceback.print_exc()

"""## Operador <<=
Muy similar al anterior, `<<=` aplica el operador `<<` y almacena su contenido en la primera variable. El equivalente de `x<<=1` sería `x=x<<1`
"""

a = 0b10 # número 2
a<<=1
print('El valor de a es', bin(a), 'o su equivalente decimal', a)

"""Sería justo pensar que si `<<` realiza un desplazamiento de bits a la izquierda y `>>` lo realiza a la derecha, tal vez un desplazamiento `<<` de una unidad, podría equivaler a `-1` desplazamiento a la derecha."""

try:
  x<<=-1 # ERROR! Python no define un desplazamiento negativo a la izquierda
except TypeError:
  traceback.print_exc()

try:
  x>>=-1 # ERROR! Python no define un desplazamiento negativo a la derecha
except TypeError:
  traceback.print_exc()