# -*- coding: utf-8 -*-
"""Semana_03-05_String.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1v9PxvdpyrrtxRPGbxzDVvrPtBpUljLg0

## str

Las cadenas de texto en Python o strings son un tipo inmutable que permite almacenar secuencias de caracteres. Para crear una, es necesario incluir el texto entre comillas dobles `"` o simples `'`.

Puedes obtener más ayuda con el comando help.
"""

help(str)

s:str = "Esto es una cadena"

print('La variable s contiene: ', s)
print('La variable s es de tipo: ', type(s))

"""También es valido declarar las cadenas con comillas simples simples '.


"""

s:str = 'Esto es otra cadena'

print('La variable s contiene: ', s)
print('La variable s es de tipo: ', type(s))

"""Las cadenas no están limitadas en tamaño, por lo que el único límite es la memoria de tu ordenador. Una cadena puede estar también vacía."""

s:str = ''
print('La variable s contiene: ', s)

"""## Caracter de escape `\`

Una situación que muchas veces se puede dar, es cuando queremos introducir una comilla, bien sea simple `'` o doble `"` dentro de una cadena. Si lo hacemos de la siguiente forma tendríamos un error, ya que Python no sabe muy bien donde empieza y termina.

```
s = "Esto es una comilla doble " de ejemplo" # Error!
 SyntaxError: unterminated string literal (detected at line 1)
```

Para resolver este problema debemos recurrir a las secuencias de escape `\`.

Por ahora, la más importante es `\"`, que nos permite incrustar comillas dentro de una cadena.
"""

s:str = "Esto es una comilla doble \" de ejemplo"
print('La variable s contiene: ', s)

"""## Nueva línea `\n`

Un salto de línea se puede agregar a una cadena si agregamos el `\n`, lo que significa que al querer imprimir un mensaje por pantalla, la función `print`, al encontrarse con este caracter se producirá un salto, se imprimirá en una nueva línea.
"""

s:str = "Primer linea\nSegunda linea"
print(s)

"""## Caracter de escape e int

También podemos usar `\` acompañado de un número entero, lo que imprimirá el carácter asociado a la tabla ASCII. En este caso imprimimos el carácter 110 que se corresponde con la H y el 111 que corresponde a la I.
"""

print("\110\111")

"""Te recomiendo que busques información sobre [ASCII](https://en.wikipedia.org/wiki/ASCII#Control_code_chart) y [Unicode](https://en.wikipedia.org/wiki/Unicode). Ambos son conceptos muy útiles a la hora de entender los strings.
Para la tabla ASCII tendras que observar la columna de los octales o oct.

Se puede definir una cadena que ocupe varias líneas usando triple `'''` comilla. Puede ser muy útil si tenemos textos muy largo que no queremos tener en una sola línea.

Existe también otra forma de declarar cadenas llamado raw strings. Usando como prefijo `r`, la cadena ignora todos las secuencias de escape, por lo que la salida es diferente a la anterior.
"""

print(r"\110\111")

"""## Función str

Es posible convertir un determinado valor a str usando la función `str`.
"""

print('10: ', str(10))
print('True: ', str(True))
print('[]: ', str([]))

"""## [Docstring](https://peps.python.org/pep-0257/)

Son los literales de cadena que aparecen justo después de la definición de una función, método, clase o módulo. Se utilizan para escribir varias renglones de un string sin tener que utilizar los separadores.

Se utilizan para documentar funciones, métodos, clases y son muy importantes a la hora del desarrollo. Existen varias formas de escribirlos pero una de las más utilizadas es la que propone [google](https://google.github.io/styleguide/pyguide.html).

Ejemplo con docstring que sirve solo a modo didáctico ya que no estamos documentando nada.
"""

print("""La siguiente
cadena ocupa
varias lineas""")

"""Ejemplo con separadores"""

print("La siguiente \n" \
"cadena ocupa \n" \
"varias lineas")

"""## Formateo de cadenas
Tal vez queramos declarar una cadena que contenga variables en su interior, como números o incluso otras cadenas. Una forma de hacerlo sería concatenando la cadena que queremos con otra usando el operador `+`. Nótese que `str` convierte en string lo que se pasa como parámetro.
"""

x:int = 5
s:str = "El número es: " + str(x)
print(s)

"""Otra forma es usando `%`. Por un lado tenemos `%s` que indica el tipo que se quiere imprimir, y por otro a la derecha del `%` tenemos la variable a imprimir. Para imprimir una cadena se usaría `%s` o `%f` para un valor en coma flotante.

En el siguiente [enlace](https://docs.python.org/3/library/stdtypes.html#printf-style-string-formatting) puedes encontrar más información sobre el uso de `%`.
"""

x:int = 5
s:str = "El número es: %d" % x
print(s)

"""Si tenemos más de una variable, también se puede hacer pasando los parámetros dentro de `()`. Si vienes de lenguajes como C, esta forma te resultará muy familiar. No obstante, esta no es la forma preferida de hacerlo, ahora que tenemos nuevas versiones de Python."""

s:str = "Los números son %d y %d." % (5, 10)
print(s)

"""Una forma un poco más moderna de realizar lo mismo, es haciendo uso de `format`. En este caso cada `{}` será reemplazado por el valor que se encuentra en la misma posición que los parámetros que recibe la función `format`.


"""

s:str = "Los números son {} y {}".format(5, 10)
print(s)

"""Es posible también darle nombre a cada elemento, y format se encargará de reemplazar todo.


"""

s:str = "Los números son {a} y {b}".format(a=5, b=10)
print(s)

"""Por si no fueran pocas ya, existe una tercera forma de hacerlo introducida en la versión 3.6 de Python. Reciben el nombre de cadenas literales o f-strings. Esta nueva característica, permite incrustar expresiones dentro de cadenas."""

a:int = 5; b:int = 10
s:str = f"Los números son {a} y {b}"
print(s)

"""Puedes incluso hacer operaciones dentro de la creación del string.


"""

a:int = 5; b:int = 10
s:str = f"a + b = {a+b}"
print(s)

"""Puedes incluso llamar a una función dentro.


"""

def funcion():
    return 20

s:str = f"El resultado de la función es {funcion()}"
print(s)

"""## Ejemplos string
Para entender mejor la clase string, vamos a ver unos ejemplos de como se comportan. Podemos sumar dos strings con el operador +.
"""

s1:str = "Parte 1"
s2:str = "Parte 2"
print(s1 + " " + s2)

"""Se puede multiplicar un string por un int. Su resultado es replicarlo tantas veces como el valor del entero."""

s:str = "Hola "
print(s*3)

"""Podemos ver si una cadena o parte de ella está contenida en otra con `in`.


"""

print("ytho" in "Hola Python")

"""Con `chr` y `ord` podemos convertir entre carácter y su valor numérico que lo representa y viceversa. El segundo solo funciona con un caracter, es decir, un string con un solo elemento."""

print(chr(36))
print(ord("$"))

"""La longitud de una cadena viene determinada por su número de caracteres, y se puede consultar con la función len()."""

print(len("Esta es mi cadena"))

"""Como hemos visto al principio, se puede convertir a string otras clases, como int o float."""

x:str = str(10.4)
print('La variable x posee el valor: ', x)
print('La variable x es de tipo: ', type(x))

"""Las cadenas se pueden indexar, es decir, que podemos acceder al caracter que se encuentra en una posición determina utilizando los corchetes y la posición. La posición es un número entero o int que comienza desde el valor `0` y en caso de ser negativo comienza desde el final hacia el inicio, por ejemplo el `-1` retorna el último caracter.


"""

x:str = "abcde"
print(x[0])
print(x[-1])

"""## Slicing

La expresión slicing hace referencia a la operación por la cual se extraen elementos de una secuencia. Dependiendo del caso, los elementos podrían ser consecutivos o podrían estar separados dentro de la secuencia original. Dado que esta operación es de uso bastante frecuente, Python ofrece características que hacen posible construir slices de forma breve, sin tener que construir funciones especializadas para hacerlo.

La forma de construción es: `[inicio:fin:paso]`

- inicio: es un entero que indica la posición de inicio para la construcción. El valor de inicio es inclusive. Sino se indica el valor de inicio entonces por defecto se comienza desde 0.
- fin: es un entero que indica la posición de fin para la construcción. El valor de fin es no inclusivo. Sino se indica el valor de fin entonces por defecto es la longitud total de la cadena.
- paso: es un entero que indica cuantos pasos hacia adelante o hacia atrás se van a realizar para la construcción. Sino se indica el valor de paso entonces por defecto es 1.

Vamos a utilizar de ejemplo la cadena "abcde" donde las posiciones son:

| Letras | a | b | c | d | e |
| --- | --- | --- | --- | --- | --- |
| Posiciones | 0 | 1 | 2 | 3 | 4 |

Vamos a obtener las 2 primeras letras de la cadena.
"""

x:str = "abcde"
print(x[0:2])

"""Si no se indica ningún valor a la derecha de los : se llega hasta el final.


"""

x:str = "abcde"
print(x[2:])

"""Es posible también crear subcadenas que contengan elementos salteados y no contiguos añadiendo un tercer elemento entre []. Indica los elementos que se saltan. En el siguiente ejemplo se toman elementos del 0 al 3 de dos en dos."""

x:str = "abcde"
print(x[0:3:2])

"""Tampoco es necesario saber el tamaño de la cadena, y el segundo valor se podría omitir. El siguiente ejemplo es igual al anterior."""

x:str = "abcde"
print(x[0::2])

"""## Métodos string
Algunos de los métodos de la clase string.

### capitalize
El método capitalize se aplica sobre una cadena y la devuelve con su primera letra en mayúscula.
"""

s:str = "mi cadena"
print(s.capitalize())

"""### lower
El método lower convierte todos los caracteres alfabéticos en minúscula.
"""

s:str = "MI CADENA"
print(s.lower())

"""### swapcase
El método swapcase convierte los caracteres alfabéticos con mayúsculas en minúsculas y viceversa.
"""

s:str = "mI cAdEnA"
print(s.swapcase())

"""### upper
El método upper convierte todos los caracteres alfabéticos en mayúsculas.
"""

s:str = "mi cadena"
print(s.upper())

"""### count(sub[, start[, end]])
El método count permite contar las veces que otra cadena se encuentra dentro de la primera. Permite también dos parámetros opcionales que indican donde empezar y acabar de buscar.
"""

s:str = "el bello cuello "
print(s.count("llo"))
print(s.count("llo", 0, 9))

"""### isalnum
El método isalnum devuelve True si la cadena esta formada únicamente por caracteres alfanuméricos, False de lo contrario. Caracteres como @ o & no son alfanumericos.
"""

s:str = "correo@dominio.com"
print(s.isalnum())

"""### isalpha
El método isalpha devuelve True si todos los caracteres son alfabéticos, False de lo contrario.
"""

s:str = "abcdefg"
print(s.isalpha())

"""### strip
El método strip elimina a la izquierda y derecha el carácter que se le introduce. Si se llama sin parámetros elimina los espacios. Muy útil para limpiar cadenas.
"""

s:str = "  abc  "
print(f'|{s}|')
print(f'|{s.strip()}|')

"""### zfill(<width>)
El método zfill rellena la cadena con ceros a la izquierda hasta llegar a la longitud pasada como parámetro.
"""

s:str = "123"
print(s.zfill(5))

"""### join(<iterable>)
El método join devuelve la primera cadena unida a cada uno de los elementos de la lista que se le pasa como parámetro.
"""

s:str = " y ".join(["1", "2", "3"])
print(s)

"""### split(sep=None, maxsplit=-1)
El método split divide una cadena en subcadenas y las devuelve almacenadas en una lista. La división es realizada de acuerdo a el primer parámetro, y el segundo parámetro indica el número máximo de divisiones a realizar.
"""

s:str = "Python,Java,C"
print(s.split(","))
print(s.split(sep=",", maxsplit=1))

"""Notesé que en la segunda impresión los valores de `Java,C` están unidos. Esto se debe a que le pedimos que solo realice 1 separación."""