# -*- coding: utf-8 -*-
"""Semana_03-Practica_03.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TMBxsijJg4GFCrpFSJ5IPNkEy-4GZrDK

# Ejercicio 1

Pedir un número entero al usuario y determinar si es par o impar.8
"""



"""# Ejercicio 2

Calcular el área de un círculo con radio introducido por el usuario.
"""



"""
# Ejercicio 3

Determinar si un triángulo es rectángulo a partir de sus longitudes de lado. El usuario debe ingresar los 3 lados.
Debemos aplicar el teorema de Pitágoras.

$a^2 + b^2 = h^2$

Donde a y b son los lados y h es la hipotenusa.
"""



"""# Ejercicio 4

Invertir el orden de una cadena ingresada por el usuario.
"""



"""# Ejercicio 5

Ingresar palabras a una lista y ordenar alfabéticamente la lista.

Se dejan de ingresar palabras cuando la palabra ingresada es una cadena vacia.
"""



"""# Ejercicio 6

Ingresar una lista de números y calcular el promedio.

Se dejan de ingresar palabras cuando la número ingresado es 0.
"""



"""# Ejercicio 7

Ingresar una frase por teclado, pasar la frase a un diccionario, donde la key del diccionario sea la posición de la palabra dentro de la frase y el value sea la palabra misma.

Al final imprimir la posición:palabra. Se debe mostrar desde el diccionario.
"""



"""# Ejercicio 8

Ingresar una frase por teclado, pasar la frase a un diccionario, donde la key del diccionario sea la palabra y el value sea una lista con la posición de la ocurrencia de cada palabra.

Al final imprimir el diccionario con el formato palabra:posiciones.
"""

