# -*- coding: utf-8 -*-
"""Semana_03-02_Entero.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VWfltfD6Xzi9TRKP9v1QxZ4ti_IRZU0K

## int
Los enteros en Python o también conocidos como int, son un tipo de datos que permite representar números enteros, es decir, positivos y negativos no decimales. Si vienes de otros lenguajes de programación, olvídate de los int8, uint16 y demás. Python nos da un sólo tipo que podemos usar sin preocuparnos del tamaño del número almacenado por debajo.

Puedes obtener más ayuda con el comando help.
"""

help(int)

"""La función [type()](https://docs.python.org/3/glossary.html#term-type) nos devuelve el tipo de la variable, y podemos ver como efectivamente es de la clase int."""

i:int = 12
print('El valor almacenado en la variable i es: ', i)
print('El tipo de dato almacenado en la variable i es: ', type(i))

"""En otros lenguajes de programación, los int tenían un valor máximo que pueden representar. Dependiendo de la longitud de palabra o wordsize de la arquitectura del ordenador, existen unos números mínimos y máximos que era posible representar. Si por ejemplo se usan enteros de 32 bits el rango a representar es de -2^31 a 2^31–1, es decir, -2.147.483.648 a 2.147.483.647. Con 64 bits, el rango es de -9.223.372.036.854.775.808 hasta 9.223.372.036.854.775.807. Una gran ventaja de Python es que ya no nos tenemos que preocupar de esto, ya que por debajo se encarga de asignar más o menos memoria al número, y podemos representar prácticamente cualquier número."""

x:int = 250**250
print('El valor almacenado en la variable x es: ', x)
print('El tipo de dato almacenado en la variable x es: \n', type(x))

"""Si vienes de otras versiones de Python, tal vez eches de menos el tipo long. Puedes leer la [PEP237](https://peps.python.org/pep-0237/), donde se explica porqué se unificó los long y los int.

## Función bool
También es posible convertir un determinado valor a entero usando la función int().

Podemos observar como el valor booleano `True` se transforma en un `1` y el `False` en un `0`.
"""

print('10: ', int(10))
print('-10.523: ', int(-10.523))
print('True: ', int(True))
print('False: ', int(False))

"""## Ejemplos

En el primer ejemplo hemos asignado un número entero a una variable, pero también es posible asignar valores en binario, hexadecimal y octal.

Los prefijos son:
- `0b`: indica que lo que viene a continuación será interpretado como un número [binario](https://es.wikipedia.org/wiki/Sistema_binario).
- `0x`: indica que lo que viene a continuación será interpretado como un número en [hexadecimal](https://es.wikipedia.org/wiki/Sistema_hexadecimal).
- `0c`.  indica que lo que viene a continuación será interpretado como un número en [octal](https://es.wikipedia.org/wiki/Sistema_octal).

Al imprimir, el número se convierte en entero para todos los casos.
"""

a:int = 0b100
b:int = 0x17
c:int = 0o720
print('El valor de la variable a es: ',a,' - el tipo de la variable es : ', type(a))
print('El valor de la variable b es: ',b,' - el tipo de la variable es : ', type(b))
print('El valor de la variable c es: ',c,' - el tipo de la variable es : ', type(c))

"""Con el siguiente ejemplo podemos ver como Python asigna diferente número de bits a las variables en función del número que quieren representar.

La función [getsizeof()](https://docs.python.org/3/library/sys.html#sys.getsizeof) devuelve el tamaño de una variable en memoria en [bytes](https://es.wikipedia.org/wiki/Byte).
"""

import sys

x:int = 5**100
y:int = 10
print('La variable x contiene el valor ', x, ', su tipo es ', type(x), ' y ocupa en memoria un total de ',sys.getsizeof(x), ' bytes o ', sys.getsizeof(x)*8,' bits.')
print('La variable y contiene el valor ', y, ', su tipo es ', type(y), ' y ocupa en memoria un total de ',sys.getsizeof(y), ' bytes o ', sys.getsizeof(y)*8,' bits.')

"""Un caso curioso es que si intentamos representar un número aún mayor, nos encontraremos con que el resultado es [inf](https://docs.python.org/3/library/math.html#math.inf) que representa al infinito en vez de con una excepción.

Este valor lo podemos encontrar en el módulo math.

"""

import math
print('Infinito: ', math.inf)

z:int = 2e2000
print(f'La variable z contiene el valor {z}. Es infinito? {z == math.inf}')

"""## Convertir a int

El posible convertir a int otro tipo. Como hemos explicado, el tipo int no puedo contener decimales, por lo que si intentamos convertir un número decimal, se truncará todo lo que tengamos a la derecha de la coma.


"""

b:int = int(1.6)
print('La variable b contiene el valor: ', b)