# -*- coding: utf-8 -*-
"""Semana_03-Practica_03_resuelta.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10HV1Z4mjd1iCOSaIxbw7KWCqDbnCNYxQ

# Ejercicio 1

Pedir un número entero al usuario y determinar si es par o impar.8
"""



#@title Solución

par_o_impar:int = int(input('Ingrese un valor entero: '))

if par_o_impar % 2 == 0:
  print(f'El valor {par_o_impar} ingresado en par.')
else:
  print(f'El valor {par_o_impar} ingresado en impar.')

"""# Ejercicio 2

Calcular el área de un círculo con radio introducido por el usuario.
"""



#@title Solución
from math import pi

radio:float = float(input('Ingrese el radio: '))

print(f'El área del círculo que tiene un radio de {radio} es: {pi*pow(radio,2):.2f}')

"""
# Ejercicio 3

Determinar si un triángulo es rectángulo a partir de sus longitudes de lado. El usuario debe ingresar los 3 lados.
Debemos aplicar el teorema de Pitágoras.

$a^2 + b^2 = h^2$

Donde a y b son los lados y h es la hipotenusa.
"""



#@title Solución
lado_a: float(float(input('Ingrese el lado a: ')))
lado_b: float(float(input('Ingrese el lado b: ')))
hipotenusa: float(float(input('Ingrese la hipotenusa: ')))

if lado_a**2 + lado_b**2 == hipotenusa**2:
  print('El triángulo es rectangulo.')
else:
  print('El triángulo NO es rectangulo.')

"""# Ejercicio 4

Invertir el orden de una cadena ingresada por el usuario.
"""



#@title Solución

cadena:str = input('Ingrese la cadena de texto a invertir: ')

print(f'''La cadena es:
{cadena}

Su reversa es:
{cadena[::-1]}''')
# utilizo slicing: [<posicion inferior>:<posicion superior>:<paso de iteracion>]
# [::-1], es un slicing donde se obtienen los valores desde el principio, hasta
# el final y se le pone un paso de -1



# 0 1 2 3 4 5 6 7 8 9 (posiciones)
# h o l a   m u n d o (frase)

# si la frase es: hola mundo
# fase[::2] entonces retorna los valores donde el índice es par osea 'hl ud'
# fase[2:7:2] entonces retorna los valores donde el índice es par pero
#   partiendo de la posición 2 hasta la posición 6 (el extremo superior es no inclusivo)
#   osea 'l u'

#@title Solución

cadena:str = input('Ingrese la cadena de texto a invertir: ')
# transformo la cadena en una lista de letras
lista:list[str] = list(cadena)
# invierto la lista
lista.reverse()

print(f'''La cadena es:
{cadena}

Su reversa es:
{"".join(lista)}''')

"""# Ejercicio 5

Ingresar palabras a una lista y ordenar alfabéticamente la lista.

Se dejan de ingresar palabras cuando la palabra ingresada es una cadena vacia.
"""



#@title Solución
palabras:list[str] = []
palabra:str = input('Ingrese una palabra (vacio o enter para salir): ')
# con el while agrego las palabras a una lista
while len(palabra.strip()) > 0:
  palabras.append(palabra.strip())
  palabra = input('Ingrese una palabra (vacio o enter para salir): ')

if len(palabras) > 0:
  palabras.sort()
  print('La lista ordenada es:\n\t-', "\n\t- ".join(palabras))
else:
  print('No se ingresaron palabras.')

"""# Ejercicio 6

Ingresar una lista de números y calcular el promedio.

Se dejan de ingresar palabras cuando la número ingresado es 0.
"""



#@title Solución
lista_numeros:list[float] = []
numero:float = float(input('Ingrese un número (vacio o enter para salir): ') or 0)
# con el while agrego los números a una lista
while numero != 0:
  lista_numeros.append(numero)
  numero = float(input('Ingrese un número (vacio o enter para salir): ') or 0)

if len(lista_numeros) > 0:
  print('La lista de números es:\n\t-', "\n\t- ".join([str(i) for i in lista_numeros]))
  print(f'El promedio es: {sum(lista_numeros)/len(lista_numeros)}')
else:
  print('No se ingresaron números.')

"""# Ejercicio 7

Ingresar una frase por teclado, pasar la frase a un diccionario, donde la key del diccionario sea la posición de la palabra dentro de la frase y el value sea la palabra misma.

Al final imprimir la posición:palabra. Se debe mostrar desde el diccionario.
"""



#@title Solución

frase:str = input('Ingrese una frase:\n')
# armo el diccionario que me pide el enunciado
diccionario:dict[int, str] = {}
for indice,palabra in enumerate(frase.split()):
  diccionario[indice] = palabra
# recorro el diccionario para mostrarlo
for key,value in diccionario.items():
  print(f'{key}:{value}')

#@title Solución

frase:str = input('Ingrese una frase:\n')

# en una sola línea armo el diccionario y luego obtengo los items para mostrarlos
for key,value in {indice:palabra for indice,palabra in enumerate(frase.split())}.items():
  print(f'{key}:{value}')

"""# Ejercicio 8

Ingresar una frase por teclado, pasar la frase a un diccionario, donde la key del diccionario sea la palabra y el value sea una lista con la posición de la ocurrencia de cada palabra.

Al final imprimir el diccionario con el formato palabra:posiciones.
"""



#@title Solución

frase_2:str = input('Ingrese una frase:\n')
#armo el diccionario como pide el enunciado
diccionario_2:dict[str, list[int]] = {}
for indice,palabra in enumerate(frase_2.split()):
  if palabra in diccionario_2:
    # la palabra ya existe dentro de la keys del diccionario
    #   solo debo agregar la posición a la lista
    diccionario_2[palabra].append(indice)
  else:
    # la palabra NO existe dentro de la keys del diccionario y
    #   agrego la lista
    diccionario_2[palabra] = [indice]

for key,value in diccionario_2.items():
  print(f'{key}:{value}')