# -*- coding: utf-8 -*-
"""Semana_03-06_Listas.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bhPZEFWxLY-AWK94f9YbaFaZR14qR_7P

## list

Las listas en Python son un tipo de dato que permite almacenar datos de cualquier tipo. Son secuencias mutables y dinámicas, lo cual es la principal diferencia con los sets y las tuplas.

Puedes obtener más ayuda con el comando help.
"""

help(list)

"""## Crear listas Python
Las listas en Python son uno de los tipos o estructuras de datos más versátiles del lenguaje, ya que permiten almacenar un conjunto arbitrario de datos. Es decir, podemos guardar en ellas prácticamente lo que sea y cuanto queramos, siempre y cuando nos alcance la memoria. Si vienes de otros lenguajes de programación, se podría decir que son similares a los arrays.
"""

lista:list = [1, 2, 3, 4]
print('La variable lista contiene:', lista)
print('La variable lista es de tipo:', type(lista))

"""Otra opción es importar `List` desde el módulo de typing."""

from typing import List

lista:List = [1, 2, 3, 4]
print('La variable lista contiene:', lista)
print('La variable lista es de tipo:', type(lista))

"""## Función list
También es posible convertir un str a list usando la función `list`. La función recibe como parámetro un objeto iterable.
"""

lista:list = list("1234")
print('La variable lista contiene:', lista)
print('La variable lista es de tipo:', type(lista))

"""Una lista sea crea con `[]` separando sus elementos con comas `,`. Una gran ventaja es que pueden almacenar tipos de datos distintos."""

lista:list = [1, "Hola", 3.67, [1, 2, 3]]
print('La variable lista contiene:', lista)
print('La variable lista es de tipo:', type(lista))

"""Algunas propiedades de las listas:

* Son ordenadas, mantienen el orden en el que han sido definidas.
* Pueden ser formadas por tipos arbitrarios.
* Pueden ser indexadas con `[i]` y de esta forma obtener el valor de la posición`i`.
* Se pueden anidar, es decir, meter una dentro de la otra.
* Son mutables, ya que sus elementos pueden ser modificados.
* Son dinámicas, ya que se pueden añadir o eliminar elementos.

## Acceder y modificar listas

Si tenemos una lista a con 3 elementos almacenados en ella, podemos acceder a los mismos usando corchetes y un índice, que va desde 0 a n-1 siendo n el tamaño de la lista.
"""

a:list = [90, "Python", 3.87]
print('La lista a tiene en la posición 0 el contenido: ', a[0])
print('La lista a tiene en la posición 1 el contenido: ', a[1])
print('La lista a tiene en la posición 2 el contenido: ', a[2])

"""Se puede también acceder al último elemento usando el índice `[-1]`.


"""

a:list = [90, "Python", 3.87]
print('La lista a tiene el valor ', a[-1], ' en la última posición')

"""De la misma manera, al igual que [-1] es el último elemento, podemos acceder a [-2] que será el penúltimo."""

print('La lista a tiene el valor ', a[-2], ' en la última posición')

"""Y si queremos modificar un elemento de la lista, basta con asignar con el operador = el nuevo valor.


"""

print('La variable a contiene:', a)
a[2] = 1
print('La variable a contiene:', a)

"""Un elemento puede ser eliminado con diferentes métodos como veremos a continuación, o con `del` y la lista con el índice a eliminar."""

a:list = [1, 2, 3, 4, 5]
print('La variable a contiene:', a)
del a[1]
print('La variable a contiene:', a)

"""También podemos tener listas anidadas, es decir, una lista dentro de otra. Incluso podemos tener una lista dentro de otra lista y a su vez dentro de otra lista. Para acceder a sus elementos sólo tenemos que usar [] tantas veces como niveles de anidado tengamos."""

a:list = [1, 2, 3, ['p', 'q', [5, 6, 7]]]
print('Muestro la posición a[3][0]: ', a[3][0])
print('Muestro la posición a[3][2][0]: ', a[3][2][0])
print('Muestro la posición a[3][2][2]: ', a[3][2][2])

"""También es posible crear sublistas más pequeñas de una más grande. Para ello debemos de utilizar slicing. Por lo tanto [0:2] creará una lista con los elementos [0] y [1] de la original."""

a:list = [1, 2, 3, 4, 5, 6]
print('La variable a contiene:', a)

print('Muestro los valores que se encuentran en las posiciones a[0:2]: ', a[0:2])
print('Muestro los valores que se encuentran en las posiciones a[2:6]: ', a[2:6])

"""Y de la misma manera podemos modificar múltiples valores de la lista a la vez usando :.


"""

a:list = [1, 2, 3, 4, 5, 6]
print('La variable a contiene:', a)
a[0:3] = [0, 0, 0]
print('La variable a contiene:', a)

"""Hay ciertos operadores como el + que pueden ser usados sobre las listas.


"""

a:list = [1, 2, 3]
print('La variable a contiene:', a)
a += [4, 5]
print('La variable a contiene:', a)

"""Y una funcionalidad muy interesante es que se puede asignar una lista con n elementos a n variables."""

lista:list = [1, 2, 3]
x, y, z = lista
print(x, y, z)

"""## Iterar listas
En Python es muy fácil iterar una lista, mucho más que en otros lenguajes de programación.
"""

lista:list = [5, 9, 10]
for l in lista:
    print(l, end=', ')

"""Si necesitamos un índice acompañado con la lista, que tome valores desde 0 hasta n-1, se puede hacer de la siguiente manera."""

lista:list = [5, 9, 10]
for index, l in enumerate(lista):
    print(f'El índice {index} contiene el valor {l}')

"""O si tenemos dos listas y las queremos iterar a la vez, también es posible hacerlo.


"""

lista1:list = [5, 9, 10]
lista2:list = ["Jazz", "Rock", "Djent"]
for l1, l2 in zip(lista1, lista2):
    print(f"Valor de la lista1 {l1} - valor de la lista2 {l2}")

"""Y por supuesto, también se pueden iterar las listas usando los índices como hemos visto al principio, y haciendo uso de len(), que nos devuelve la longitud de la lista."""

lista1:list = [5, 9, 10]
for i in range(0, len(lista)):
    print(f'El índice {i} contiene el valor {lista1[i]}')

"""## Métodos listas

### append(obj)
El método append() añade un elemento al final de la lista.
"""

l:list = [1, 2]
print('La variable l contiene:', l)
l.append(3)
print('La variable l contiene:', l)

"""### extend(iterable)
El método extend() permite añadir una lista a la lista inicial.
"""

l:list = [1, 2]
print('La variable l contiene:', l)
l.extend([3, 4])
print('La variable l contiene:', l)

"""### insert(index, obj)
El método insert() añade un elemento en una posición o índice determinado.
"""

l:list = [1, 3]
print('La variable l contiene:', l)
l.insert(1, 2)
print('La variable l contiene:', l)

"""### remove(obj)
El método remove() recibe como argumento un objeto y lo borra de la lista.
"""

l:list = [1, 2, 3]
print('La variable l contiene:', l)
l.remove(3)
print('La variable l contiene:', l)

"""Otra opción es utilizando la función `del`."""

l:list = [1, 2, 3]
print('La variable l contiene:', l)
del l[2]
print('La variable l contiene:', l)

"""### pop(index=-1)
El método pop() elimina por defecto el último elemento de la lista, pero si se pasa como parámetro un índice permite borrar elementos diferentes al último.
"""

l:list = [1, 2, 3]
print('La variable l contiene:', l)
l.pop() # eliminamos el último valor
print('La variable l contiene:', l)

l:list = [1, 2, 3]
print('La variable l contiene:', l)
l.pop(1) # eliminamos el valor del medio
print('La variable l contiene:', l)

"""### reverse()
El método reverse() inverte el órden de la lista.
"""

l:list = [1, 2, 3]
print('La variable l contiene:', l)
l.reverse()
print('La variable l contiene:', l)

"""### sort()
El método sort() ordena los elementos de menos a mayor por defecto.
"""

l:list = [3, 1, 2]
print('La variable l contiene:', l)
l.sort()
print('La variable l contiene:', l)

"""Y también permite ordenar de mayor a menor si se pasa como parámetro reverse=True.


"""

l:list = [3, 1, 2]
print('La variable l contiene:', l)
l.sort(reverse=True)
print('La variable l contiene:', l)

"""### index(obj[,index])
El método index() recibe como parámetro un objeto y devuelve el índice de su primera aparición. Como hemos visto en otras ocasiones, el índice del primer elemento es el 0.
"""

l:list = ["Periphery", "Intervals", "Monuments"]
print('El indice de la palabra Intervals es : ', l.index("Intervals"))

"""También permite introducir un parámetro opcional que representa el índice desde el que comenzar la búsqueda del objeto. Es como si ignorara todo lo que hay antes de ese índice para la búsqueda, en este caso el 4."""

l:list = [1, 1, 1, 1, 2, 1, 4, 5]
# busco el valor 1 luego de la posición4
print(l.index(1, 4))