# -*- coding: utf-8 -*-
"""Semana_03-10_Frozensets.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1busi3ApiidPMmtPhC-nPGZhVpKdGLVTL

## Frozenset

Puedes obtener más ayuda con el comando help.
"""

help(frozenset)

"""## Crear frozenset Python
Los frozensets en Python son un tipo muy parecido a los sets con la salvedad de que son inmutables, es decir, están congelados y no pueden ser modificados una vez inicializados.
"""

fs:frozenset = frozenset([1, 2, 3])
print('La variable fs contiene:', fs)

"""Otra opción es importar `Frozenset` desde el módulo de typing."""

from typing import FrozenSet

fs:FrozenSet = frozenset([1, 2, 3])
print('La variable fs contiene:', fs)

"""## Ejemplos frozenset
Dado que son inmutables, cualquier intento de modificación con los métodos que ya hemos visto en otros capítulos como add() o clear() dará un error, ya que los frozenset no disponen de esos métodos.


"""

import traceback

fs:frozenset = frozenset([1, 2, 3])
try:
  fs.add(4)
except Exception as e:
  traceback.print_exc()

try:
  fs.clear()
except Exception as e:
  traceback.print_exc()

"""Los frozenset pueden ser útiles cuando queremos usar un set pero se requiere que el tipo sea inmutable. Algo no muy común, pero que podría darse, es crear un set de sets. Es decir, un ser que contiene como elementos a otros sets. El siguiente código daría un TypeError ya que los elementos de un set deben ser por definición inmutables."""

s1:set = {1, 2}
s2:set = {3, 4}
try:
  s3 = {s1, s2}
except Exception as e:
  traceback.print_exc()

"""Para resolver este problema, podemos crear un set de frozensets. Esto si es posible ya que el frozenset es un tipo inmutable."""

s1:frozenset = frozenset([1, 2])
s2:frozenset = frozenset([3, 4])
s3:set = {s1, s2}
print('La variable s3 contiene:', s3)

"""Lo mismo aplica a los diccionarios, ya que su key debe ser un tipo inmutable. Si intentamos crear un diccionario con set como key, obtendremos un TypeError."""

s1:set = set([1, 2])
s2:set = set([3, 4])
try:
  d = {s1: "Texto1", s2: "Texto2"}
except Exception as e:
  traceback.print_exc()

"""Pero si podemos crear un diccionario donde sus key son frozenset, ya que son un tipo inmutable.


"""

s1:frozenset = frozenset([1, 2])
s2:frozenset = frozenset([3, 4])
d = {s1: "Texto1", s2: "Texto2"}
print('La variable d contiene:', d)