# -*- coding: utf-8 -*-
"""Semana_03-09_Diccionarios.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eJlV4evY9VctFnLS1PG-Yp1dwQHFmWqr

## dict
Los diccionarios en Python son una estructura de datos que permite almacenar su contenido en forma de llave y valor.

Puedes obtener más ayuda con el comando help.
"""

help(dict)

"""## Crear diccionario Python
Un diccionario en Python es una colección de elementos, donde cada uno tiene una llave `key` y un valor `value` asociado a la key. Los diccionarios se pueden crear con paréntesis `{}` separando con una coma cada par `key: value`. En el siguiente ejemplo tenemos tres keys que son el nombre, la edad y el documento.
"""

d1:dict = {
  "Nombre": "Sara",
  "Edad": 27,
  "Documento": 1003882
}
print('La variable d1 contiene:', d1)

"""Otra opción es importar `Dict` desde el módulo de typing."""

from typing import Dict

d1:Dict = {
  "Nombre": "Sara",
  "Edad": 27,
  "Documento": 1003882
}
print('La variable d1 contiene:', d1)

"""Otra forma equivalente de crear un diccionario en Python es usando `dict()` e introduciendo los pares `key: value` entre paréntesis."""

d2:dict = dict([
      ('Nombre', 'Sara'),
      ('Edad', 27),
      ('Documento', 1003882),
])
print('La variable d2 contiene:', d2)

"""También es posible usar el constructor `dict()` para crear un diccionario.


"""

d3:dict = dict(Nombre='Sara',
          Edad=27,
          Documento=1003882)
print('La variable d3 contiene:', d3)

"""Algunas propiedades de los diccionario en Python son las siguientes:

* Son dinámicos, pueden crecer o decrecer, se pueden añadir o eliminar elementos.
* Son indexados, los elementos del diccionario son accesibles a través del key.
* Y son anidados, un diccionario puede contener a otro diccionario en su campo value.

## Acceder y modificar elementos
Se puede acceder a sus elementos con [] o también con la función get()
"""

print(d1['Nombre'])
print(d1.get('Nombre'))

"""Para modificar un elemento basta con usar [] con el nombre del key y asignar el valor que queremos."""

print('La variable d1 contiene:', d1)
d1['Nombre'] = "Laura"
print('La variable d1 contiene:', d1)

"""Si el key al que accedemos no existe, se añade automáticamente.


"""

print('La variable d1 contiene:', d1)
d1['Direccion'] = "Calle 123"
print('La variable d1 contiene:', d1)

"""## Iterar diccionario
Los diccionarios se pueden iterar de manera muy similar a las listas u otras estructuras de datos. Para imprimir los key.
"""

for x in d1:
    print(x)

"""Se puede imprimir también solo el value.


"""

for x in d1:
    print(f"Clave: {x} - valor: {d1[x]}")

"""O si queremos imprimir el key y el value a la vez.


"""

for key, value in d1.items():
    print(key, value)

"""## Diccionarios anidados
Los diccionarios en Python pueden contener uno dentro de otro. Podemos ver como los valores anidado uno y dos del diccionario d contienen a su vez otro diccionario.
"""

anidado1:dict = {"a": 1, "b": 2}
anidado2:dict = {"a": 1, "b": 2}
d:dict = {
  "anidado1" : anidado1,
  "anidado2" : anidado2
}
print('La variable d contiene:', d)

"""## Métodos diccionarios Python

### clear()
El método clear() elimina todo el contenido del diccionario.
"""

d:dict = {'a': 1, 'b': 2}
print('La variable d contiene:', d)
d.clear()
print('La variable d contiene:', d)

"""### get(key[,default])
El método get() nos permite consultar el value para un key determinado. El segundo parámetro es opcional, y en el caso de proporcionarlo es el valor a devolver si no se encuentra la key.
"""

d:dict = {'a': 1, 'b': 2}
print(d.get('a'))
print(d.get('z', 'No encontrado'))

"""### items()
El método items() devuelve una lista con los keys y values del diccionario. Si se convierte en list se puede indexar como si de una lista normal se tratase, siendo los primeros elementos las key y los segundos los value.
"""

d:dict = {'a': 1, 'b': 2}
it = d.items()
print(it)
print(list(it))
print(list(it)[0][0])

"""### keys()
El método keys() devuelve una lista con todas las keys del diccionario.
"""

d:dict = {'a': 1, 'b': 2}
k = d.keys()
print(k)
print(list(k))

"""### values()
El método values() devuelve una lista con todos los values o valores del diccionario.
"""

d:dict = {'a': 1, 'b': 2}
print(list(d.values()))

"""### pop(key[,default])
El método pop() busca y elimina la key que se pasa como parámetro y devuelve su valor asociado. Daría un error si se intenta eliminar una key que no existe.
"""

d:dict = {'a': 1, 'b': 2}
print('La variable d contiene:', d)
valor_a:int = d.pop('a')
print('La variable d contiene:', d)
print('El valor extraido es: ', valor_a)

"""También se puede pasar un segundo parámetro que es el valor a devolver si la key no se ha encontrado. En este caso si no se encuentra no habría error."""

d:dict = {'a': 1, 'b': 2}
print('La variable d contiene:', d)
valor_c: int = d.pop('c', -1)
print('La variable d contiene:', d)
print('El valor extraido es: ', valor_c)

"""### popitem()
El método popitem() elimina el último elemento del diccionario.
"""

d:dict = {'a': 1, 'b': 2}
print('La variable d contiene:', d)
d.popitem()
print('La variable d contiene:', d)

"""### update(obj)
El método update() se llama sobre un diccionario y tiene como entrada otro diccionario. Los value son actualizados y si alguna key del nuevo diccionario no esta, es añadida.
"""

d1:dict = {'a': 1, 'b': 2}
d2:dict = {'a': 0, 'd': 400}
print('La variable d contiene:', d1)
d1.update(d2)
print('La variable d contiene:', d1)