# -*- coding: utf-8 -*-
"""Semana_03-11_Casting.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wiloas2nvsFmzj1NH3ROR0iG0P9iQOMP

## Cast en Python

Hacer un cast o casting significa convertir un tipo de dato a otro. Anteriormente hemos visto tipos como los int, str o float. Pues bien, es posible convertir de un tipo a otro.

Pero antes de nada, veamos los diferentes tipos de cast o conversión de tipos que se pueden hacer.

Existen dos:

* Conversión implícita: Es realizada automáticamente por Python. Sucede cuando realizamos ciertas operaciones con dos tipos distintos.

* Conversión explícita: Es realizada expresamente por nosotros, como por ejemplo convertir de str a int con str().

## Conversión implícita
Esta conversión de tipos es realizada automáticamente por Python, prácticamente sin que nos demos cuenta. Aún así, es importante saber lo que pasa por debajo para evitar problemas futuros.

El ejemplo más sencillo donde podemos ver este comportamiento es el siguiente:
* a es un int
* b es un float

Pero si sumamos a + b y almacenamos el resultado en a, podemos ver como internamente Python ha convertido el int en float para poder realizar la operación, y la variable resultante es float
"""

a:int = 1
b:float = 2.3
print('El tipo de la variable a antes de sumar es: ', type(a))

print(f'El resultado de sumar {a}+{b} es: ', end='', sep='' )
a:float = a + b
print(a)
print('El tipo de la variable a después de sumar es: ', type(a))

"""Sin embargo hay otros casos donde Python no es tan listo y no es capaz de realizar la conversión. Si intentamos sumar un int a un string, tendremos un error TypeError."""

import traceback

a:int = 1
b:str = "2.3"
try:
  c = a + b
except Exception:
  traceback.print_exc()

"""Si te das cuenta, es lógico que esto sea así, ya que en este caso b era "2.3", pero ¿y si fuera "Hola"? ¿Cómo se podría sumar eso? No tiene sentido.

## Conversión explicita
Por otro lado, podemos hacer conversiones entre tipos o cast de manera explícita haciendo uso de diferentes funciones que nos proporciona Python. Las más usadas son las siguientes:

* float(), str(), int(), list(), set()
* Y algunas otras como hex(), oct() y bin()

### Convertir float a int
Para convertir de float a int debemos usar float(). Pero mucho cuidado, ya que el tipo entero no puede almacena decimales, por lo que perderemos lo que haya después de la coma.
"""

a:float = 3.5
print('El valor de la variable a es: ', a)
a:int = int(a)
print('El valor de la variable a luego del casting es: ', a)
print('El tipo de la variable a es: ', type(a))

"""### Convertir float a string
Podemos convertir un float a string con str(). Podemos ver en el siguiente código como cambia el tipo de a después de hacer el cast.
"""

a:float = 3.5
print('El valor de la variable a es: ', a)
print('El tipo de la variable a es: ', type(a))
a:str = str(a)
print('El valor de la variable a es: ', a)
print('El tipo de la variable a luego de realizar el casting es: ', type(a))

"""### Convertir string a float
Podemos convertir un string a float usando float(). Es importante notar que se usa el . como separador.
"""

a:str = "35.5"
print(float(a))

"""El siguiente código daría un error, dado que , no se reconoce por defecto como separador decimal.


"""

a:str = "35,5"
try:
  print(float(a))
except Exception:
  traceback.print_exc()

"""Y por último, resulta obvio pensar que el siguiente código dará un error también.


"""

a:str = "Python"
try:
  a:float = float(a)
except Exception:
  traceback.print_exc()

"""### Convertir string a int
Al igual que la conversión a float del caso anterior, podemos convertir de string a int usando int().
"""

a:str = "3"
print('El valor de la variable a es: ', a)
print('El tipo de la variable a es: ', type(a))
a:int = int(a)
print('El valor de la variable a es: ', a)
print('El tipo de la variable a luego de realizar el casting es: ', type(a))

"""Cuidado ya que no es posible convertir a int cualquier valor.


"""

a:str = "Python"
try:
  a:int = int(a)
except Exception:
  traceback.print_exc()

"""### Convertir int a string
La conversión de int a string se puede realizar con str().

A diferencia de otras conversiones, esta puede hacerse siempre, ya que cualquier valor entero que se nos ocurra poner en a, podrá ser convertido a string.
"""

a:int = 10
print('El valor de la variable a es: ', a)
print('El tipo de la variable a es: ', type(a))
a:str = str(a)
print('El valor de la variable a es: ', a)
print('El tipo de la variable a luego de realizar el casting es: ', type(a))

"""### Convertir a list
Es también posible hacer un cast a lista, desde por ejemplo un set. Para ello podemos usar list().
"""

a:set = {1, 2, 3}
b:list = list(a)

print('El valor de la variable a es: ', a)
print('El tipo de la variable a es: ', type(a))
print('El valor de la variable b es: ', b)
print('El tipo de la variable b es: ', type(b))

"""### Convertir a set
Y de manera completamente análoga, podemos convertir de lista a set haciendo uso de set().
"""

a:list = ["Python", "Mola"]
b:set = set(a)

print('El valor de la variable a es: ', a)
print('El tipo de la variable a es: ', type(a))
print('El valor de la variable b es: ', b)
print('El tipo de la variable b es: ', type(b))

"""Esperamos que esto haya servido para aclarar el concepto de casts o conversiones de tipos en Python. Es muy importante tener bien claro el tipo de datos con el que estamos trabajando en cada momento, ya que Python es un lenguaje con tipado dinámico, algo que puede ser una gran ventaja, pero también causa de muchos quebraderos de cabeza.

Y recuerda, la función type() es tu amiga.

Si quieres saber más, tal vez te interese el concepto de duck typing.
"""