# -*- coding: utf-8 -*-
"""Semana_03-08_Tuplas.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EIQRyPd64IlzT8IfwH_Ve9hFGnyzOhRF

## tuple

Las tuplas en Python son un tipo o estructura de datos que permite almacenar datos de una manera muy parecida a las listas, con la salvedad de que son inmutables. No se pueden modificar.

Puedes obtener más ayuda con el comando help.
"""

help(tuple)

"""## Crear tupla Python
Las tuplas en Python o tuples son muy similares a las listas, pero con dos diferencias. Son inmutables, lo que significa que no pueden ser modificadas una vez declaradas, y en vez de inicializarse con corchetes se hace con `()`. Dependiendo de lo que queramos hacer, las tuplas pueden ser más rápidas.
"""

tupla:tuple = (1, 2, 3)
print('La variable tupla contiene:', tupla)

"""Otra opción es importar `Tuple` desde el módulo de typing."""

from typing import Tuple

tupla:Tuple = (1, 2, 3)
print('La variable tupla contiene:', tupla)

"""También pueden declararse sin `()`, separando por `,` todos sus elementos.


"""

tupla:tuple = 1, 2, 3
print('La variable tupla contiene:', tupla)

"""## Operaciones con tuplas
Como hemos comentado, las tuplas son tipos inmutables, lo que significa que una vez asignado su valor, no puede ser modificado. Si se intenta, tendremos un TypeError.
"""

import traceback

tupla:tuple = (1, 2, 3)
try:
  tupla[0] = 5
except Exception:
  traceback.print_exc()

"""Al igual que las listas, las tuplas también pueden ser anidadas.


"""

tupla:tuple = 1, 2, ('a', 'b'), 3
print('La variable tupla contiene:', tupla)
print('La variable tupla en el índice 2 contiene:', tupla[2])
print('La variable tupla en el índice 2 sub índice 0 contiene:', tupla[2][0])

"""## Función tupel
También es posible convertir un str a tuple usando la función tuple(). La función recibe como parámetro un objeto iterable.
"""

tupla:tuple = tuple("123")
print('La variable tupla contiene:', tupla)

"""Y también es posible convertir una lista en tupla haciendo uso de al función tuple().


"""

lista:list = [1, 2, 3]
tupla:tuple = tuple(lista)
print('La variable tupla contiene:', tupla)

"""Se puede iterar una tupla de la misma forma que se hacía con las listas.


"""

tupla:tuple = [1, 2, 3]
for t in tupla:
    print(t, end=', ')

"""Y se puede también asignar el valor de una tupla con n elementos a n variables.


"""

l:tuple = (1, 2, 3)
x, y, z = l
print(f'x={x} - y={y} -z={z}')

"""Aunque tal vez no tenga mucho sentido a nivel práctico, es posible crear una tupla de un solo elemento. Para ello debes usar , antes del paréntesis, porque de lo contrario (2) sería interpretado como int."""

tupla:tuple = (2,)
print('La variable tupla contiene:', tupla)

"""## Métodos tuplas

### count(obj)
El método count() cuenta el número de veces que el objeto pasado como parámetro se ha encontrado en la lista.
"""

l:tuple = (1, 1, 1, 3, 5)
print(l.count(1))

"""### index(obj[,index])
El método index() busca el objeto que se le pasa como parámetro y devuelve el índice en el que se ha encontrado.
"""

l:tuple = (7, 7, 7, 3, 5)
print(l.index(5))

"""En el caso de no encontrarse, se devuelve un ValueError.


"""

l:tuple = (7, 7, 7, 3, 5)
try:
  print(l.index(35))
except Exception:
  traceback.print_exc()

"""El método index() también acepta un segundo parámetro opcional, que indica a partir de que índice empezar a buscar el objeto."""

l:tuple = (7, 7, 7, 3, 5)
print(l.index(7, 2))