# -*- coding: utf-8 -*-
"""Semana_06-03_Herencia.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Fe3KQNyN4WNh5uDLActH9WFT-xLJD8p7

## Herencia en Python
Para comprender la herencia, es fundamental comprender la programación orientada a objetos, por lo que te recomendamos empezar por ahí antes.

La herencia es un proceso mediante el cual se puede crear una `clase hija` que `hereda` de una `clase padre`, compartiendo sus métodos y atributos. Además de ello, una `clase hija` puede sobreescribir los métodos o atributos, o incluso definir unos nuevos.

Se puede crear una `clase hija` con tan solo pasar como parámetro la clase de la que queremos heredar. En el siguiente ejemplo vemos como se puede usar la herencia en Python, con la `clase Perro` que hereda de la `clase Animal`. Así de fácil.
"""

# Definimos una clase padre
class Animal:
    pass

# Creamos una clase hija que hereda de la padre
class Perro(Animal):
    pass

"""De hecho podemos ver como efectivamente la `clase Perro` es la hija de la `clase Animal` usando la propiedad `__bases__`.


"""

print('La clase Perro tiene como padres a las clases:', Perro.__bases__)

"""De manera similar podemos ver que clases descienden de una en concreto con el método `__subclasses__()`."""

print('La clase Animal tiene como hijos a las clases:', Animal.__subclasses__())

"""¿Y para que queremos la herencia?

Dado que una clase hija hereda los atributos y métodos de la padre, nos puede ser muy útil cuando tengamos clases que se parecen entre sí pero tienen ciertas particularidades. En este caso en vez de definir un montón de clases para cada animal, podemos tomar los elementos comunes y crear una clase Animal de la que hereden el resto, respetando por tanto la filosofía DRY (Don’t Repeat Yourself). Realizar estas abstracciones y buscar el denominador común para definir una clase de la que hereden las demás, es una tarea de lo más compleja en el mundo de la programación.

Para saber más: El principio DRY es muy aplicado en el mundo de la programación y consiste en no repetir código de manera innecesaria. Cuanto más código duplicado exista, más difícil será de modificar y más fácil será crear inconsistencias.

## Extendiendo y modificando métodos
Continuemos con nuestro ejemplo de perros y animales. Vamos a definir una clase padre Animal que tendrá todos los atributos y métodos genéricos que los animales pueden tener. Esta tarea de buscar el denominador común es muy importante en programación.

Veamos los atributos:

* Tenemos la `especie` ya que todos los animales pertenecen a una.
* Y la `edad`, ya que todo ser vivo nace, crece, se reproduce y muere.

Y los métodos o funcionalidades:

* Tendremos el método `hablar`, que cada animal implementará de una forma. Los perros ladran, las abejas zumban y los caballos relinchan.
* Un método `moverse`. Unos animales lo harán caminando, otros volando.
* Y por último un método `descríbeme` que será común.

Definimos la clase padre, con una serie de atributos comunes para todos los animales como hemos indicado.
"""

class Animal:
    def __init__(self, especie:str, edad:int):
        """ Constructor de la clase Animal

        Args:
          especie (str): Especie del animal
          edad (int): Edad del animal
        """
        print(f'Se construye la clase {type(self).__name__} con la especie {especie} y la edad {edad}')
        self.especie:str = especie
        self.edad:int = edad

    # Método genérico pero con implementación particular
    def hablar(self):
        """ Me indica como habla el animal. Implementar en cada animal. """
        pass

    # Método genérico pero con implementación particular
    def moverse(self):
        """ Me indica como se mueve el animal. Implementar en cada animal. """
        pass

    # Método genérico con la misma implementación
    def describeme(self):
        """ Imprime por pantalla el tipo de animal. """
        print("Soy un Animal del tipo", type(self).__name__, "\n")

"""Tenemos ya por lo tanto una clase genérica Animal, que generaliza las características y funcionalidades que todo animal puede tener. Ahora creamos una clase Perro que hereda del Animal. Como primer ejemplo vamos a crear una clase vacía, para ver como los métodos y atributos son heredados por defecto."""

# Perro hereda de Animal
class Perro(Animal):
    pass

mi_perro = Perro(especie='mamífero', edad=10)
mi_perro.describeme()
# Soy un Animal del tipo Perro

"""Con tan solo un par de líneas de código, hemos creado una clase nueva que tiene todo el contenido que la clase padre tiene, pero aquí viene lo que es de verdad interesante. Vamos a crear varios animales concretos y sobreescrbir algunos de los métodos que habían sido definidos en la clase Animal, como el hablar o el moverse, ya que cada animal se comporta de una manera distinta.

Podemos incluso crear nuevos métodos que se añadirán a los ya heredados, como en el caso de la Abeja con picar().
"""

class Perro(Animal):
    def hablar(self):
        """ Implementación del método hablar del perro. """
        print("Guau!\n")

    def moverse(self):
        """ Implementación del método moverse del perro. """
        print("Caminando con 4 patas\n")

class Vaca(Animal):
    def hablar(self):
        """ Implementación del método hablar del vaca. """
        print("Muuu!\n")

    def moverse(self):
        """ Implementación del método moverse de la vaca. """
        print("Caminando con 4 patas\n")

class Abeja(Animal):
    def hablar(self):
        """ Implementación del método hablar del abeja. """
        print("Bzzzz!\n")

    def moverse(self):
        """ Implementación del método moverse de la abeja. """
        print("Volando\n")

    # Nuevo método
    def picar(self):
        """ Creación de un método particular de la abeja. """
        print("Picar!\n")

"""Por lo tanto ya podemos crear nuestros objetos de esos animales y hacer uso de sus métodos que podrían clasificarse en tres:

* Heredados directamente de la clase padre: describeme()
* Heredados de la clase padre pero modificados: hablar() y moverse()
* Creados en la clase hija por lo tanto no existentes en la clase padre: picar()
"""

mi_abeja = Abeja(especie='insecto', edad=1)
print()

print('Invoco al método hablar de la variable mi_abeja:')
mi_abeja.hablar()
print('Invoco al método moverse de la variable mi_abeja:')
mi_abeja.moverse()
print('Invoco al método describeme de la variable mi_abeja:')
mi_abeja.describeme()
print('Invoco al método picar de la variable mi_abeja:')
mi_abeja.picar()

import traceback

mi_perro = Perro(especie='mamífero', edad=10)

print('Invoco al método hablar de la variable mi_perro:')
mi_perro.hablar()
print('Invoco al método moverse de la variable mi_perro:')
mi_perro.moverse()
print('Invoco al método describeme de la variable mi_perro:')
mi_perro.describeme()
print('Invoco al método picar de la variable mi_perro:')
try:
    mi_perro.picar()
except AttributeError:
    traceback.print_exc()

"""Nótese que al intentar llamar al método `picar` en la instancia de `mi_perro`, nos muestra un error porque no está definido. Lo mismo va a ocurrir con la clase `Vaca`."""

mi_vaca = Vaca(especie='mamífero', edad=23)

print('Invoco al método hablar de la variable mi_vaca:')
mi_vaca.hablar()
print('Invoco al método moverse de la variable mi_vaca:')
mi_vaca.moverse()
print('Invoco al método describeme de la variable mi_vaca:')
mi_vaca.describeme()
print('Invoco al método picar de la variable mi_vaca:')
try:
    mi_perro.picar()
except AttributeError:
    traceback.print_exc()

"""## Uso de super()
En pocas palabras, la función `super()` nos permite acceder a los métodos de la clase padre desde una de sus hijas. Volvamos al ejemplo de Animal y Perro.
"""

class Animal:
    def __init__(self, especie:str, edad:int):
        """ Constructor de la clase Animal

        Args:
          especie (str): Especie del animal
          edad (int): Edad del animal
        """
        print(f'Se construye la clase Animal con la especie {especie} y la edad {edad}')
        self.especie:str = especie
        self.edad:int = edad

    # Método genérico pero con implementación particular
    def hablar(self):
        """ Me indica como habla el animal. Implementar en cada animal. """
        pass

    # Método genérico pero con implementación particular
    def moverse(self):
        """ Me indica como se mueve el animal. Implementar en cada animal. """
        pass

    # Método genérico con la misma implementación
    def describeme(self):
        """ Imprime por pantalla el tipo de animal. """
        print("Soy un Animal del tipo", type(self).__name__, "\n")

"""Tal vez queramos que nuestra clase `Perro` tenga un parámetro extra en el constructor, como podría ser el `dueño`. Para realizar esto tenemos dos alternativas:

* Podemos crear un nuevo `__init__` y guardar todas las variables una a una.
* O podemos usar la función `super()` para llamar al método `__init__` de la clase padre que ya aceptaba la especie y edad, y sólo asignar la variable nueva manualmente.
"""

class Perro(Animal):
    # opción crear un nuevo constructor para la clase Perro
    def __init__(self, especie:str, edad:int, duenio:str):
        """ Constructor de la clase Perro

        Args:
          especie (str): Especie del animal
          edad (int): Edad del animal
          duenio (str): Dueño del animal
        """
        print(f'Se construye la clase Perro con la especie {especie}, con la edad {edad} y el dueño {duenio}')
        self.especie:str = especie
        self.edad:int = edad
        self.duenio:str = duenio

    def hablar(self):
        """ Implementación del método hablar del perro. """
        print("Guau!\n")

    def moverse(self):
        """ Implementación del método moverse del perro. """
        print("Caminando con 4 patas\n")

mi_perro = Perro(especie='mamífero', edad=7, duenio='Luis')
print('Tiene la especie', mi_perro.especie)
print('Tiene una edad de', mi_perro.edad)
print('El dueño es', mi_perro.duenio)

class Perro(Animal):
    # opción donde se utiliza la llamada a la función super()
    def __init__(self, especie:str, edad:int, duenio:int):
        """ Constructor de la clase Perro

        Args:
          especie (str): Especie del animal
          edad (int): Edad del animal
        """
        print(f'Se construye la clase Perro con la especie {especie}, con la edad {edad} y el dueño {duenio}')
        super().__init__(especie=especie, edad=edad)
        self.duenio = duenio

    def hablar(self):
        """ Implementación del método hablar del perro. """
        print("Guau!\n")

    def moverse(self):
        """ Implementación del método moverse del perro. """
        print("Caminando con 4 patas\n")

mi_perro = Perro(especie='mamífero', edad=7, duenio='Luis')
print('Tiene la especie', mi_perro.especie)
print('Tiene una edad de', mi_perro.edad)
print('El dueño es', mi_perro.duenio)

"""Notar como en está segunda opción aparece una leyenda que se imprime cuando se inicializa la clase Animal.

## Herencia múltiple
En Python es posible realizar herencia múltiple. Anteriormente hemos visto como se podía crear una clase padre que heredaba de una clase hija, pudiendo hacer uso de sus métodos y atributos. La herencia múltiple es similar, pero una clase hereda de varias clases padre en vez de una sola.

Veamos un ejemplo. Por un lado tenemos dos clases Clase1 y Clase2, y por otro tenemos la Clase3 que hereda de las dos anteriores. Por lo tanto, heredará todos los métodos y atributos de ambas.
"""

class Clase1:
    pass
class Clase2:
    pass
class Clase3(Clase1, Clase2):
    pass

"""Es posible también que una clase herede de otra clase y a su vez otra clase herede de la anterior."""

class Clase1:
    pass
class Clase2(Clase1):
    pass
class Clase3(Clase2):
    pass

"""Llegados a este punto nos podemos plantear lo siguiente. Hemos visto las clases hijas heredan los métodos de las clases padre, pero también pueden reimplementarlos de manera distinta. Entonces, si llamo a un método que todas las clases tienen en común ¿a cuál se llama?. Pues bien, existe una forma de saberlo.

La forma de saber a que método se llama es consultar el MRO o Method Order Resolution. Esta función nos devuelve una tupla con el orden de búsqueda de los métodos. Como era de esperar se empieza en la propia clase y se va subiendo hasta la clase padre, de izquierda a derecha.
"""

class Clase1:
    pass
class Clase2:
    pass
class Clase3(Clase1, Clase2):
    pass

print('El orden en que se busca el método a ejecutar es:', Clase3.__mro__)

"""Una curiosidad es que al final del todo vemos la clase object. Aunque pueda parecer raro, es correcto ya que en realidad todas las clases en Python heredan de una clase genérica object, aunque no lo especifiquemos explícitamente.

Y como último ejemplo,el cielo es el límite. Podemos tener una clase heredando de otras tres. Fíjate en que el MRO depende del orden en el que las clases son pasadas: 1, 3, 2.
"""

class Clase1:
    pass
class Clase2:
    pass
class Clase3:
    pass
class Clase4(Clase3, Clase1, Clase2):
    pass
print('El orden en que se busca el método a ejecutar es:', Clase4.__mro__)

"""Junto con la herencia, la cohesión, abstracción, polimorfismo, acoplamiento y encapsulamiento son otros de los conceptos claves para entender la programación orientada a objetos."""