# -*- coding: utf-8 -*-
"""Semana_06-05_Encapsulamiento.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1giVhEI7EzCM9SxxGfa7zezHoqUe1kXTP

## Encapsulamiento en programación

El encapsulamiento o encapsulación en programación es un concepto relacionado con la programación orientada a objetos, y hace referencia al ocultamiento de los estado internos de una clase al exterior. Dicho de otra manera, encapsular consiste en hacer que los atributos o métodos internos a una clase no se puedan acceder ni modificar desde fuera, sino que tan solo el propio objeto pueda acceder a ellos.

Para la gente que conozca Java, le resultará un termino muy familiar, pero en Python es algo distinto. Digamos que Python por defecto no oculta los atributos y métodos de una clase al exterior. Veamos un ejemplo con el lenguaje Python.
"""

class Clase:
    atributo_clase = "Hola"

    def __init__(self, atributo_instancia):
        """ Constructor de la clase Animal

        Args:
          atributo_instancia: Atributo instancia
        """
        self.atributo_instancia = atributo_instancia

mi_clase = Clase("Que tal")
print('El atributo de clase tiene el valor:', mi_clase.atributo_clase)
print('El atributo de instancia tiene el valor:', mi_clase.atributo_instancia)

"""Ambos atributos son perfectamente accesibles desde el exterior. Sin embargo esto es algo que tal vez no queramos. Hay ciertos métodos o atributos que queremos que pertenezcan sólo a la clase o al objeto, y que sólo puedan ser accedidos por ellos mismos. Para ello podemos usar la doble `__` para nombrar a un atributo o método. Esto hará que Python los interprete como `privados`, de manera que no podrán ser accedidos desde el exterior."""

import traceback

class Clase:
    atributo_clase = "Hola"   # Accesible desde el exterior
    __atributo_clase_privado = "Hola" # No accesible

    # No accesible desde el exterior
    def __mi_metodo_privado(self):
        print("Dentro del método privado")
        self.__variable = 0

    # Accesible desde el exterior
    def metodo_normal(self):
        print("Dentro del método normal", end=' - ')
        # El método si es accesible desde el interior
        self.__mi_metodo_privado()

mi_clase = Clase()
print('El atributo de clase tiene el valor:', mi_clase.atributo_clase)
print('Al ejecutar el metodo_normal obtengo:')
mi_clase.metodo_normal()

"""Ahora vamos a intentar acceder al atributo y método privado."""

try:
  mi_clase.__mi_metodo_privado()  # Error!
except AttributeError:
  print("El método es privado")
  traceback.print_exc()

try:
  mi_clase.__atributo_clase_privado  # Error!
except AttributeError:
  print("El atributo es privado")
  traceback.print_exc()

"""Y como curiosidad, podemos hacer uso de `dir` para ver el listado de métodos y atributos de nuestra clase. Podemos ver claramente como tenemos el `metodo_normal` y el `atributo de clase`, pero no podemos encontrar `__mi_metodo_privado` ni `__atributo_clase_privado`."""

from typing import List
from math import ceil

propiedades_y_metodo_accesible:List[str] = dir(mi_clase)
largo_salto:int = 5
cantidad_saltos:int = ceil(len(propiedades_y_metodo_accesible)/largo_salto)
for i in range(cantidad_saltos):
  print(propiedades_y_metodo_accesible[i*largo_salto:i*largo_salto+largo_salto])

"""Pues bien, en realidad si que podríamos acceder a `__atributo_clase` y a `__mi_metodo` haciendo un poco de trampa. Aunque no se vea a simple vista, si que están pero con un nombre distinto, para de alguna manera ocultarlos y evitar su uso. Pero podemos llamarlos de la siguiente manera, pero por lo general no es una buena idea."""

print('El atributo de clase privado tiene el valor:', mi_clase._Clase__atributo_clase_privado)
print('Al ejecutar el metodo_privado obtengo:')
mi_clase._Clase__mi_metodo_privado()