# -*- coding: utf-8 -*-
"""Semana_06-Practica_06_resuelta.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rHOJR1VCsMIJo7RMAz8MA7eiYKsnkKYh

# Básicas

## Ejercicio 1
Crear una clase Persona con los atributos nombre, edad y dni. Implementar un método \_\_init\_\_ para inicializar los atributos y un método mostrar_datos para imprimir la información de la persona.
"""



#@title Solución

class Persona:
  """ Clase Persona """

  def __init__(self, nombre:str, edad:int, dni:int):
    """ Constructor

    Args:
      nombre (str): Nombre de la persona.
      edad (int): Edad de la persona.
      dni (int): Dni de la persona.
    """
    self.nombre:str = nombre
    self.edad:int = edad
    self.dni:int = dni

  def mostrar_datos(self):
    """ Muestra los datos por pantalla
    """
    print(f'La persona de nombre {self.nombre} tiene la edad de {self.edad} año/s y su dni es {self.dni}')

persona = Persona(nombre='SAI', edad=1, dni=182)
persona.mostrar_datos()

"""## Ejercicio 2
Crear una clase Coche con los atributos marca, modelo y matricula. Implementar un método \_\_init\_\_ para inicializar los atributos y un método conducir que imprima un mensaje.
"""



#@title Solución

class Coche:
  """ Clase Coche """

  def __init__(self, modelo:str, marca:str, matricula:str):
    """ Constructor

    Args:
      modelo (str): Modelo del coche.
      marca (str): Marca del coche.
      matricula (str): Matrícula del coche.
    """
    self.modelo:str = modelo
    self.marca:str = marca
    self.matricula:str = matricula

  def conducir(self):
    """ Muestra los datos por pantalla
    """
    print(f'El coche de matrícula {self.matricula} es de marca {self.marca} y modelo {self.modelo}')

coche = Coche(modelo='Ranger Raptor',marca='Ford', matricula='XX---XX')
coche.conducir()

"""## Ejercicio 3
Crear una clase Punto con los atributos x e y. Implementar un método \_\_init\_\_ para inicializar los atributos y un método distancia que calcule la distancia a otro punto.
"""



#@title Solución

from __future__ import annotations

class Punto:
  """ Clase Punto """

  def __init__(self, x:float, y:float):
    """ Constructor

    Args:
      x (float): Coordenada X.
      y (float): Coordenada Y.
    """
    self.x:float = x
    self.y:float = y

  def __str__(self):
    return f'({self.x},{self.y})'

  # para usar la anotación de Punto utilizo el 'from __future__ import annotations'
  # el cual ignora que la clase Punto todavía no esta definida por completo
  ## OJO!: EL future annotatios TAMBIÉN SE UTILIZA PARA LA MALA PRÁCTICA DE
  ## ALGUNOS PROGRAMADORES DE ANIDAR MODULOS DE FORMA RECURSICA.
  def distancia(self, punto:Punto):
    """ Calcula la distancia.

    Args:
      punto (Punto): Segundo punto para calcular la distancia.
    """
    distancia:float=pow((punto.x**2-self.x**2) + (punto.y**2-self.y**2), .5)
    print(f'La distancia entre {self} y {punto} es: {distancia:.2f}')

  # aqui la anotación de punto utilizo comilla simple para que no tire un
  # error porque clase Punto todavía no esta definida por completo
  def distancia_2(self, punto:'Punto'):
    """ Calcula la distancia.

    Args:
      punto (Punto): Segundo punto para calcular la distancia.
    """
    distancia:float=pow((punto.x**2-self.x**2) + (punto.y**2-self.y**2), .5)
    print(f'La distancia 2 entre {self} y {punto} es: {distancia:.2f}')

punto_1 = Punto(1,2)
punto_2 = Punto(2,2)

punto_1.distancia(punto=punto_2)
punto_1.distancia_2(punto=punto_2)

"""# Herencia

## Ejercicio 4
Crear una clase Vehiculo con los atributos nombre y potencia. Implementar un método \_\_init\_\_ para inicializar los atributos y un método cantidad\_ruedas que imprima un mensaje genérico.
"""



#@title Solución

class Vehiculo:
  """ Clase Vehiculo """

  def __init__(self, nombre:str, potencia:float):
    """ Constructor

    Args:
      nombre (str): Nombre del vehículo.
      potencia (float): Potencia del motor.
    """
    self.nombre:str = nombre
    self.potencia:float = potencia

  def cantidad_ruedas(self):
    """ Imprime la cantidad de ruedas.
    """
    print('El vehículo debe implementar esta función.')

vehiculo = Vehiculo(nombre='Genérico', potencia=0)
vehiculo.cantidad_ruedas()

"""## Ejercicio 5
Crear una clase Auto que herede de Vehiculo e implemente un método cantidad\_ruedas hablar que imprima un 4.
"""



#@title Solución

class Auto(Vehiculo):
  """ Clase Auto """

  def cantidad_ruedas(self):
    """ Imprime la cantidad de ruedas.
    """
    print(f'El Auto {self.nombre} tiene una potencia de {self.potencia} cv y posee 4 ruedas.')

vehiculo = Vehiculo(nombre='Genérico', potencia=0)
vehiculo.cantidad_ruedas()

utopia = Auto(nombre='Utopia -Paggani', potencia=900)
utopia.cantidad_ruedas()

"""## Ejercicio 6
Crear una clase Moto que herede de Vehiculo e implemente un método cantidad\ruedas que imprima un 2.
"""



#@title Solución

class Moto(Vehiculo):
  """ Clase Moto """

  def cantidad_ruedas(self):
    """ Imprime la cantidad de ruedas.
    """
    print(f'La Moto {self.nombre} tiene una potencia de {self.potencia} cv y posee 2 ruedas.')

vehiculo = Vehiculo(nombre='Genérico', potencia=0)
vehiculo.cantidad_ruedas()

utopia = Auto(nombre='Utopia - Paggani', potencia=900)
utopia.cantidad_ruedas()

ninja_h2r = Moto(nombre='Ninja H2R - Kawasaki', potencia=326)
ninja_h2r.cantidad_ruedas()

"""# Polimorfismo

## Ejercicio 7
Crear una clase Figura con un método abstracto calcular_area.
"""



#@title Solución

from abc import ABC, abstractmethod

class Figura(ABC):
    """ Clase abstracta Figura.
    """

    @abstractmethod
    def calcular_area(self) -> float:
        """ Calcula el área

        Returns:
            float: Returna el área.
        """
        pass

"""## Ejercicio 8
Crear una clase Cuadrado que herede de Figura e implemente el método calcular_area para calcular el área de un cuadrado.
"""



#@title Solución

class Cuadrado(Figura):
    """ Clase Cuadrado.
    """

    def __init__(self, lado:float):
        """ Constructor

        Args:
          lado (float): Medida del lado.
        """
        self.lado:float = lado

    def calcular_area(self) -> float:
        """ Calcula el área

        Returns:
            float: Returna el área.
        """
        return self.lado ** 2

cuadrado = Cuadrado(lado=3)
print(f'El área de un cuadado de lado igual a {cuadrado.lado} es : {cuadrado.calcular_area()}')

"""## Ejercicio 9
Crear una clase Triangulo que herede de Figura e implemente el método calcular_area para calcular el área de un triángulo.
"""



#@title Solución

class Triangulo(Figura):
    def __init__(self, base:float, altura:float):
        """ Constructor

        Args:
          base (float): Medida de la base.
          altura (float): Medida de la altura.
        """
        self.base:float = base
        self.altura:float = altura

    def calcular_area(self) -> float:
        """ Calcula el área

        Returns:
            float: Returna el área.
        """
        return (self.base * self.altura) / 2


triangulo = Triangulo(base=3, altura=8)
print(f'El área de un triánguloa de base igual a {triangulo.base} y de altura igual a {triangulo.altura} es : {triangulo.calcular_area()}')

"""## Ejercicio 10
Escribir un programa que cree una lista de figuras y calcule el área total de la lista.
"""



#@title Solución

def calcular_area_total(figuras:list[Figura]) -> float:
    """ Cacula el área total de las figuras

    Args:
        figuras (list[Figuras]): Lista de figuras.

    Returns:
        float: Retorna la suma de las áreas de cada figura.
    """
    return sum(map(lambda f: f.calcular_area(), figuras))

# Crear una lista de figuras
figuras = [Cuadrado(4), Triangulo(3, 5), Cuadrado(2), Triangulo(4, 6)]

# Calcular el área total de la lista de figuras
area_total = calcular_area_total(figuras)
print("El área total de la lista de figuras es:", area_total)

"""# Encpsulamiento

## Ejercicio 11
Crear una clase CuentaBancaria con los atributos nombre, saldo y dni. Implementar métodos para depositar y retirar dinero, y para obtener el saldo actual.
"""



#@title Solución

class CuentaBancaria:
    """ Clase CuentaBancaria
    """
    def __init__(self, nombre:str, saldo:float, dni:int):
        """ Constructor

        Args:
            nombre (str): Nombre de la cuenta.
            saldo (float): Saldo de la cuenta.
            dni (int): Dni de la persona.
        """
        self.__nombre:str = nombre
        self.__saldo:float = saldo
        self.__dni:int = dni

    def depositar(self, cantidad:float):
        """ Agrega dinero a la cuenta bancaria.

        Args:
            cantida (float): Cantidad de dinero a agregar.
        """
        self.__saldo += cantidad
        print(f"Se han depositado {cantidad} unidades. Saldo actual: {self.__saldo}")

    def retirar(self, cantidad:float):
        """ Retirar dinero a la cuenta bancaria.

        Args:
            cantida (float): Cantidad de dinero a retirar.
        """
        if cantidad <= self.__saldo:
            self.__saldo -= cantidad
            print(f"Se han retirado {cantidad} unidades. Saldo actual: {self.__saldo}")
        else:
            print("Saldo insuficiente")

    @property
    def nombre(self):
        print("Obteniendo el nombre de la cuenta...")
        return self.__nombre

    @property
    def saldo(self):
        print("Obteniendo saldo...")
        return self.__saldo

    @property
    def dni(self):
        return self.__dni


cuenta = CuentaBancaria("Caja ahora", 1000, 12)
cuenta.depositar(500)
cuenta.retirar(200)

"""## Ejercicio 12
Implementar un setter para el atributo dni que valide que el valor introducido sea un DNI válido.
"""



#@title Solución

class CuentaBancaria:
    """ Clase CuentaBancaria
    """
    def __init__(self, nombre:str, saldo:float, dni:int):
        """ Constructor

        Args:
            nombre (str): Nombre de la cuenta.
            saldo (float): Saldo de la cuenta.
            dni (int): Dni de la persona.
        """
        self.__nombre:str = nombre
        self.__saldo:float = saldo
        self.__dni:int = dni

    def depositar(self, cantidad:float):
        """ Agrega dinero a la cuenta bancaria.

        Args:
            cantida (float): Cantidad de dinero a agregar.
        """
        self.__saldo += cantidad
        print(f"Se han depositado {cantidad} unidades. Saldo actual: {self.__saldo}")

    def retirar(self, cantidad:float):
        """ Retirar dinero a la cuenta bancaria.

        Args:
            cantida (float): Cantidad de dinero a retirar.
        """
        if cantidad <= self.__saldo:
            self.__saldo -= cantidad
            print(f"Se han retirado {cantidad} unidades. Saldo actual: {self.__saldo}")
        else:
            print("Saldo insuficiente")

    @property
    def nombre(self):
        return self.__nombre

    @property
    def saldo(self):
        return self.__saldo

    @property
    def dni(self):
        return self.__dni

    @dni.setter
    def dni(self, nuevo_dni:int):
        if self.validar_dni(nuevo_dni):
            self.__dni = nuevo_dni
            print("DNI actualizado correctamente")
        else:
            print("DNI inválido")

    def validar_dni(self, dni):
        """ Todos los dni son válidos o implemente una validación
        """
        return True


cuenta = CuentaBancaria("Caja ahora", 1000, 12)
print("DNI actual:", cuenta.dni)
cuenta.dni = "11111"
print("Nuevo DNI:", cuenta.dni)

"""## Ejercicio 13
Implementar un getter para el atributo saldo que imprima un mensaje antes de devolver el valor.
"""



#@title Solución
#@title Solución

class CuentaBancaria:
    """ Clase CuentaBancaria
    """
    def __init__(self, nombre:str, saldo:float, dni:int):
        """ Constructor

        Args:
            nombre (str): Nombre de la cuenta.
            saldo (float): Saldo de la cuenta.
            dni (int): Dni de la persona.
        """
        self.__nombre:str = nombre
        self.__saldo:float = saldo
        self.__dni:int = dni

    def depositar(self, cantidad:float):
        """ Agrega dinero a la cuenta bancaria.

        Args:
            cantida (float): Cantidad de dinero a agregar.
        """
        self.__saldo += cantidad
        print(f"Se han depositado {cantidad} unidades. Saldo actual: {self.__saldo}")

    def retirar(self, cantidad:float):
        """ Retirar dinero a la cuenta bancaria.

        Args:
            cantida (float): Cantidad de dinero a retirar.
        """
        if cantidad <= self.__saldo:
            self.__saldo -= cantidad
            print(f"Se han retirado {cantidad} unidades. Saldo actual: {self.__saldo}")
        else:
            print("Saldo insuficiente")

    @property
    def nombre(self):
        return self.__nombre

    @property
    def saldo(self):
        print("Obteniendo saldo...")
        return self.__saldo

    @property
    def dni(self):
        return self.__dni

    @dni.setter
    def dni(self, nuevo_dni:int):
        if self.validar_dni(nuevo_dni):
            self.__dni = nuevo_dni
            print("DNI actualizado correctamente")
        else:
            print("DNI inválido")

    def validar_dni(self, dni):
        """ Todos los dni son válidos o implemente una validación
        """
        return True


cuenta = CuentaBancaria("Caja ahora", 1000, 12)
print("Saldo actual:", cuenta.saldo)

"""# Asociación

## Ejercicio 14
Crear una clase Autor con los atributos nombre y nacionalidad.
"""



#@title Solución

class Autor:
    """ Clase Autor
    """

    def __init__(self, nombre:str, nacionalidad:str):
        """ Constructor

        Args:
            nombre (str): Contiene el nombre.
            nacionalidad (str): Contiene la nacionalidad.
        """
        self.nombre:str = nombre
        self.nacionalidad:str = nacionalidad

"""## Ejercicio 15
Crear una clase Editorial con los atributos nombre y sede.

"""



#@title Solución

class Editorial:
    """ Clase Editorial
    """

    def __init__(self, nombre:str, sede:str):
        """ Constructor

        Args:
            nombre (str): Contiene el nombre.
            sede (str): Contiene la sede.
        """
        self.nombre:str = nombre
        self.sede:str = sede

"""## Ejercicio 16
Escribir un programa que cree un libro, un autor y una editorial, y los asocie entre sí.
"""



#@title Solución

class Libro:
    """ Clase Libro
    """
    def __init__(self, titulo:str, autor:Autor, editorial:Editorial):
        """ Constructor

        Args:
            titulo (str): Contiene el título.
            autor (Autor): Contiene el autor.
            editorial (Editorial): Contiene la editorial.
        """
        self.titulo:str = titulo
        self.autor:Autor = autor
        self.editorial:Editorial = editorial

autor = Autor("Gabriel García Márquez", "Colombiana")
editorial = Editorial("Sudamericana", "Buenos Aires")
libro = Libro("Cien años de soledad", autor, editorial)

print("Información del libro:")
print("Título:", libro.titulo)
print("Autor:", libro.autor.nombre)
print("Nacionalidad del autor:", libro.autor.nacionalidad)
print("Editorial:", libro.editorial.nombre)
print("Sede de la editorial:", libro.editorial.sede)