# -*- coding: utf-8 -*-
"""Semana_06-10-Dataclass.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1A-KQOMRiMv4ThtSdBWrkGRYYo4kfUzwS

## [Dataclass](https://docs.python.org/3/library/dataclasses.html)

Una característica que viene desde Python 3.7 es la clase de dataclass. Una clase de datos es una clase que normalmente contiene principalmente datos, aunque en realidad no hay ninguna restricción. Se crea utilizando el nuevo decorador `@dataclass`, de la siguiente manera:
"""

from dataclasses import dataclass

@dataclass
class Carta:
    rango: str
    palo: str

"""> Para aquellos que no conocen la baraja inglesa ver el [link](https://es.m.wikipedia.org/wiki/Baraja_inglesa).

Una clase de datos viene con una funcionalidad básica ya implementada. Por ejemplo, puede crear instancias de clases de datos, imprimirlas y compararlas directamente.
"""

reina_de_corazones = Carta('Q', 'Corazones')

print('El rango de la carta reina_de_corazones es:', reina_de_corazones.rango)
print()
print('La carta reina_de_corazones contiene los siguientes atributos:', reina_de_corazones)
print()
reina_de_corazones_2 = Carta('Q', 'Corazones')
print('Comparamos las cartas reina_de_corazones y reina_de_corazones_2:')
print('¿Son iguales?', reina_de_corazones == reina_de_corazones_2)

"""Ahora vamos a crear una clase normal para ver cualse son las diferencias.


"""

class CartaClaseNormal:
  def __init__(self, rango:str, palo:str):
    self.rango:str = rango
    self.palo:str = palo

"""Si bien no es mucho más código para escribir, ya se pueden ver signos del problema del código repetitivo: `rango` y `palo` se repiten tres veces simplemente para inicializar un objeto. Además, si intentamos usar esta clase simple, notarás que la representación de los objetos no es muy descriptiva y, por alguna razón, una reina de corazones no es lo mismo que una reina de corazones 2."""

reina_de_corazones_normal = CartaClaseNormal('Q', 'Corazones')

print('El rango de la carta reina_de_corazones_normal es:', reina_de_corazones_normal.rango)
print()
print('La carta reina_de_corazones_normal contiene los siguientes atributos:', reina_de_corazones_normal)
print()
reina_de_corazones_normal_2 = CartaClaseNormal('Q', 'Corazones')
print('Comparamos las cartas reina_de_corazones_normal y reina_de_corazones_normal_2:')
print('¿Son iguales?', reina_de_corazones_normal == reina_de_corazones_normal_2)

"""Parece que las clases de datos nos están ayudando. De forma predeterminada, las clases de datos implementan un método `.__repr__()` para proporcionar una buena representación de un `str` y un método `.__eq__()` que puede realizar comparaciones básicas de objetos. Para que la clase `CartaClaseNormal` imite a la clase de datos anterior, también debe agregar estos métodos."""

class CartaClaseNormal:
  def __init__(self, rango, palo):
    self.rango = rango
    self.palo = palo

  def __repr__(self):
    return (f'{self.__class__.__name__}'
    f'(rango={self.rango!r}, palo={self.palo!r})')

  def __eq__(self, otro):
    if otro.__class__ is not self.__class__:
      return NotImplemented
    return (self.rango, self.palo) == (otro.rango, otro.palo)

"""Vamos a ver que pasa con estos agregados."""

reina_de_corazones_normal = CartaClaseNormal('Q', 'Corazones')

print('El rango de la carta reina_de_corazones_normal es:', reina_de_corazones_normal.rango)
print()
print('La carta reina_de_corazones_normal contiene los siguientes atributos:', reina_de_corazones_normal)
print()
reina_de_corazones_normal_2 = CartaClaseNormal('Q', 'Corazones')
print('Comparamos las cartas reina_de_corazones_normal y reina_de_corazones_normal_2:')
print('¿Son iguales?', reina_de_corazones_normal == reina_de_corazones_normal_2)

"""## Alternativas a las clases de datos
Para estructuras de datos simples, probablemente ya hayas usado las tuplas o diccionarios. Puedes representar la carta de la reina de corazones de cualquiera de las siguientes maneras.
"""

reina_de_corazones_tupla: tuple = ('Q', 'Corazones')
print('Mostramos la variable reina_de_corazones_tupla:', reina_de_corazones_tupla)
reina_de_corazones_dict: dict = {'rango': 'Q','palo': 'Corazones'}
print('Mostramos la variable reina_de_corazones_dict:', reina_de_corazones_dict)

"""Funciona, pero implica mucha responsabilidad por parte del programador:

- Debes recordar que la reina_de_corazones_... variable representa una carta.
- Para la versión de tupla, debes recordar el orden de los atributos.Escribir `('Espadas', 'A')` puede causar problemas en el programa, pero probablemente no te dará un mensaje de error fácil de entender.
- Si utilizas la versión del diccionario, debes asegurarte de que los nombres de los atributos sean coherentes. Por ejemplo, `{'rango': 'A', 'palos': 'Espadas'}` no funcionará como se espera.

Además, el uso de estas estructuras no es ideal.
"""

print('Solo puedo acceder por posiciones, veamos la posición 0:', reina_de_corazones_tupla[0])
print('Debo acceder por la palabra clave, y la debo repetir por todo el código:', reina_de_corazones_dict['palo'])

"""Una mejor alternativa es [namedtuple](https://docs.python.org/3/library/collections.html#collections.namedtuple). Se ha utilizado durante mucho tiempo para crear pequeñas estructuras de datos legibles. De hecho, podemos crear el ejemplo de clase de datos anterior utilizando un namedtuplede la siguiente forma."""

from collections import namedtuple

NamedTupleCarta = namedtuple('NamedTupleCarta', ['rango', 'palo'])

"""Esta definición NamedTupleCarta dará exactamente el mismo resultado que nuestra `dataclass Carta` de ejemplo."""

reina_de_corazones_nt = NamedTupleCarta('Q', 'Corazones')

print('El rango de la carta reina_de_corazones_nt es:', reina_de_corazones_nt.rango)
print()
print('La carta reina_de_corazones_nt contiene los siguientes atributos:', reina_de_corazones_nt)
print()
reina_de_corazones_nt_2 = NamedTupleCarta('Q', 'Corazones')
print('Comparamos las cartas reina_de_corazones_nt y reina_de_corazones_nt_2:')
print('¿Son iguales?', reina_de_corazones_nt == reina_de_corazones_nt_2)

"""Entonces, ¿por qué molestarse con las clases de datos? En primer lugar, las clases de datos vienen con muchas más características de las que ha visto hasta ahora. Al mismo tiempo, namedtuple tiene otras características que no son necesariamente deseables. Por diseño, unaa namedtuple es una tupla regular. Esto se puede ver en la siguente celda."""

Persona = namedtuple('Persona', ['nombre', 'apellido'])
as_de_espadas = NamedTupleCarta('A', 'Espadas')
print('Creamos la carta as_de_espadas:', as_de_espadas)
persona = Persona('A', 'Espadas')
print('Creamos una persona:', persona)
print('Comparamos la carta as_de_espadas con la persona. ¿Son iguales? ', as_de_espadas == persona)

"""También namedtuple viene con algunas restricciones. Por ejemplo, es difícil agregar valores predeterminados a algunos de los campos de a namedtuple. También es inmutable por naturaleza. Es decir, el `valor` nunca puede cambiar. En algunas aplicaciones, esta es una característica increíble, pero en otras configuraciones, sería bueno tener más flexibilidad.

Las clases de datos no reemplazarán todos los usos de namedtuple. Por ejemplo, si necesita que su estructura de datos se comporte como una tupla, ¡una tupla con nombre es una excelente alternativa!

Otra alternativa, y una de las inspiraciones para las clases de datos, es el proyecto [attrs](http://www.attrs.org/). Con attrs (pip install attrs), podemos escribir una clase de tarjeta de la siguiente manera.
"""

!pip install attrs

import attr

@attr.s
class AttrsCarta:
    valor = attr.ib()
    palo = attr.ib()

"""Esto se puede utilizar exactamente de la misma manera que la dataclass `Carta` y `NamedTupleCarta` anteriores. El proyecto `attrs` es excelente y admite algunas funciones que las clases de datos no tienen, incluidos los conversores y validadores. Además, attrs ha existido durante un tiempo y es compatible con Python 2.7, así como con Python 3.4 y versiones posteriores. Sin embargo, como attrs no es parte de la biblioteca estándar, agrega una dependencia externa a tus proyectos. A través de las clases de datos, habrá una funcionalidad similar disponible en todas partes.

Además de tuple, dict, namedtuple, y attrs, existen muchos otros proyectos similares, incluidos typing.NamedTuple, namedlist, attrdict, plumbery y fields. Si bien las clases de datos son una excelente alternativa nueva, aún existen casos de uso en los que una de las variantes más antiguas se adapta mejor. Por ejemplo, si necesita compatibilidad con una API específica que espera tuplas o necesita una funcionalidad que no es compatible con las clases de datos.

## Clases de datos básicos
Volvamos a las clases de datos. Como ejemplo, crearemos una clase `Posicion` que represente posiciones geográficas con un nombre, así como la latitud y la longitud.
"""

@dataclass
class Posicion:
    nombre: str
    lon: float
    lat: float

"""Lo que hace que esta sea una clase de datos es el decorador `@dataclass`.

También puedes crear clases de datos de forma similar a como se crean las tuplas con nombre. Lo siguiente es (casi) equivalente a la definición anterior.
"""

from dataclasses import make_dataclass

Position = make_dataclass('Posicion', ['nombre', 'lat', 'lon'])

"""Una clase de datos es una clase Python normal. Lo único que la distingue es que tiene métodos de modelo de datos básicos como `.__init__()`, `.__repr__()`y `.__eq__()` implementados automáticamente.

### Valores predeterminados
Es fácil agregar valores predeterminados a los campos de su clase de datos.
"""

@dataclass
class Posicion:
    nombre: str
    lat: float = 0.0
    lon: float = 0.0

"""Esto funciona exactamente como si hubiera especificado los valores predeterminados en la definición del método `.__init__()` de una clase regular.

Veamos algunos ejemplos.
"""

posicion_1:Posicion = Posicion('Null Island')
posicion_2:Posicion = Posicion('Bluebell Railway', lat=50.995644028630856)
posicion_3:Posicion = Posicion('Vancouver', 49.28247887243744, -123.12013907259335)

print('La posicion_1 es:', posicion_1)
print('La posicion_2 es:', posicion_2)
print('La posicion_3 es:', posicion_3)

"""### Sugerencias de tipo

Hasta ahora, no hemos hecho mucho ruido sobre el hecho de que las clases de datos admiten la escritura de forma predeterminada. Probablemente hayas notado que definimos los campos con una sugerencia de tipo `nombre: str`, esto dice que `nombre` debe ser una cadena de texto.

De hecho, agregar algún tipo de sugerencia de tipo es obligatorio al definir los campos en su clase de datos. Sin una sugerencia de tipo, el campo no será parte de la clase de datos. Sin embargo, si no desea agregar tipos explícitos a su clase de datos, utilice `typing.Any`.
"""

from typing import Any

@dataclass
class SinTiposEspecificos:
    nombre: Any
    valor: Any = 42

"""Si bien es necesario agregar sugerencias de tipo de alguna forma al usar clases de datos, estos tipos no se aplican en tiempo de ejecución. El siguiente código se ejecuta sin problemas.


"""

error:Posicion = Posicion(3.14, 'pi day', 2018)
print('La variable error se creo con estos datos:', error)

"""Así es como suele funcionar la tipificación en Python: Python es y siempre será un lenguaje de tipado dinámico. Para detectar errores de tipado, se pueden ejecutar comprobadores de tipos como `mypy` en el código fuente.

### Añadiendo métodos
Ya sabes que una clase de datos es simplemente una clase normal. Eso significa que puedes agregar libremente tus propios métodos a una clase de datos. Como ejemplo, calculemos la distancia entre una posición y otra a lo largo de la superficie de la Tierra. Una forma de hacerlo es utilizando la [fórmula de Haversine](https://en-m-wikipedia-org.translate.goog/wiki/Haversine_formula?_x_tr_sl=en&_x_tr_tl=es&_x_tr_hl=es&_x_tr_pto=wapp):

\begin{align*}
d &= 2r\arcsin\sqrt{\sin^2 \frac{1}{2} ({\phi_2 - \phi_1}) + \cos(\phi_1) \cos(\phi_2) \sin^2 \frac{1}{2} (\lambda_2 - \lambda_1)}
\end{align*}


Puedes agregar un método `.distancia_al_punto()` a tu clase de datos tal como lo haces con las clases normales.
"""

from math import asin, cos, radians, sin, sqrt

@dataclass
class Posicion:
    name: str
    lat: float = 0.0
    lon: float = 0.0

    def distancia_al_punto(self, punto:Posicion) -> float:
        """ Calcula la distancia entre dos puntos en la superficie de la Tierra.

        Args:
          punto (Posicion): Un punto de la tierra.

        Returns:
          float: Retorna la distancia en kilómetros.
        """
        r = 6371
        lam_1, lam_2 = radians(self.lon), radians(punto.lon)
        phi_1, phi_2 = radians(self.lat), radians(punto.lat)
        h = (sin((phi_2 - phi_1) / 2)**2
             + cos(phi_1) * cos(phi_2) * sin((lam_2 - lam_1) / 2)**2)
        return 2 * r * asin(sqrt(h))

posicion_2:Posicion = Posicion('Bluebell Railway', lat=50.995644028630856)
posicion_3:Posicion = Posicion('Vancouver', 49.28247887243744, -123.12013907259335)
print('La distancia entre Vancouver y Bluebell Railway es:', posicion_3.distancia_al_punto(posicion_2), 'kilómetros')

"""## Clases de datos más flexibles

Hasta ahora, has visto algunas de las características básicas que la clase de datos ofrece, algunos métodos prácticos y el agregado de valores predeterminados y otros métodos. Ahora aprenderemos sobre algunas características más avanzadas, como los parámetros para de el decorador  `@dataclass` y la función `field()`. Juntos, brindan más control al crear una clase de datos.

Volvamos al ejemplo de las cartas.
"""

from typing import List

@dataclass
class Carta:
    valor: str
    palo: str

@dataclass
class Baraja:
    cartas: List[Carta]

"""Se puede crear una baraja sencilla que contenga sólo dos cartas de la siguiente manera.


"""

reina_de_corazones:Carta = Carta('Q', 'Corazones')
as_de_espadas:Carta = Carta('A', 'Espadas')
dos_cartas:Baraja = Baraja([reina_de_corazones, as_de_espadas])
print('La baraja contiene las siguientes cartas:', dos_cartas)

"""### Valores predeterminados avanzados

Digamos que desea asignar un valor predeterminado a `Baraja`. Sería conveniente, por ejemplo, crear `Baraja()` una baraja francesa normal de 52 cartas. Primero, especifique los diferentes valores y palos. Luego, agregue una función `crear_baraja_francesa()` que cree una lista de instancias de `Carta`:


"""

valores = '2 3 4 5 6 7 8 9 10 J Q K A'.split()
palos = '♣ ♢ ♡ ♠'.split()

def crear_baraja_francesa() -> List[Carta]:
    """ Crea una lista de cartas de una baraja francesa.

    Returns:
      List[Carta]: Retorna una lista de cartas.
    """
    return [Carta(r, s) for s in palos for r in valores]

"""Para diversión, los cuatro palos diferentes se especifican utilizando sus símbolos Unicode.

> Nota: Arriba, usamos glifos Unicode como ♠ directamente en el código fuente. Pudimos hacer esto porque Python admite la escritura de código fuente en UTF-8 de manera predeterminada. Consulta [esta página sobre la entrada Unicode](https://en.wikipedia.org/wiki/Unicode_input) para saber cómo ingresarlos en tu programa. También puedes ingresar los símbolos Unicode para los palos usando \Ncaracteres de escape nombrados (como \N{BLACK SPADE SUIT}) o \ucaracteres de escape Unicode (como \u2660).

Para simplificar las comparaciones de cartas posteriores, los valores y palos también se enumeran en su orden habitual.


"""

baraja_francesa:List[Carta] = crear_baraja_francesa()
print('La baraja es:', baraja_francesa)

"""En teoría, ahora podemos usar esta función para especificar un valor predeterminado para `Baraja.cartas`."""

import traceback

try:
  @dataclass
  class Baraja:
      cartas: List[Carta] = crear_baraja_francesa()
except ValueError:
  traceback.print_exc()

"""Esto introduce uno de los antipatrones más comunes en Python: usar argumentos predeterminados mutables. El problema es que todas las instancias de `Baraja` usarán el mismo objeto de lista como valor predeterminado de la propiedad `.cartas`. Esto significa que si, por ejemplo, se quita una carta de una `Baraja`, también desaparece de todas las demás instancias de `Baraja`. En realidad, las clases de datos intentan evitar que hagas esto, y el código anterior generará un error `ValueError`.

En cambio, las clases de datos utilizan algo llamado a `default_factory` para manejar valores predeterminados `mutables`. Para utilizar `default_factory` (y muchas otras funciones interesantes de las clases de datos), debe utilizar `field()`.
"""

from dataclasses import field

@dataclass
class Baraja:
    cartas: List[Carta] = field(default_factory=crear_baraja_francesa)

"""El argumento `default_factory` puede ser cualquier parámetro que se pueda invocar. Ahora es fácil crear una baraja completa de cartas."""

baraja_francesa:Baraja = Baraja()
print('La baraja es:', baraja_francesa)

"""El especificador `field()` se utiliza para personalizar cada campo de una clase de datos individualmente. Como referencia, estos son los parámetros admitidos por `field()`:

- default: Valor predeterminado del campo
- default_factory: Función que devuelve el valor inicial del campo
- init: Utilizar el método `.__init__()`. (El valor predeterminado es True.)
- repr: Utilizar campo en `repr` del objeto. (El valor predeterminado es True.)
- compare: Incluir el campo en las comparaciones. (El valor predeterminado es True.)
- hash: Incluir el campo al calcular `hash()` (El valor predeterminado es utilizar el mismo que para compare).
- metadata: Un mapeo con información sobre el campo

En `Posicion`, vimos cómo agregar valores predeterminados simples escribiendo `lat: float = 0.0`. Sin embargo, si también quieres personalizar el campo, por ejemplo para ocultarlo en `repr`, necesitas usar el `default` parámetro: `lat: float = field(default=0.0, repr=False)`. No puedes especificar `default` y `default_factory` dentro del mismo `field`.

El parámetro `metadata` no lo utilizan las clases de datos en sí, pero está disponible para que lo utilices (o paquetes de terceros) adjunten información a los campos. En `Posicion`, podría especificar que la latitud y la longitud se indiquen en grados.
"""

@dataclass
class Posicion:
    nombre: str
    lon: float = field(default=0.0, metadata={'unit': 'degrees'})
    lat: float = field(default=0.0, metadata={'unit': 'degrees'})

"""El campo metadata (y otra información sobre un campo) se pueden recuperar utilizando la función `fields()` (observe el plural)."""

from dataclasses import fields
print('Vamos a ver la metadata de Posicion"',fields(Posicion))
print('La unidad de medida es:', fields(Posicion)[2].metadata['unit'])

"""Recordemos que podemos crear barajas de cartas de la nada."""

Baraja()

"""Si bien esta representación de a `Baraj` explícita y legible, también es muy verborrágica. Se han eliminado 48 de las 52 cartas de la baraja en el resultado anterior. En una pantalla de 80 columnas, ¡simplemente imprimir la carta completa ocupa 22 líneas! Agreguemos una representación más concisa. En general, un objeto Python tiene dos representaciones de cadena diferentes.

- repr(obj) se define por `obj.__repr__()` y debe devolver una representación del obj. Si es posible, debe ser un código que pueda recrear `obj`. Las clases de datos hacen esto.

- str(obj) se define por `obj.__str__()` y debe devolver una representación fácil de usar de `obj`. Las clases de datos no implementan un método `.__str__()`, por lo que Python recurrirá al método `.__repr__()`.

Implementemos una representación fácil de usar de un `Carta`.

"""

@dataclass
class Carta:
    valor: str
    palo: str

    def __str__(self):
        return f'{self.palo}{self.valor}'

"""Las cartas ahora lucen mucho mejor, pero el mazo sigue siendo tan detallado como siempre."""

reina_de_corazones:Carta = Carta('A', '♡')
print('La carta reina_de_corazones es:', reina_de_corazones)
baraja:Baraja = Baraja()
print('La baraja contiene las siguientes cartas:', baraja)

"""Para demostrar que también es posible agregar un método `.__repr__()` propio, romperemos el principio de que debe devolver código que pueda recrear un objeto. Después de todo, la practicidad supera a la pureza. El siguiente código agrega una representación más concisa de `Baraja`.


"""

@dataclass
class Baraja:
    cartas: List[Carta] = field(default_factory=crear_baraja_francesa)

    def __repr__(self):
        cartas_temporales:str = ', '.join(f'{c!s}' for c in self.cartas)
        return f'{self.__class__.__name__}({cartas_temporales})'

"""Tengamos en cuenta el sespecificador `!` en el str de formato`{c!s}`. Significa que queremos utilizar explícitamente la representación `str()` de cada `Carta`. Con el nuevo `.__repr__()`, la representación de `Bajara` será más agradable a la vista.


"""

Baraja()

"""Esta es una representación más bonita del mazo. Sin embargo, tiene un costo. Ya no puedes recrear el mazo ejecutando su representación. A menudo, sería mejor implementar la misma representación en `.__str__()` en su lugar.

### Comparando cartas

En muchos juegos de cartas, las cartas se comparan entre sí. Por ejemplo, en un juego típico de bazas, la carta más alta se lleva la baza. Tal como está implementada actualmente, la `Carta` no admite este tipo de comparación.
"""

reina_de_corazones:Carta = Carta('Q', '♡')
as_de_espadas:Carta = Carta('A', '♠')
try:
  print('El as de espadas en mayor a la reina de corazones?', as_de_espadas > reina_de_corazones)
except TypeError:
  traceback.print_exc()

"""Sin embargo, esto es fácil de corregir:"""

from typing import List

@dataclass(order=True)
class Carta:
    valor: str
    palo: str

    def __str__(self):
        return f'{self.palo}{self.valor}'

"""El decorador `@dataclass` tiene dos formas. Hasta ahora has visto la forma simple donde no utilizamos paréntesis ni parámetros. Sin embargo, también puedes darle parámetros al `@dataclass()` entre paréntesis. Se admiten los siguientes parámetros:

- init: Agrega el método `.__init__()`. (El valor predeterminado es True.)
- repr: Agrega el método  `.__repr__()`. (El valor predeterminado es True.)
- eq: Agrega el método `.__eq__()`.  (El valor predeterminado es True.)
- order: Agrega un método de ordenamiento. (El valor predeterminado es False.)
- unsafe_hash: Agrega el método `.__hash__()`. (El valor predeterminado es False.)
- frozen: Si True, la asignación a campos genera una excepción. (El valor predeterminado es False).

Consulte el [PEP original](https://www.python.org/dev/peps/pep-0557/#id7) para obtener más información sobre cada parámetro. Después de configurar order=True, `Carta` pueden comparar las instancias.
"""

reina_de_corazones:Carta = Carta('Q', '♡')
as_de_espadas:Carta = Carta('A', '♠')
try:
  print('El as de espadas en mayor a la reina de corazones?', as_de_espadas > reina_de_corazones)
except TypeError:
  traceback.print_exc()

"""¿Pero cómo se comparan las dos cartas? No has especificado cómo debe hacerse y, por alguna razón, Python parece creer que una reina es más alta que un as.

Resulta que las clases de datos comparan objetos como si fueran tuplas. En otras palabras, una reina es más alta que un as porque 'Q' va después 'A' en el alfabeto.
"""

print('El as de espadas en mayor a la reina de corazones?', ('A', '♠') > ('Q', '♡'))

"""Esto no nos funciona realmente. En su lugar, necesitamos definir algún tipo de índice de ordenación que utilice el orden de `valores` y `palos`. Algo como esto."""

valores = '2 3 4 5 6 7 8 9 10 J Q K A'.split()
palos = '♣ ♢ ♡ ♠'.split()
carta = Carta('Q', '♡')
print('El valor de esta carta es:', valores.index(carta.valor) * len(palos) + palos.index(carta.palo))

"""Para `Carta` podemos utilizar este índice de ordenación para comparaciones, necesitamos agregar un campo `.sort_index` a la clase. Sin embargo, este campo debe calcularse a partir de los otros campos `.valor` y `.palo` de manera automática. Para eso sirve exactamente el método especial `.__post_init__()`. Permite un procesamiento especial después de llamar al método `.__init__()`."""

valores = '2 3 4 5 6 7 8 9 10 J Q K A'.split()
palos = '♣ ♢ ♡ ♠'.split()

@dataclass(order=True)
class Carta:
    indice_de_ordenamiento: int = field(init=False, repr=False)
    valor: str
    palo: str

    def __str__(self):
        return f'{self.palo}{self.valor}'

    def __post_init__(self):
        self.indice_de_ordenamiento = (valores.index(self.valor) * len(palos)
                           + palos.index(self.palo))

"""Tené en cuenta que la propiedad `.indice_de_ordenamiento` se agrega como el primer campo de la clase. De esa manera, la comparación se realiza primero utilizando `.indice_de_ordenamiento` y solo si hay empates se utilizan los otros campos. Al utilizar `field()`, también debe especificar que `.indice_de_ordenamiento` no se debe incluir como parámetro en el método `.__init__()` (porque se calcula a partir de los campos `.valor` y `.palo`). Para evitar confundir al usuario sobre este detalle de implementación, probablemente también sea una buena idea eliminar `.indice_de_ordenamiento` de la representación clase.

Finalmente, los ases son altos.
"""

reina_de_corazones:Carta = Carta('Q', '♡')
as_de_espadas:Carta = Carta('A', '♠')
try:
  print('El as de espadas en mayor a la reina de corazones?', as_de_espadas > reina_de_corazones)
except TypeError:
  traceback.print_exc()

"""Ahora podemos crear fácilmente un mazo ordenado."""

Baraja(sorted(crear_baraja_francesa()))

"""## Clases de datos inmutables
Una de las características definitorias de la `namedtuple` que vimos antes es que es inmutable. Es decir, el valor de sus campos nunca puede cambiar. Para muchos tipos de clases de datos, ¡esta es una gran idea! Para hacer que una clase de datos sea inmutable, debemos configurarla como `frozen=True` cuando la creamos. Por ejemplo, la siguiente es una versión inmutable de la clase `Posicion` que vimos antes.
"""

@dataclass(frozen=True)
class Posicion:
    nombre: str
    lon: float = 0.0
    lat: float = 0.0

"""En una clase de datos congelados, no se pueden asignar valores a los campos después de la creación."""

pos:Posicion = Posicion('Oslo', 10.8, 59.9)
print('La posición es:', pos.nombre)

from dataclasses import FrozenInstanceError
try:
  pos.name = 'Estocolmo'
except FrozenInstanceError:
  traceback.print_exc()

"""Sin embargo, tené en cuenta que si tu clase de datos contiene campos mutables, estos pueden cambiar."""

@dataclass(frozen=True)
class CartaImmutable:
    valor: str
    palo: str

@dataclass(frozen=True)
class BarajaImmutable:
    cartas: List[CartaImmutable]

"""Aunque tanto `CartaImmutable` como `BarajaImmutable` son inmutables, la lista que contiene `cartas` no lo es. Por lo tanto, aún se pueden cambiar las cartas del mazo."""

reina_de_corazones:CartaImmutable = CartaImmutable('Q', 'Corazones')
as_de_espadas:CartaImmutable = CartaImmutable('A', 'Espadas')
baraja:BarajaImmutable = BarajaImmutable([reina_de_corazones, as_de_espadas])
print('Mostramos la baraja:', baraja)

baraja.cartas[0] = CartaImmutable('7', '♢')
print('Mostramos la baraja:', baraja)

"""Para evitar esto, asegúrate de que todos los campos de una clase de datos  inmutable utilicen tipos inmutables (pero recuerda que los tipos no se aplican en tiempo de ejecución). Se `BarajaImmutable` se debe implementar utilizando una tupla en lugar de una lista.

## Herencia
Puedes crear subclases de datos con total libertad. A modo de ejemplo, ampliaremos nuestra clase `Posicion`, por ejemplo con un campo `pais`.
"""

@dataclass
class Posicion:
    nombre: str
    lon: float
    lat: float

@dataclass
class Capital(Posicion):
    pais: str

"""En este sencillo ejemplo, todo funciona sin problemas.


"""

capital:Capital = Capital('Oslo', 10.8, 59.9, 'Noruega')
print('La capital es:', capital)

"""El campo `pais` de `Capital` se agrega después de los tres campos originales en `Posicion`. Las cosas se complican un poco más si algún campo en la clase base tiene valores predeterminados."""

try:
  @dataclass
  class Posicion:
      nombre: str
      lon: float = 0.0
      lat: float = 0.0

  @dataclass
  class Capital(Posicion):
      pais: str
except TypeError:
  traceback.print_exc()

"""Este código se bloqueará inmediatamente y muestra la excepción `TypeError` porque el argumento no predeterminado 'país' se encuentra después de un campo con valor predeterminado. El problema es que nuestro nuevo campo `pais` no tiene un valor predeterminado, mientras que los campos `lon` y `lat` tienen valores predeterminados. La clase de datos intentará escribir un método `.__init__()` con la siguiente firma.


```
def __init__(nombre: str, lon: float = 0.0, lat: float = 0.0, pais: str):
    ...
```

Sin embargo, esto no es válido en Python. Si un parámetro tiene un valor predeterminado, todos los parámetros siguientes también deben tener un valor predeterminado. En otras palabras, si un campo en una clase base tiene un valor predeterminado, entonces todos los campos nuevos agregados en una subclase también deben tener valores predeterminados.

Otra cosa que hay que tener en cuenta es cómo se ordenan los campos en una subclase. A partir de la clase base, los campos se ordenan en el orden en el que se definieron por primera vez. Si se redefine un campo en una subclase, su orden no cambia. Por ejemplo, si define `Posicion` y `Capital` de la siguiente manera.

"""

@dataclass
class Posicion:
    nombre: str
    lon: float = 0.0
    lat: float = 0.0

@dataclass
class Capital(Posicion):
    pais: str = 'Desconocida'
    lat: float = 40.0

"""Entonces el orden de los campos en `Capital` seguirá siendo `nombre`, `lon`, `lat`, `pais`. Sin embargo, el valor predeterminado de `lat` será 40.0.

"""

capital:Capital =Capital('Madrid', pais='España')
print('La capital es:', capital)

"""## Optimización de clases de datos

Los [slots](https://docs.python.org/reference/datamodel.html#slots) se pueden usar para hacer que las clases sean más rápidas y utilicen menos memoria. Las clases de datos no tienen una sintaxis explícita para trabajar con slots, pero la forma normal de crearlos también funciona para las clases de datos.
"""

@dataclass
class PosicionSimple:
    nombre: str
    lon: float
    lat: float

@dataclass
class PosicionSlot:
    __slots__ = ['nombre', 'lon', 'lat']
    nombre: str
    lon: float
    lat: float

"""Básicamente, los slots se definen `.__slots__` para enumerar las variables de una clase. Las variables o atributos que no están presentes en una clase `.__slots__` no se pueden definir. Además, una clase de slots puede no tener valores predeterminados.

La ventaja de añadir estas restricciones es que se pueden realizar ciertas optimizaciones. Por ejemplo, las clases de slots ocupan menos memoria, como se puede medir con [Pympler](https://pythonhosted.org/Pympler/).
"""

!pip install pympler

from pympler import asizeof
simple = PosicionSimple('London', -0.1, 51.5)
slot = PosicionSlot('Madrid', -3.7, 40.4)

print('El tamaño que ocupa la clase simple es:', asizeof.asizesof(simple), 'bytes')
print('El tamaño que ocupa la clase slot es:', asizeof.asizesof(slot), 'bytes')

"""De manera similar, las clases de slots suelen ser más rápidas de usar. El siguiente ejemplo mide la velocidad de acceso a los atributos en una clase de datos de slots y una clase de datos normal utilizando [timeit](https://docs.python.org/library/timeit.html) de la biblioteca estándar."""

from timeit import timeit
tiempo_slot:float = timeit ('slot.nombre', setup="slot=PosicionSlot('Oslo', 10.8, 59.9)", globals=globals())
print('El tiempo en crear una instancia de PosicionSlot y acceder al campo nombre es:', tiempo_slot, 'segundos')

tiempo_simple:float = timeit ('simple.nombre', setup="simple=PosicionSimple('Oslo', 10.8, 59.9)", globals=globals())
print('El tiempo en crear una instancia de PosicionSimple y acceder al campo nombre es:', tiempo_simple, 'segundos')

"""Se pueden dar mucha variantes en los tiempos al ejecutarlos en un colab, pero si lo ejecutamos en nuestra computadora y según estimación de python los slots deberían ser un 35% más rápidos y eficientes.

"""