# -*- coding: utf-8 -*-
"""Semana_06-02_Tipos_metodos.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yRM6nEPJsoYEGxavEk3fA3RPEG3DsXJz

## Métodos en Python: instancia, clase y estáticos
En otros momentos hemos visto como se pueden crear métodos con `def` dentro de una clase, pudiendo recibir parámetros como entrada y modificar el estado (como los atributos) de la instancia. Pues bien, haciendo uso de los decoradores, es posible crear diferentes tipos de métodos:

* Lo métodos de instancia `normales` que ya hemos visto como `nombre_del_metodo(self...)`
* Métodos de `clase` usando el decorador `@classmethod`
* Y métodos `estáticos` usando el decorador `@staticmethod`

En la siguiente clase tenemos un ejemplo donde definimos los tres tipos de métodos.
"""

from typing import Tuple

class ClaseTest:
    def metodo(self) -> Tuple:
        """ Método que representa un método normal.

        Returns:
          Tuple: Retorna una tupla con el mensaje y el argumento self.
        """
        return 'Método normal', self

    @classmethod
    def metododeclase(cls) -> Tuple:
        """ Método que representa un método de clase utilizando el decorador @classmethod.
            NOTAR QUE RECIBE UN ARGUMENTO DENOMINADO cls.

        Returns:
          Tuple: Retorna una tupla con el mensaje y el argumento cls.
        """
        return 'Método de clase', cls

    @staticmethod
    def metodoestatico() -> str:
        """ Método que representa un método de estático utilizando el decorador @staticmethod.
            NOTAR QUE NO RECIBE NINGÚN ARGUMENTO.

        Returns:
          str: Retorna un mensaje.
        """
        return "Método estático"

class Temperatura:
    escala = "Celsius"                 # atributo de clase

    def __init__(self, grados: float):
        self.grados = grados           # atributo de instancia

    def mostrar(self) -> str:          # de instancia: usa self
        return f"{self.grados} {Temperatura.escala}"

    @classmethod
    def desde_fahrenheit(cls, f: float):   # de clase: usa cls, crea objetos
        return cls((f - 32) * 5 / 9)

    @staticmethod
    def es_bajo_cero(grados: float) -> bool:   # estático: no usa ni self ni cls
        return grados < 0


t = Temperatura.desde_fahrenheit(212)
print(t.mostrar())
print(Temperatura.es_bajo_cero(-5))

"""Veamos su comportamiento en detalle uno por uno.

## Métodos de instancia

Los métodos de instancia son los métodos normales, de toda la vida, que hemos visto anteriormente. Reciben como parámetro de entrada `self` que hace referencia a la instancia que llama al método. También pueden recibir otros argumentos como entrada.

Para saber más: El uso de `self` es totalmente arbitrario. Se trata de una convención acordada por los usuarios de Python, usada para referirse a la instancia que llama al método, pero podría ser cualquier otro nombre. Lo mismo ocurre con `cls`, que veremos a continuación.
"""

class ClaseTestNormal:
    argumento_clase:str = 'incialización'
    # argumento de clase

    def __init__(self, argumento_instancia:str):
        """ Constructor de la clase

        Args:
          argumento_instancia (str): Contiene un valor a setearse en el argumento de instancia
        """
        self.argumento_instancia = argumento_instancia

    def metodo(self, arg1:str, arg2:str) -> Tuple:
        """ Método que representa un método normal.

        Args:
          arg1 (str): Primer argumento que se seteará en el argumento de instancia.
          arg2 (str): Segundo argumento que se intentará setear en el argumento de clase.

        Returns:
          Tuple: Retorna una tupla con el mensaje y el argumento self.
        """
        print(f'El método normal recibió los arguments {arg1} y {arg2}')
        print('-'*80)
        print(f'El argumento de instancia es {self.argumento_instancia}')
        self.argumento_instancia = arg1
        print(f'El argumento de instancia modificado es {self.argumento_instancia}')
        print('-'*80)
        print(f'El argumento de clase es {self.argumento_clase}')
        self.argumento_clase = arg2
        print(f'El argumento de instancia modificado es {self.argumento_clase}')
        print('-'*80)
        return 'Método normal', self

"""Y como ya sabemos, una vez creado un objeto pueden ser llamados.


"""

mi_clase_normal = ClaseTestNormal(argumento_instancia='constructor')
print('El retorno de la ejecución es:', mi_clase_normal.metodo(arg1='método_arg1', arg2='método_arg2'))

"""En vista a esto, los métodos de instancia:

* Pueden acceder y modificar los atributos del objeto sin importar de que tipo son (instancia o clase).
* Pueden acceder a otros métodos.
* Dado que desde el objeto `self` se puede acceder a la clase con `self.class`, también pueden modificar el estado de la clase.

## Métodos de clase (classmethod)
A diferencia de los métodos de instancia, los métodos de clase reciben como argumento `cls`, que hace referencia a la `clase`. Por lo tanto, pueden acceder a la clase pero `no a la instancia`.
"""

import traceback

class ClaseTestClassMethod:
    argumento_clase:str = 'incialización'
    # argumento de clase

    def __init__(self, argumento_instancia:str):
        """ Constructor de la clase

        Args:
          argumento_instancia (str): Contiene un valor a setearse en el argumento de instancia
        """
        self.argumento_instancia = argumento_instancia

    @classmethod
    def metododeclase(cls, arg1:str, arg2:str) -> Tuple:
        """ Método que representa un método de clase utilizando el decorador @classmethod.
            NOTAR QUE RECIBE UN ARGUMENTO DENOMINADO cls.

        Args:
          arg1 (str): Primer argumento que se seteará en el argumento de instancia.
          arg2 (str): Segundo argumento que se intentará setear en el argumento de clase.

        Returns:
          Tuple: Retorna una tupla con el mensaje y el argumento self.
        """
        print(f'El método normal recibió los arguments {arg1} y {arg2}')
        print('-'*80)
        try:
            print(f'El argumento de instancia es {cls.argumento_instancia}')
            cls.argumento_instancia = arg1
            print(f'El argumento de instancia modificado es {cls.argumento_instancia}')
        except AttributeError:
            print(traceback.format_exc())
        print('-'*80)
        print(f'El argumento de clase es {cls.argumento_clase}')
        cls.argumento_clase = arg2
        print(f'El argumento de instancia modificado es {cls.argumento_clase}')
        print('-'*80)
        return 'Método de clase', cls

"""Se pueden llamar sobre la clase."""

print('El retorno de la ejecución desde la clase es:', ClaseTestClassMethod.metododeclase(arg1='método_arg1', arg2='método_arg2'))

"""Notar como la llamada anterior genera un error. Este error está referenciado al `argumento_instacia` porque se está llamando al método desde la clase y no desde una instancia.

Pero también se pueden llamar sobre el objeto.
"""

mi_clase_class_method = ClaseTestClassMethod(argumento_instancia='constructor')
print('El retorno de la ejecución desde la instancia es:', mi_clase_class_method.metododeclase(arg1='método_arg1', arg2='método_arg2'))

"""Nuevamente se reproduce el error de al quere acceder al atributo de instancia con la diferencia de que en esta oportunidad se está llamando al método desde una instancia. Para comprender el error debemos tener en cuenta que ahora el primer argumento de un método de clase contiene un acceso a la clase y no a la instancia y es por está razón que se genera el error. No hay forma de acceder a la instancia dentro de un método de clase.


Por lo tanto, los métodos de clase:

* No pueden acceder a los atributos de la instancia.
* Pero si pueden modificar los atributos de la clase.

## Métodos estáticos (staticmethod)
Por último, los métodos estáticos se pueden definir con el decorador @staticmethod y no aceptan como parámetro ni la instancia ni la clase. Es por ello por lo que no pueden modificar el estado ni de la clase ni de la instancia. Pero por supuesto pueden aceptar parámetros de entrada.
"""

class ClaseTestStaticMethod:
    argumento_clase:str = 'incialización'
    # argumento de clase

    def __init__(self, argumento_instancia:str):
        """ Constructor de la clase

        Args:
          argumento_instancia (str): Contiene un valor a setearse en el argumento de instancia
        """
        self.argumento_instancia = argumento_instancia

    @staticmethod
    def metodoestatico(arg1:str, arg2:str) -> str:
        """ Método que representa un método de clase utilizando el decorador @classmethod.
            NOTAR QUE NO RECIBE UN ARGUMENTO DENOMINADO cls ni self. Esto se
            debe que no recibe referencia a la clase ni a la instancia.

        Args:
          arg1 (str): Primer argumento que se seteará en el argumento de instancia.
          arg2 (str): Segundo argumento que se intentará setear en el argumento de clase.

        Returns:
          Tuple: Retorna una tupla con el mensaje y el argumento self.
        """
        print(f'El método normal recibió los arguments {arg1} y {arg2}')
        print('-'*80)
        try:
            print(f'El argumento de instancia es {argumento_instancia}')
            argumento_instancia = arg1
            print(f'El argumento de instancia modificado es {argumento_instancia}')
        except NameError:
            print(traceback.format_exc())
        print('-'*80)
        try:
            print(f'El argumento de clase es {argumento_clase}')
            argumento_clase = arg2
            print(f'El argumento de instancia modificado es {argumento_clase}')
        except NameError:
            print(traceback.format_exc())
        print('-'*80)
        return "Método estático"

mi_clase_static_method = ClaseTestStaticMethod(argumento_instancia='constructor')

print('El retorno de la ejecución desde la clase es:', ClaseTestStaticMethod.metodoestatico(arg1='método_arg1', arg2='método_arg2'))

print('El retorno de la ejecución desde la instancia es:', mi_clase_static_method.metodoestatico(arg1='método_arg1', arg2='método_arg2'))

"""Por lo tanto el uso de los métodos estáticos pueden resultar útil para indicar que un método no modificará el estado de la instancia ni de la clase. Es cierto que se podría hacer lo mismo con un método de instancia por ejemplo, pero a veces resulta importante indicar de alguna manera estas peculiaridades, evitando así futuros problemas y malentendidos.

En otras palabras, los métodos estáticos se podrían ver como funciones normales, con la salvedad de que van ligadas a una clase concreta.
"""

