# -*- coding: utf-8 -*-
"""01_Book_Manager-Grupo_XX.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/144vWcF0fX2C0XWaMGi89eHBWPdFy1uDr

# Trabajo Práctico Integrador

## Book Manager - Sprint 1

Tomar el sitio [Cúspide](https://www.cuspide.com/) como referencia para el trabajo.

## Integrantes del grupo:

> Obtener el número de grupo de la pestaña del aula de "Trabajos Prácticos"
>
> Entrega UN SOLO integrante del grupo, debe ser siempre el mismo.
>
> Utilizar UN ÚNICO repositorio de github por grupo.

* Joaquín Betes
* Katherine Contreras
* Silvina Moyano
* Mateo Maibach
* Emilce Robles

Grupo 28

## Repositorio GITHUB

Especificar en la siguiente línea cual es la url para acceder al repositorio del grupo.

> https://github.com/katherine-j-c-s/TP1_Grupo28_Seminario_Actualizacion_I.git

## Consideraciones Generales e Importantes

- Desarrollo base: Los puntos solicitados son la base del trabajo práctico. Es posible la ampliación sin restricciones del mismo.
- Para el traceo se deben agregar 1 [secrets](https://drlee.io/how-to-use-secrets-in-google-colab-for-api-key-protection-a-guide-for-openai-huggingface-and-c1ec9e1277e0) para la utilización de github.
  - GITHUB_TOKEN
- Organización del Notebook:
  - Agregar antes del ejercicio 01 una celda donde se importan todas librerías necesarias.
  - Utilizar un título para cada celda y escribir cada funcionalidad en una celda con título.
- La defensa es individual.
- Los grupos deben mantenerse a lo largo del trabajo integrador.
- Programación Orientada a Objetos (POO):
  - Diseño de clases aplicando las bondades y características básicas de POO.
  - Encapsulamiento de datos e implementación de relaciones entre objetos.
  - Implementación de clases de lógica.
  - Cada entidad debe tener implementado su CRUD completo (Create, Read, Update y Delete / Nuevo, Lectura, Modificación y Borrado).

## Versionado y Trabajo en Equipo


- Control de Versiones: Utilizar herramientas de versionado
- Colaboradores: Brindar acceso al repositorio a las siguientes cuentas:
  - lcd-sa182@ugr.edu.ar
  - fpasinato@ugr.edu.ar
  - srobadorpapich@ugr.edu.ar
- La descripción del commit debe ser con el siguiente formato `"Día X: \<comentario del commit\>"`
- Changelog: Cada ejercicio/punto del trabajo práctico es considerado como un día distinto de trabajo. Debe quedar constancia en un archivo CHANGELOG.md de los cambios generados cada día. El changelog debe escribirse de tal forma que lo primero que se observe es el último cambio realizado, de esta forma apenas se abre el archivo se pueden leer los últimos cambios realizados. La forma de escritura debe ser un encabezado entre corchetes [Ejercicio X] y luego debajo los cambios realizado como bullets.
- El archivo README.md debe contener el sprint en el que nos encontramos y debe contener:
  - El objetivo.
  - La introducción y el contexto del sprint de trabajo.

## Criterios de evaluación

- Funcionalidad: el código debe ejecutar sin errores al dar "Ejecutar todo" (Ctrl+F9). Validar con Runtime -> Restart session and run all antes de entregar.
- Claridad: código organizado, nombres descriptivos, comentarios solo donde corresponde (funciones, clases, métodos). No se admite `git add .`.
- Estilo: [type hints](https://docs.python.org/3/library/typing.html), [pep8](https://peps.python.org/pep-0008/).

- Herramientas: librerías vistas en la cursada. Sin gdrive ni herramientas alternativas.

## Condiciones de Entrega
- Archivo `.ipynb`, ejecutado y con datos precargados, sobre copia de la plantilla original manteniendo la nomenclatura del nombre.
- Canal: aula virtual. Correo a lcd-sa182@ugr.edu.ar solo si el plazo finalizó. No se aceptan enlaces.
- Los trabajos que no cumplan con los requisitos no serán tomados en cuenta como nota final. Solo serán corregidos y evaluados con nota para la devolución correspondiente. Se considera incumplimiento a:
  - Entregas fuera de término.
  - Trabajos que no se entreguen sobre la plantilla de trabajo estipulada.
  - Trabajos que no se ejecuten completos (que contengan errores intermedios al dar "Ejecutar todo").

---

## Objetivo

El objetivo principal de este proyecto es aplicar los conocimientos adquiridos en programación orientada a objetos, almacenamiento de datos en archivos para su persistencia.

## Introducción y Contexto del problema

### Sprint 1

Una librería con venta al público necesita modernizar su sistema de gestión de inventario de libros. Debido a la fluctuación en los costos de importación de material bibliográfico, el sistema debe gestionar precios en diferentes monedas y seguir de cerca la cotización del dólar para actualizar sus valores en tiempo real.

El objetivo es desarrollar una aplicación de consola (CLI) robusta en Python que permita gestionar el inventario de una librería, cotizar los libros en tiempo real según el valor del dólar y comparar precios automáticamente con la competencia web.

Descripción de las Entidades

Para cumplir con el requerimiento, se han identificado las siguientes entidades:

- Libro: representa cada título del catálogo de la librería (isbn, título, autor, editorial, género, etc.).
- Genero: categoría literaria a la que pertenece un libro (novela, ensayo, infantil, técnico, etc.).
- Editorial: proveedor/distribuidora que provee los libros a la librería.
- Moneda: las distintas monedas en las que se puede expresar un precio (ARS, USD, etc.).
- TipoCotizacion: los distintos tipos de cotización del dólar (Oficial, Blue, MEP, etc.).
- Precio: valor monetario asociado a un libro en una moneda determinada.
- Stock: cantidad disponible de cada libro.
- Cotizacion: registro histórico de las cotizaciones por tipo y fecha.

---
"""

from google.colab import userdata
GITHUB_TOKEN = userdata.get('GITHUB_TOKEN')

"""## Ejercicio 01

> Puntos: 1

Inicialización y configuración de la herramienta de versionado. Vamos a trabajar sobre la rama llamada "Sprint_1".

La estructura de directorios es:

```
book_manager/
├── src/
│   └── book_manager/
│       ├── entities/
│       │   └── entities.py
│       ├── preload_data/
│       │   └── preload_data.py
│       ├── repositories/
│       │   └── repositories.py
│       ├── services/
│       │   └── services.py
│       ├── migrations
│       │   └── csv
│       ├── ui/
│       │   └── console.py
│       └── main.py
├── CHANGELOG.md
├── README.md
└── requirements.txt
```

"""

# Commented out IPython magic to ensure Python compatibility.
#@title Posicionamiento y seteo de path
# La carpeta todavía no existe: el clonado está en la sección de checks.
# Se deja preparado el PYTHONPATH para no cortar "Ejecutar todo".
import os
RUTA_SRC = "/content/TP1_Grupo28_Seminario_Actualizacion_I/book_manager/src"
os.environ["PYTHONPATH"] = RUTA_SRC
if os.path.isdir(RUTA_SRC):
    os.chdir(RUTA_SRC)
print(f"PYTHONPATH = {RUTA_SRC}")

"""## Ejercicio 02

> Puntos: 2

Definir la/s clase/s entidad necesarias para el uso del sistema (Libro, Genero, Editorial, Moneda, TipoCotizacion, Precio, Stock, CotizacionDolar). Se debe representar todo con objetos y se deben aplicar las facilidades que nos permiten una mejor programación. Se debe aplicar la encapsulación.

Archivo/s de trabajo:
- book_manager/entities/entities.py

## Ejercicio 03

> Puntos: 2


Definir la/s clase/s responsables de la persistencia de datos.

Todas las clases deben tener su propio CRUD (Create/Read/Update/Delete o Alta/Lectura/Modificación/Borrado).

Archivo/s de trabajo:
- book_manager/repositories/repositories.py

Tomar como base el siguiente código.

```python
import abc
from typing import TypeVar, Generic, List, Optional

T = TypeVar('T', bound=EntidadBase)


class IRepositorio(abc.ABC, Generic[T]):
  '''Interfaz para repositorios que manejan entidades con operaciones CRUD básicas.'''

  @abc.abstractmethod
  def crear(self, entidad: T) -> T:
    '''Crea una nueva entidad en el repositorio.

    Args:
        entidad (T): La entidad a crear.

    Returns:
        T: La entidad creada.

    Raises:
        ValueError: Si ya existe una entidad con el mismo ID.
    '''
    pass

  @abc.abstractmethod
  def leer_por_id(self, id: int) -> Optional[T]:
    '''Lee una entidad del repositorio por su ID.

    Args:
        id (int): El ID de la entidad a leer.

    Returns:
        Optional[T]: La entidad si se encuentra, None en caso contrario.
    '''
    pass

  @abc.abstractmethod
  def leer_todos(self) -> List[T]:
    '''Lee todas las entidades del repositorio.

    Returns:
        List[T]: Una lista de todas las entidades.
    '''
    pass

  @abc.abstractmethod
  def actualizar(self, entidad: T) -> T:
    '''Actualiza una entidad existente en el repositorio.

    Args:
        entidad (T): La entidad a actualizar (debe tener un ID existente).

    Returns:
        T: La entidad actualizada.

    Raises:
        ValueError: Si no se encuentra la entidad para actualizar.
    '''
    pass

  @abc.abstractmethod
  def eliminar(self, id: int) -> bool:
    '''Elimina una entidad del repositorio por su ID.

    Args:
        id (int): El ID de la entidad a eliminar.

    Returns:
        bool: True si la entidad fue eliminada, False si no se encontró.
    '''
    pass


class IRepositorioStock(abc.ABC):
  '''Interfaz para repositorios del tipo Stock.'''

  @abc.abstractmethod
  def crear(self, stock: Stock) -> Stock:
    '''Crea un nuevo registro de stock.

    Args:
        stock (Stock): El objeto Stock a crear.

    Returns:
        Stock: El objeto Stock creado.

    Raises:
        ValueError: Si ya existe un registro de stock para el mismo libro.
    '''
    pass

  @abc.abstractmethod
  def leer_por_libro(self, libro_id: int) -> Optional['Stock']:
    '''Lee un registro de stock por ID de libro.

    Args:
        libro_id (int): El ID del libro asociado al stock.

    Returns:
        Optional[Stock]: El objeto Stock si se encuentra, None en caso contrario.
    '''
    pass

  @abc.abstractmethod
  def actualizar(self, stock: 'Stock') -> 'Stock':
    '''Actualiza un registro de stock existente.

    Args:
        stock (Stock): El objeto Stock a actualizar (debe tener un libro_id existente).

    Returns:
        Stock: El objeto Stock actualizado.

    Raises:
        ValueError: Si no se encuentra el stock para actualizar.
    '''
    pass

  @abc.abstractmethod
  def eliminar(self, libro_id: int) -> bool:
    '''Elimina un registro de stock por ID de libro.

    Args:
        libro_id (int): El ID del libro asociado al stock a eliminar.

    Returns:
        bool: True si el stock fue eliminado, False si no se encontró.
    '''
    pass


class IRepositorioCotizacionDolar(abc.ABC):
  '''Interfaz para repositorios del tipo RepositorioCotizacionDolar.'''

  @abc.abstractmethod
  def crear(self, cotizacion: 'CotizacionDolar') -> 'CotizacionDolar':
    '''Crea una nueva cotización de dólar.

    Args:
        cotizacion (CotizacionDolar): El objeto CotizacionDolar a crear.

    Returns:
        CotizacionDolar: El objeto CotizacionDolar creado.

    Raises:
        ValueError: Si ya existe una cotización para el mismo tipo y fecha.
    '''
    pass

  @abc.abstractmethod
  def leer_por_tipo_y_fecha(self, tipo_id: int, fecha: datetime.date) -> Optional['CotizacionDolar']:
    '''Lee una cotización de dólar por tipo y fecha.

    Args:
        tipo_id (int): El ID del tipo de cotización (e.g., 'Oficial', 'Blue').
        fecha (datetime.date): La fecha de la cotización.

    Returns:
        Optional[CotizacionDolar]: La cotización si se encuentra, None en caso contrario.
    '''
    pass

  @abc.abstractmethod
  def leer_historico_por_tipo(self, tipo_id: int) -> List['CotizacionDolar']:
    '''Lee el histórico de cotizaciones para un tipo específico.

    Args:
        tipo_id (int): El ID del tipo de cotización.

    Returns:
        List[CotizacionDolar]: Una lista de cotizaciones históricas para el tipo dado.
    '''
    pass

  @abc.abstractmethod
  def actualizar(self, cotizacion: 'CotizacionDolar') -> 'CotizacionDolar':
    '''Actualiza una cotización de dólar existente.

    Args:
        cotizacion (CotizacionDolar): El objeto CotizacionDolar a actualizar.

    Returns:
        CotizacionDolar: El objeto CotizacionDolar actualizado.
    '''
    pass

  @abc.abstractmethod
  def eliminar(self, tipo_id: int, fecha: datetime.date) -> bool:
    '''Elimina una cotización de dólar por tipo y fecha.

    Args:
        tipo_id (int): El ID del tipo de cotización.
        fecha (datetime.date): La fecha de la cotización a eliminar.

    Returns:
        bool: True si la cotización fue eliminada, False si no se encontró.
    '''
    pass
```

## Ejercicio 04

> Puntos: 2


Definir la/s clase/s responsables de la lógica que se debe aplicar a cada operación/método de las clases.

Archivo/s de trabajo:
- book_manager/services/services.py

## Punto 05

> Puntos: 1

Crear archivos para la importación de datos, escribirlos dentro de la carpeta `migrations/csv`.

Cada clase debe tener un mínimo de 10 registros.

Archivo/s de trabajo:
- book_manager/preload_data/preload_data.py

## Punto 06

> Puntos: 1


Armar las interfaces gráficas del sistema, estas deben operar con los CRUD de cada clase.

Archivo/s de trabajo:
- book_manager/ui/console.py

## Punto 07

> Puntos: 1

Crear el archivo main.py que se encarga de ejecutar el sistema.

Archivo/s de trabajo:
- book_manager/main.py

---

# Checks y validaciones

## Clonar el repositorio

Completar la parte que falta.
"""

!git clone https://{GITHUB_TOKEN}@github.com/katherine-j-c-s/TP1_Grupo28_Seminario_Actualizacion_I.git || echo Repositorio ya clonado

# Commented out IPython magic to ensure Python compatibility.
#@title Posicionamiento y seteo de path
# %cd /content/TP1_Grupo28_Seminario_Actualizacion_I/book_manager/src
# cambio o seteo la variable de entorno PYTHONPATH para simplificar la ejecución
# e importación de módulos generados manualmente o por el usuario.
!export PYTHONPATH=/content/TP1_Grupo28_Seminario_Actualizacion_I/book_manager/src
# %env PYTHONPATH=/content/TP1_Grupo28_Seminario_Actualizacion_I/book_manager/src

!git fetch --all
!git checkout -B Sprint_1 origin/Sprint_1

"""## Ejecución del programa

Ejecutar las siguientes acciones:
- Un listado y un alta o modificación de cada modelo (tablas de la base de datos). Realizarlo en orden, es decir, tomar Libro realizar el listado y luego la acción seleccionada.
- Cada uno de los reportes solicitados.

"""

import sys
RUTA_SRC = "/content/TP1_Grupo28_Seminario_Actualizacion_I/book_manager/src"
if RUTA_SRC not in sys.path:
    sys.path.insert(0, RUTA_SRC)

from book_manager.main import main
main(import_default_data=False)

"""## Visualizar la rama actual

"""

!git status

"""## Visualizar el contenido de cada commit

"""

!git --no-pager log --name-status Sprint_1

"""## Muestra del código fuente

"""

from IPython.display import display, HTML, Code
import os

display(HTML("""
<style>
  .jp-RenderedText pre, .jp-RenderedHTMLCommon pre, .p-Widget pre {
    background-color: #1e1e1e !important;
    color: #d4d4d4 !important;
    border: 1px solid #FFF !important;
  }
  .highlight  { background: #1e1e1e !important; }
  .highlight pre { border: 2px solid !important; }
</style>
"""))
!rm -rf /content/sample_data .config
def visualizar_archivos_dark(directorio):
    for raiz, _, archivos in os.walk(directorio):
      if raiz.lower().endswith(('.git','.dvc', '__pycache__')):
        continue
      for nombre in archivos:
        if nombre.lower().endswith(('.py')):
          ruta = os.path.join(raiz, nombre)
          print(f"📁 {ruta}")
          with open(ruta, 'r') as f:
              contenido = f.read()
          display(Code(contenido, language=nombre.split('.')[-1]))
        if nombre.lower().endswith(('.md', '.csv', '.env', '.sql', '.txt', '.json')):
          ruta = os.path.join(raiz, nombre)
          print(f"📁 {ruta}")
          with open(ruta, 'r') as f:
              contenido = f.read()
          print("".join(contenido))
          print("\n\n")

visualizar_archivos_dark('/content/')