# -*- coding: utf-8 -*-
"""Semana_01-05_variables.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1woxh041Aav_F-qFqKi7BujGXPh8uYNzR

# Nombrando variables
Puedes nombrar a tus variables como quieras, pero es importante saber que las mayúsculas y minúsculas son importantes. Las variables `x` y `X` son distintas.

Por otro lado existen ciertas normas a la hora de nombrar variables:

* El nombre no puede empezar por un número
* No se permite el uso de guiones -
* Tampoco se permite el uso de espacios.

Se muestran unos ejemplos de nombres de variables válidos y no válidos.
"""

import traceback

# Válido
_variable = 10
vari_able = 20
variable10 = 30
variable = 60
variaBle = 10

## No válido, cualquiera de estas definiciones generan un error de SyntaxError
## descomentar para verificar
#2variable = 10
#var-iable = 10
#var iable = 10

"""Una última condición para nombrar a una variable en Python, es no usar nombres reservados para Python. Las palabras reservadas son utilizadas por Python internamente, por lo que no podemos usarlas para nuestras variables o funciones.

Más adelante veremos cuales son todas estas palabras.

## Creando variables
Anteriormente ya hemos visto como crear una variable y asignarle un valor con el uso de `=`. Existen también otras formas de hacerlo de una manera un poco más sofisticada.

Podemos por ejemplo asignar el mismo valor a diferentes variables con el siguiente código.
"""

x = y = z = 10

"""O también podemos asignar varios valores separados por coma."""

x, y = 4, 2
x, y, z = 1, 2, 3

"""## Tipos de escritura

Existen varias formas de escrituras para los nombres de variables, funciones o clases.

Vamos a suponer que queremos llamar a una variable utilizando las siguientes palabras `aumentar nivel dificultad`

### Camel Case

La primer letra se escribe en minúscula y luego el comienzo de cada palabra se pasa a mayúscula.

Para este caso la variable se llamaría `aumentarNivelDificultad`

### Pascal Case

El comienzo de cada palabra se pasa a mayúscula.

Para este caso la variable se llamaría `AumentarNivelDificultad`

### Kebab Case

Las palabras son separadas por un guión medio.

Para este caso la variable se llamaría `aumentar-nivel-dificultad`

### Snake Case

Las palabras son separadas por un guión bajo.

Para este caso la variable se llamaría `aumentar_nivel_dificultad`

`IMPORTANTE: Este es el utilizado en Python.`
"""