# -*- coding: utf-8 -*-
"""Semana_01-04_print.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nDsZBxKYVEWscp9NaYbKc756RPpr1q9A

# Función print

Función para mostrar datos por pantalla. Puede recibir uno o varios argumentos/parámetros, los cuales se pasan dentro de paréntesis.

Tiene la particularidad en imprimir cualquier tipo de dato siempre y cuando tenga implementada la función o método `__str__`. Más adelante vamos a ampliar sobre este tema.

Muestra el valor `123`
"""

print(123)

"""Muestra un línea en blanco. Está escribiendo una nueva línea."""

print()

"""Vamos a crear una variable, asignandole un valor por defecto para luego imprimer el valor."""

variale_string = 'a'
print(variale_string)

"""Una función muy importante es `type` la cual se encarga de mostrar el tipo de dato de una variable.

En este caso vamos a mostrar el tipo de la variable `variable_string`
"""

print(type(variale_string))

"""## Caracter de escape \
Curiosamente, mietras tu ves dos caracteres, Python ve solo uno.
La barra invertida `\` tiene un significado muy especial cuando se usa dentro de las cadenas de carácteres o strings y es llamado caracter de escape.

La palabra escape debe entenderse claramente, significa que la serie de caracteres en la cadena se escapa(detiene) por un momento(un momento muy corto) para introducir una inclusión especial.

En otras palabras, la barra invertida no sifnifca nada, sino que es solo un tipo de anuncio, de que el siguiente caracter después de la barra invertida también tiene un significado diferente.

`Importante: El caracter de escape funciona tanto con la comilla simple como con la comilla doble`

En el siguiente ejemplo vamos a escapar una comilla doble `"` dentro de un string para que podamos imprimirla por pantalla.
"""

print("utilizando el caracter de escape, puedo printear una \", efectivamente, no hay errores")

"""En el siguiente ejemplo vamos a escapar una comilla simple `'` dentro de un string para que podamos imprimirla por pantalla."""

print('utilizando el caracter de escape, puedo printear una \', efectivamente, no hay errores')

"""Si quiero evitar el uso del caracter de escape en la definición de string puedo invertir las comillas."""

print('utilizando el caracter de escape, puedo printear una ", efectivamente, no hay errores')

"""### Nueva línea

Para escribir una nueva línea podemos utilizar la siguiente cadena `\n`


"""

print("hola mundo,\ncomo va?")

"""### Sangría

Para escribir una sangría podemos utilizar la siguiente cadena `\t`
"""

print('Hola mundo, \t como va?')

"""Combinamos la sangría y la nueva línea"""

print('Hola mundo,\n\tcomo va?')

"""## Argumentos múltiples

A la función print le podemos pasar todos los argumentos que deseemos y estos pueden ser de diferentes tipos. La función se encarga de mostrarlo de forma correcta.
"""

print("argumento 1", "argumento 2", "valor entero igual a", 3., "siempre separarlos con comas!!")

"""## Argumentos de palabras clave

* sep, es el argumento de separación de argumentos y por defecto en un espacio en blanco.
* end, es el argumento de nuevas líneas y por defecto es una nueva línea.

Utilizando los valores de `sep` por defecto.
"""

print("Hola", "mundo", "!")

"""Cambiando el valor de sep por un cardinal"""

print("Hola", "mundo", "!", sep= '#')

"""Utilizando el valor de `end` por defecto."""

print("Hola", "mundo")
print("!")

"""Cambiando el valor de end por un vacio."""

print("Hola", "mundo", end='')
print("!")

"""# input

La función `input` se utiliza para obtener datos. El dispositivo externo que que realiza la entrada es el teclado.

La salida de esta función la debemos almacenar en alguna variable para no perder la información.

`IMPORTANTE: La salida es un string`
"""

print("Dime algo: ")
algo = input()
print(f"Mmm... {algo} ...¿en serio?")

"""Está función recibe como parámetro un prompt o mensaje que se mostrará por pantalla, de esta forma no evitamos utilizar la llamada a la función print."""

algo = input("Dime algo: ")
print(f"Mmm... {algo} ...¿En serio?")

"""# Función help

La función help es la encargada de brindarnos ayuda sobre las funciones.

Nos mostrará una descripción de su funcionamiento, nos explicará los argumentos de entrada y la salida.
"""

import random

help(random.randint)