# -*- coding: utf-8 -*-
"""Semana_01-06_palabras_reservadas.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hk8qtFGNtYVJY0rlVhyHbSs8XiXjINcR

# Palabras reservadas en Python

Python tiene un conjunto de palabras reservadas que no podemos utilizar para nombrar variables ni funciones, ya que las reserva internamente para su funcionamiento.

Por ejemplo, no podemos llamar a una función `True`, y si intentamos hacerlo, tendremos un SyntaxError. Esto es lógico ya que Python usa internamente `True` para representar el tipo booleano.
"""

import traceback

## No válido, cualquiera de estas definiciones generan un error de SyntaxError
## descomentar para verificar
#def True():
#  pass

"""
Análogamente, no podemos llamar a una variable `is` ya que se trata del operador de identidad.
"""

## No válido, cualquiera de estas definiciones generan un error de SyntaxError
## descomentar para verificar
#is = 4

"""Resulta lógico que no se nos permita realizar esto, ya que de ser posible, podríamos romper el lenguaje. Algo muy importante a tener en cuenta es que palabras como list no están reservadas, y esto es algo que puede generar problemas. El siguiente código crea una lista usando la función estándar de Python `list()`.

"""

lista = list("letras")
print(f"La lista contiene: \n", lista)

"""Sin embargo, y aunque pueda parece extraño, podemos crear una función con ese nombre. Al hacer esto, estamos sobre escribiendo la función list() de Python, y por lo tanto al intentar hacer la llamada anterior falla, ya que nuestra función en este caso no acepta argumentos. Mucho cuidado con esto."""

def list():
    print("Función list")

try:
  lista = list("letras")
  print(f"La lista contiene: \n", lista)
except Exception:
  print("Falla porque sobre escribimos la función list.")
  traceback.print_exc()

print("Al invocar la función sobre escrita obtendremos el mensaje 'Función list'")
list()

"""
Pero volviendo a las palabras reservadas, Python nos ofrece una forma de acceder a estas palabras programmatically, es decir, a través de código. Aquí tenemos un listado con todas las palabras reservadas.
"""

import keyword
print(keyword.kwlist)

"""Vistas ya las palabras reservadas de Python, a continuación explicaremos para que sirve cada una de ellas y las pondremos en contexto.

## Funciones: def, return, lambda, pass, yield
Todas estas palabras están relacionadas con las funciones. El uso de `def` nos permite crear una función.

Una función (también conocida como método o procedimiento) es un bloque de código que realiza una tarea específica y puede ser llamada varias veces desde diferentes partes del programa.

Las funciones tienen varios propósitos clave:
- Reutilización: Las funciones permiten reutilizar código para realizar tareas similares en diferentes partes del programa, lo que reduce la duplicación y facilita la mantenibilidad.
- Modularidad: Las funciones dividen el código en módulos autónomos, lo que facilita la comprensión y el mantenimiento del programa.
- Encapsulación: Las funciones pueden encapsular datos y lógica relacionados con una tarea específica, lo que ayuda a mantener la integridad y la consistencia del programa.

Una función típica tiene los siguientes componentes:
- Nombre: Un identificador único que se utiliza para llamar a la función.
- Parámetros o Argumentos: Variables que se pasan como entrada a la función, que pueden ser utilizados para realizar la tarea.
- Cuerpo: El bloque de código que se ejecuta cuando se llama a la función.
- Return: La función puede devolver un valor o resultado después de ejecutarse.
"""

def funcion_suma(a, b):
    print("La suma es", a + b)

funcion_suma(3, 5)

"""Si queremos que la función devuelva uno o varios valores, podemos usar return.

"""

def funcion_suma(a, b):
    return a + b

suma = funcion_suma(3, 5)
print("La suma es", suma)

"""El uso de `lambda` nos permite crear funciones lambda, una especie de funciones “para vagos”. Dichas funciones no tienen un nombre per se, salvo asignado explícitamente."""

print("La suma es", (lambda a, b: a + b)(3, 5))

"""Por otro lado, podemos usar `pass` cuando no queramos definir la función, es decir si la queremos dejar en blanco por el momento. Nótese que también puede ser usado en clases, estructuras de control, etc.

"""

def funcion_suma(a, b):
    pass

"""Por último, `yield` está asociado a los generadores y las corrutinas, un concepto un tanto avanzado pero muy interesante. En el siguiente generador vemos como se generan tres valores, obteniendo uno cada vez que iteramos el generador.


"""

def generador():
    n = 1
    yield n

    n += 1
    yield n

    n += 1
    yield n

for i in generador():
    print(i)

"""Los generadores pueden ser usados para generar secuencias infinitas de valores, sin que tengan que ser almacenados a priori, siendo creados bajo demanda. Este es una utilidad muy importante trabajando con listas muy grandes, cuyo almacenamiento en memoria sería muy costoso.

## Clases: class
El uso de `class` nos permite crear clases. Las clases son el núcleo de la programación orientada objetos, y son una especie de estructura de datos que agrupa un conjunto de funciones (métodos) y variables (atributos).
"""

class MiClase:
    def __init__(self):
        print("Creando objeto de MiClase")

objeto = MiClase()

"""## Excepciones: assert, try, except, finally, raise
Las palabras clave `assert`, `try`, `except`, `finally` y `raise` están relacionadas con las excepciones, y nos permiten tratar el qué hacer cuando las cosas no salen como esperamos. El siguiente código intenta hacer un cast de cadena a entero, manejando un posible error.

* Si x="10" el casteo se realiza sin problemas, ya que es posible representar esa cadena como un entero. Sin embargo hay que estar preparados siempre para lo peor.
* Si x="a" no se podría hacer int() y tendríamos un error. Si no manejamos este error, el programa se pararía, y esto no es algo deseable. El uso de try, except y finally nos permite controlar dicho error y actuar en consecuencia sin que el programa se pare.

"""

x = "10"

valor = None
try:
    valor = int(x)
except Exception as e:
    print("Hubo un error:", e)
finally:
    print("El valor es", valor)

"""## Variables: global, nonlocal
El uso de `global` permite realizar lo siguiente, y de no usarlo tendríamos un UnboundLocalError. Aunque puede resultar muy útil, mucho cuidado con las variables globales.

"""

a = 0

def suma_uno():
    global a
    a = a + 1

suma_uno()
print('La salida es uno porque se modifica dentro de la función: ', a)

"""El uso de `nonlocal` es útil cuando tenemos funciones anidadas. El el siguiente ejemplo podemos ver como cuando funcion_b modifica x, también afecta a la x de la funcion_a, ya que la hemos declarado como `nonlocal`. Te invito a que elimines el `nonlocal` y veas el comportamiento.

"""

def funcion_a():
    x = 10

    def funcion_b():
        nonlocal x
        x = 20
        print("funcion_b", x)

    funcion_b()
    print("funcion_a", x)

funcion_a()

"""## Módulos: from, import
El uso de `from` e `import` nos permite importar módulos o librerías, tanto estándar de Python como externas o definidas por nosotros. En ejemplos como este es donde podemos ver que la sintaxis de Python se asemeja bastante al lenguaje natural. Por ejemplo: `de collections importa namedtuple`.

"""

from collections import namedtuple

"""## Pertenencia e Identidad: in, is
El uso de `in` nos permite saber si un determinado elemento está en una clase iterable, devolviendo `True` en el caso de que sea cierto.

"""

lista = ["a", "b", "c"]
print("a" in lista)

"""El uso de `is` nos permite saber si dos variables apuntan en realidad al mismo objeto. Por debajo se usa la función `id()` y es importante notar que la igualdad `==` no implica que `is` sea `True`.

"""

a = [1, 2]
b = [1, 2]
c = a

print('a is b: ', a is b)
print('a is c: ', a is c)

"""## Eliminar variables: del
El uso de `del` nos permite eliminar una variable del scope, pudiendo resultar útil cuando trabajamos con variables que almacenan gran cantidad de datos. Es una manera explícita de indicar que ya no queremos una variable, pero no olvidemos que Python tiene gargabe collector.

"""

a = 10
del a
try:
  print(a)
except Exception:
  traceback.print_exc()

"""## Context Managers: with, as
El uso de `with` y `as` es muy utilizado a la hora de manejar ficheros, pero en realidad pertenecen a los context managers o gestores de contexto, un concepto algo avanzado.

"""

# Commented out IPython magic to ensure Python compatibility.
# %%writefile fichero.txt
# Creamos un fichero de pruebas

with open('fichero.txt', 'r') as file:
    print(file.read())

"""## Concurrencia: async, await
El uso de `async` y `await` nos permite ejecutar procesos de manera concurrente en vez de secuencial. Imaginemos un proceso() que tarda 10 segundos en ejecutarse, ya que realiza una petición a una base de datos que lo bloquea durante ese tiempo. Sin esta herramienta, si quisiéramos ejecutar 3 veces el proceso tardaríamos 30 segundos, ya que por defecto se ejecutan de manera secuencial, hasta que uno no acaba no pasamos al siguiente.

Sin embargo, creando una función `async` y usando `await`, podemos paralelizar la ejecución de los procesos, aprovechando el tiempo “muerto” mientras se retorna al await. En el siguiente ejemplo podemos ver como se tarda unos 10 segundos en ejecutar los 3 procesos.

"""

import asyncio
import nest_asyncio
import random

nest_asyncio.apply()

async def proceso(id_proceso):
    print("Empieza proceso: ", id_proceso)
    if id_proceso % 3 == 0:
      # solo se penalizan los procesos múltiplos de 3
      print("El proceso ", id_proceso, " es penalizado con 10 segundos de timeout")
      await asyncio.sleep(10)
    print("\tAcaba proceso: ", id_proceso, '\n')

async def main():
    await asyncio.gather(*[proceso(i) for i in range(0,10)])

asyncio.run(main())