# -*- coding: utf-8 -*-
"""Semana_01-01_que_es_python.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/121RiZjqIHpW6-bh3DbyMk0Fox-4oGO7L

# Introducción

##  ¿Qué es Python?

Como veremos, Python es utilizado en aplicaciones como lo son el análisis de datos, automatización de tareas, web scraping, machine learning, data science, desarrollo de videojuegos, interfaces gráficos o finanzas.

A diferencia de lo que mucha gente puede pensar, Python es un lenguaje que data de los años 1990s, y su creación se le atribuye al neerlandés Guido van Rossum. Recibió su nombre por los humoristas Monty Python.

Su última versión es Python 3, y es la que te recomendamos usar ya que las anteriores ya no tienen soporte oficial.

Estos son los motivos por lo que ha crecido tanto y lo seguirá haciendo:

* Se trata de un lenguaje fácil de aprender, con una sintaxis muy sencilla que se asemeja bastante al pseudocódigo. En otras palabras, poco código hace mucho.
* Su uso no está ligado a un sector concreto. Por ejemplo el lenguaje R es útil para análisis de datos, pero no puede ser usado para desarrollo web. Python vale para todo.
* Tiene una comunidad enorme, además de gran cantidad de librerías para hacer prácticamente cualquier cosa, literalmente.
* Es un lenguaje multiplataforma, por lo que el mismo código es compatible en cualquier plataforma (Windows, macOS, Linux) sin hacer nada.
* Por lo general se puede hacer desarrollos en Python más rápidamente que en otros lenguajes, acortando la duración de los proyectos.

## Usos de Python

Python es un lenguaje muy transversal, usado en diferentes industrias y para diferentes fines. Algunas de las empresas que usan Python:

* YouTube usa Python en la parte del servidor, unida a otros lenguajes como Java o Go.
* Netflix usa Python par automatizar tareas, explorar datos y labores de aprendizaje automático entre otras.
* La NASA usa Python en gran cantidad de programas científicos.
* JPMorgan ya dijo hace varios años que se esperaba de sus analistas financieros supieran Python.

También es utilizado para fines muy diversos como son los siguientes:

* Desarrollo Web: Existen frameworks como Django, Pyramid, Flask, FastAPI o Bottle que permiten desarrollar páginas web a todos los niveles.
* Ciencia y Educación: Debido a su sintaxis tan sencilla, es una herramienta perfecta para enseñar conceptos de programación a todos los niveles. En lo relativo a ciencia y cálculo numérico, existen gran cantidad de librerías como SciPy o Pandas.
* Desarrollo de Interfaces Gráficos: Gran cantidad de los programas que utilizamos tienen un interfaz gráfico que facilita su uso. Python también puede ser usado para desarrollar GUIs con librerías como Kivy o pyqt.
* Desarrollo Software: También es usado como soporte para desarrolladores, como para testing.
* Machine Learning: En los último años ha crecido el número de implementaciones en Python de librerías de aprendizaje automático como Keras, TensorFlow, PyTorch o sklearn.
* Visualización de Datos: Existen varias librerías muy usadas para mostrar datos en gráficas, como matplotlib, seaborn o plotly.
* Finanzas y Trading: Gracias a librerías como QuantLib o qtpylib y a su facilidad de uso, es cada vez más usado en estos sectores.

De hecho a día de hoy prácticamente cualquier API, librería o servicio que existe en el mundo tiene una versión para Python, bien sea de manera nativa o a través de un wrapper.

## Comunidad
La comunidad de Python es inmensa, una cifra que supera ya a los usuarios de Java (a fecha de 2024).

Es importante el tamaño de la comunidad, porque cuanto más grande sea, mayor soporte se le dará al lenguaje y mayor número de personas compartirán sus problemas y se ayudarán a resolverlos.

Otra de las características de la comunidad Python son las famosas PyCon, unas convenciones anuales llevadas a cabo en gran número de países, donde los desarrolladores se reúnen para compartir ideas.


Es también importante mencionar la Python Software Foundation, una organización sin ánimo de lucro que se dedica a promover, proteger y desarrollar el lenguaje Python.

## Características de Python

Como cualquier otro lenguaje, Python tiene una serie de características que lo hacen diferente al resto. Las explicamos a continuación:

* Es un lenguaje interpretado, no compilado.
* Usa tipado dinámico, lo que significa que una variable puede tomar valores de distinto tipo.
* Es fuertemente tipado, lo que significa que el tipo no cambia de manera repentina. Para que se produzca un cambio de tipo tiene que hacer una conversión explícita.
* Es multiplataforma, ya que un código escrito en macOS funciona en Windows o Linux y vice versa.

Tal vez algunos de estos conceptos puedan resultarte extraños si estás empezando en el mundo de la programación. El siguiente código pretende ilustrar algunas de las características de Python.

Algunas curiosidades que en otros lenguajes no pasan. La función acepta un parámetro entrada pero no se especifica su tipo. La x almacena primero una cadena de caracteres, luego un decimal y luego un entero. La función funcion() es llamada con un entero, pero su valor se divide entre 2 y el resultado es convertido automáticamente en un decimal.

```
def funcion(entrada):
    return entrada/2
    
x = "Hola"
x = 7.0
x = int(x)
x = funcion(x)
print(x)
print(type(x))

# 3.5
# <class 'float'>
```

Definimos la función.
"""

def funcion(entrada):
  """ Función de muestra.

  Args:
    entrada (object): Variable de entrada.

  Returns:
    float: Retorna el valor de la entrada dividido entre 2.
  """
  return entrada/2

"""Asignamos una cadena de caracteres a la variable x y mostramos su tipo."""

x = "Hola"
print(f"Mostramos el valor de la variable x: {x}")
print(f"Mostramos el typo de la variable x: {type(x)}")

"""Asignamos un decimal a la variable x, es decir, le cambiamos el tipo.

Mostramos el valor almacenado y su tipo.
"""

x = 7.0
print(f"Mostramos el valor de la variable x: {x}")
print(f"Mostramos el typo de la variable x: {type(x)}")

"""Asignamos un entero a la variable x, es decir, le cambiamos el tipo.

Mostramos el valor almacenado y su tipo.
"""

x = int(x)
print(f"Mostramos el valor de la variable x: {x}")
print(f"Mostramos el typo de la variable x: {type(x)}")

"""Ejecutamos la función que declarmos más arriba y vemos que nos devuelve.

Mostramos el resultado y su tipo.
"""

print(f"Mostramos el valor original de la variable x: {x}")
x = funcion(x)
print(f"Mostramos el valor de la variable x luego de la ejecución de la función: {x}")
print(f"Mostramos el typo de la variable x: {type(x)}")

"""## The Zen of Python
El Zen de Python es una colección de los 19 principios que influyen en el diseño del lenguaje. De alguna manera, muestran la filosofía del mismo y pueden ser encontrados en la [PEP20](https://peps.python.org/pep-0020/). Las [PEP](https://peps.python.org/) o Python Enhancement Prososals son unos documentos que ofrecen información a la comunidad de Python, bien describiendo alguna característica nueva o dando información en general.

Son las siguientes, y aunque alguna pueda parecer lógica, a veces resultan no serlo tanto cuando no se cumplen:

1. Bello es mejor que feo (Beautiful is better than ugly).
2. Explícito es mejor que implícito (Explicit is better than implicit).
3. Simple es mejor que complejo (Simple is better than complex).
4. Complejo es mejor que complicado (Complex is better than complicated).
6. Plano es mejor que anidado (Flat is better than nested).
7. Espaciado es mejor que denso (Sparse is better than dense).
7. La legibilidad es importante (Readability counts).
8. Los casos especiales no son lo suficientemente especiales como para romper las reglas (Special cases aren't special enough to break the rules).
9. Sin embargo la practicidad gana a la pureza (Although practicality beats purity).
10. Los errores nunca deben pasar silenciosamente (Errors should never pass silently).
11. A menos que se silencien explícitamente (Unless explicitly silenced).
12. Frente a la ambigüedad, evitar la tentación de adivinar (In the face of ambiguity, refuse the temptation to guess).
13. Debería haber una, y preferiblemente solo una, manera obvia de hacerlo (There should be one -- and preferably only one -- obvious way to do it).
14. A pesar de que esa manera no sea obvia a menos que seas Holandés (Although that way may not be obvious at first unless you're Dutch).
15. Ahora es mejor que nunca (Now is better than never).
16. A pesar de que nunca es muchas veces mejor que ahora mismo (Although never is often better than *right* now).
17. Si la implementación es difícil de explicar, es una mala idea (If the implementation is hard to explain, it's a bad idea).
18. Si la implementación es fácil de explicar, puede que sea una buena idea (If the implementation is easy to explain, it may be a good idea).
19. Los namespaces son una gran idea, ¡tengamos más de esos! (Namespaces are one honking great idea -- let's do more of those!)
"""