# -*- coding: utf-8 -*-
"""Semana_01-08_Modulos.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1o6oruq6YPOQxNm9RapG9C-38qgb1_guU

# Módulos y scripts en Python

## Script

En programación, un script es un archivo de código fuente con instrucciones sencillas, que puede ser ejecutado a través de la línea de comandos.

## Módulo

Un módulo o module en Python es un fichero .py que alberga un conjunto de funciones, variables o clases y que puede ser usado por otros módulos. Nos permiten reutilizar código y organizarlo mejor en namespaces. Por ejemplo, podemos definir un módulo mimodulo.py con dos funciones suma() y resta().
"""

# Commented out IPython magic to ensure Python compatibility.
# %%writefile mimodulo.py
# def suma(valor_1:int, valor_2:int) -> int:
#     """ Función que suma dos valores enteros
# 
#     Args:
#         valor_1 (int): Primer valor a sumar
#         valor_2 (int): Segundo valor a sumar
# 
#     Returns:
#         int: Suma de los dos valores
#     """
#     return valor_1 + valor_2
# 
# def resta(valor_1:int, valor_2:int) -> int:
#     """ Función que resta dos valores enteros
# 
#     Args:
#         valor_1 (int): Primer valor a restar
#         valor_2 (int): Segundo valor a restar
# 
#     Returns:
#         int: Resta de los dos valores
#     """
#     return valor_1 - valor_2

"""Una vez definido, dicho módulo puede ser usado o importado en otro fichero, como mostramos a continuación. Usando import podemos importar todo el contenido."""

# otromodulo.py
import mimodulo
valor_1:int = 10
valor_2:int = 5

print(f'El resultado de sumar {valor_1} + {valor_2} es: {mimodulo.suma(valor_1, valor_2)}')
print(f'El resultado de restar {valor_1} - {valor_2} es: {mimodulo.resta(valor_1, valor_2)}')

"""También podemos importar únicamente los componentes que nos interesen como mostramos a continuación."""

from mimodulo import suma, resta

print(f'El resultado de sumar {valor_1} + {valor_2} es: {suma(valor_1, valor_2)}')
print(f'El resultado de restar {valor_1} - {valor_2} es: {resta(valor_1, valor_2)}')

"""Por último, podemos importar todo el módulo haciendo uso de \*, sin necesidad de usar mimodulo.\*.


"""

from mimodulo import *

print(f'El resultado de sumar {valor_1} + {valor_2} es: {suma(valor_1, valor_2)}')
print(f'El resultado de restar {valor_1} - {valor_2} es: {resta(valor_1, valor_2)}')

"""## Rutas y Uso de sys.path
Normalmente los módulos que importamos están en la misma carpeta, pero es posible acceder también a módulos ubicados en una subcarpeta. Imaginemos la siguiente estructura:
```
.
├── ejemplo.py
├── carpeta
│   └── modulo.py
```

Donde modulo.py contiene lo siguiente:
"""

!mkdir carpeta

# Commented out IPython magic to ensure Python compatibility.
# %%writefile carpeta/modulo.py
# def hola():
# 	print("Hola")

"""Desde nuestro ejemplo.py, podemos importar el módulo modulo.py de la siguiente manera:


"""

from carpeta.modulo import *
hola()

"""Es importante notar que Python busca los módulos en las rutas indicadas por el sys.path. Es decir, cuando se importa un módulo, lo intenta buscar en dichas carpetas. Puedes ver tu sys.path de la siguiente manera:"""

import sys
print(sys.path)

"""Como es obvio, verás que la carpeta de tu proyecta está incluida, pero ¿y si queremos importar un módulo en una ubicación distinta? Pues bien, podemos añadir al sys.path la ruta en la que queremos que Python busque."""

import sys
sys.path.append(r'/ruta/de/tu/modulo')

"""Una vez realizado esto, los módulos contenidos en dicha carpeta podrán ser importados sin problema como hemos visto anteriormente.

## Cambiando los Nombres con as
Por otro lado, es posible cambiar el nombre del módulo usando as. Imaginemos que tenemos un módulo moduloconnombrelargo.py.
"""

# Commented out IPython magic to ensure Python compatibility.
# %%writefile moduloconnombrelargo.py
# hola = "hola"

"""En vez de usar el siguiente import, tal vez queramos asignar un nombre más corto al módulo.


"""

import moduloconnombrelargo
print(moduloconnombrelargo.hola)

"""Podemos hacerlo de la siguiente manera con as:


"""

import moduloconnombrelargo as m
print(m.hola)

"""## Listando dir

La función dir() nos permite ver los nombres (variables, funciones, clases, etc) existentes en nuestro namespace. Si probamos en un módulo vacío, podemos ver como tenemos varios nombres rodeados de \_\_. Se trata de nombres que Python crea por debajo.
"""

def mostrar_funcion_dir_format(dir_list:list):
    """ Función que muestra la salida de la función dir. """
    output = ""
    for i, name in enumerate(dir_list):
      output += name
      if i > 0 and i % 5 == 0:
        output += "\n"
      else:
        output += ", "
    print(output)

mostrar_funcion_dir_format(dir())

"""Por ejemplo, __file__ es creado automáticamente y alberga el nombre del fichero .py."""

# Commented out IPython magic to ensure Python compatibility.
# %%writefile carpeta/mifichero.py
# print(__file__)

!python carpeta/mifichero.py

"""Imaginemos ahora que tenemos alguna variable y función definida en nuestro script. Como era de esperar, dir() ahora nos muestra también los nuevos nombres que hemos creado, y que por supuesto pueden ser usados."""

mi_variable = "Python"
def mi_funcion():
    pass

mostrar_funcion_dir_format(dir())

"""Por último, vamos a importar el contenido de un módulo externo. Podemos ver que en el namespace tenemos también los nombres resta y suma, que han sido tomados de mimodulo."""

from mimodulo import *
mostrar_funcion_dir_format(dir())

"""El uso de dir() también acepta parámetros de entrada, por lo que podemos por ejemplo pasar nuestro modulo y nos dará más información sobre lo que contiene."""

import mimodulo

mostrar_funcion_dir_format(dir(mimodulo))

print(mimodulo.__name__)

print(mimodulo.__file__)

"""## Excepción ImportError
Importar un módulo puede lanzar una excepción, cuando se intenta importar un módulo que no ha sido encontrado. Se trata de ModuleNotFoundError.
"""

import moduloquenoexiste
# ModuleNotFoundError: No module named 'moduloquenoexiste'

"""Dicha excepción puede ser capturada para evitar la interrupción del programa."""

try:
    import moduloquenoexiste
except ModuleNotFoundError as e:
    print("Hubo un error:", e)

"""## Módulos y Función Main
Un problema muy recurrente es cuando creamos un módulo con una función como en el siguiente ejemplo, y añadimos algunas sentencias a ejecutar.
"""

# Commented out IPython magic to ensure Python compatibility.
# %%writefile modulo.py
# 
# def suma(valor_1:int, valor_2:int) -> int:
#     """ Función que suma dos valores enteros
# 
#     Args:
#         valor_1 (int): Primer valor a sumar
#         valor_2 (int): Segundo valor a sumar
# 
#     Returns:
#         int: Suma de los dos valores
#     """
#     return valor_1 + valor_2
# 
# c = suma(1, 2)
# print("La suma es:", c)

"""Si en otro módulo importamos nuestro modulo.py, tal como está nuestro código el contenido se ejecutará, y esto puede no ser lo que queramos."""

# otromodulo.py
import modulo

## al realizar un import de todo el módulo se ejecuta la asignación de c y el print

from modulo import suma
suma(2,2)

## al importar solo la función de suma, NO se ejecuta la asignación de c y el print

"""Dependiendo de la situación, puede ser importante especificar que únicamente queremos que se ejecute el código si el módulo es el __main__. Con la siguiente modificación, si hacemos import modulo desde otro módulo, este fragmento ya no se ejecutará al ser el módulo main otro."""

# Commented out IPython magic to ensure Python compatibility.
# # modulo.py
# %%writefile modulo.py
# 
# def suma(valor_1:int, valor_2:int) -> int:
#     """ Función que suma dos valores enteros
# 
#     Args:
#         valor_1 (int): Primer valor a sumar
#         valor_2 (int): Segundo valor a sumar
# 
#     Returns:
#         int: Suma de los dos valores
#     """
#     return valor_1 + valor_2
# 
# if (__name__ == '__main__'):
#     c = suma(1, 2)
#     print("La suma es:", c)

import modulo

!python modulo.py

"""## Recargando Módulos
Es importante notar que los módulos solamente son cargados una vez. Es decir, no importa el número de veces que llamemos a import mimodulo, que sólo se importará una vez.

Imaginemos que tenemos el siguiente módulo que imprime el siguiente contenido cuando es importado.
"""

# Commented out IPython magic to ensure Python compatibility.
# %%writefile mimodulo1.py
# 
# print("Importando mimodulo")
# 
# def suma(valor_1:int, valor_2:int) -> int:
#     """ Función que suma dos valores enteros
# 
#     Args:
#         valor_1 (int): Primer valor a sumar
#         valor_2 (int): Segundo valor a sumar
# 
#     Returns:
#         int: Suma de los dos valores
#     """
#     return valor_1 + valor_2
# 
# def resta(valor_1:int, valor_2:int) -> int:
#     """ Función que resta dos valores enteros
# 
#     Args:
#         valor_1 (int): Primer valor a restar
#         valor_2 (int): Segundo valor a restar
# 
#     Returns:
#         int: Resta de los dos valores
#     """
#     return valor_1 - valor_2

"""A pesar de que llamamos tres veces al import, sólo vemos una única vez el contenido del print."""

import mimodulo1
import mimodulo1
import mimodulo1

"""Si queremos que el módulo sea recargado, tenemos que ser explícitos, haciendo uso de reload."""

import mimodulo1
import importlib
importlib.reload(mimodulo1)
importlib.reload(mimodulo1)

