# -*- coding: utf-8 -*-
"""Semana_04-Practica_04.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JwpRoVS8lU1OTDic-oufTaqbA0bUcSb8

`IMPORTANTE: Los datos deben ser ingresados por el usuario, no pueden ser fijos en variables.`

# Ejercicio 1

Escribir una función que calcule el área de un círculo.
"""



"""# Ejercicio 2

Escribir una función que determine si un número es par o impar.
"""



"""# Ejercicio 3

Escribir una función que calcule la distancia entre dos puntos cartesianos.

Ayuda: $d = \sqrt[2]{((x_2-x_1)^2 + (y_2-y_1)^2)}$
"""



"""# Ejercicio 4

Escribir una función que devuelva el valor máximo y su posición de una lista de números positivos. Se debe desarrollar la función que encuentra el máximo, no se puede utilizar `max`.
"""



"""# Ejercicio 5

Escribir una función que agregue un elemento a una lista. Luego de cada ingreso se debe mostrar la lista completa.
"""



"""# Ejercicio 6

Completa la función `e6_funcion` para que imprima la cantidad variables que recibe como parámetros.
"""

def e6_ingreso_dato(posicion:int) -> float:
  """ Ingreso de datos.

  Args:
    posicion (int): Contiene la posición que estoy ingresando.

  Returns:
    float: Retorna el valor ingresado.
  """
  return float(input(f'Ingrese el valor de la posición {posicion} (-1 corta el ingreso de datos): '))

def e6_ingreso_datos() -> list[float]:
  """ Ingresa datos hasta que se encuentra un -1.
  """
  lista:list[float] = []
  posicion = 1
  valor:float = e6_ingreso_dato(posicion=posicion)
  while valor != -1:
    lista.append(valor)
    posicion += 1
    valor = e6_ingreso_dato(posicion=posicion)
  return lista

def e6_funcion(*args:float):
  """ Función que muestra por pantalla la cantidad de valores que recibe.

  Args:
    args (float): Valores flotantes.
  """
  ### COMPLETAR

e6_funcion(*e6_ingreso_datos())

"""# Ejercicio 7

Escribir una función que calcule la suma de una cantidad variable de números. La función no puede recibir una lista y no se puede utilizar la función `sum`.
"""



"""# Ejercicio 8

Ejercutar el siguiente código con las siguientes secuencias y anotar que pasa en cada una.

Para cada secuencia responder:

> ¿Qué sucedió?

> Se mostraron los valores?

> Porqué?

> Comó lo podría solucionar?
"""

def e8_ingreso_dato(posicion:int, corte:str = '') -> float:
  """ Ingreso de datos.

  Args:
    posicion (int): Contiene la posición que estoy ingresando.
    corte (str): Contiene el mensaje de corte. Defaults to ''.

  Returns:
    float: Retorna el valor ingresado.
  """
  return float(input(f'Ingrese un número de la posición {posicion}{corte}: '))

def e8_ingreso_nombre(posicion:int) -> str:
  """ Ingreso de nombres de variables.

  Args:
    posicion (int): Contiene la posición que estoy ingresando.

  Returns:
    float: Retorna el nombre de una variable.
  """
  return input(f'Ingrese el nombre de la variable en la posición {posicion} (enter corta el ingreso de datos): ').strip()

def e8_ingreso_datos() -> list:
  """ Ingresa datos hasta que se encuentra un -1.
  """
  lista:list = []
  posicion = 1
  valor:float = e8_ingreso_dato(posicion=posicion, corte=' (-1 corta el ingreso de datos)')
  while valor != -1:
    lista.append(valor)
    posicion += 1
    valor = e8_ingreso_dato(posicion=posicion, corte=' (-1 corta el ingreso de datos)')
  return lista

def e8_ingreso_datos_nombre() -> dict:
  """ Ingresa datos hasta que se encuentra un -1.
  """
  diccionario:dict = {}
  posicion = 1
  variable:str = e8_ingreso_nombre(posicion=posicion)
  while variable != '':
    valor:float = e8_ingreso_dato(posicion=posicion)
    diccionario[variable] = valor
    posicion += 1
    variable = e8_ingreso_nombre(posicion=posicion)
  return diccionario

def e8_funcion(par_1, par_2, par_3):
  """ Función que recibe valores.

  Args:
    par_1: Parámetro 1.
    par_2: Parámetro 2.
    par_3: Parámetro 3.
  """
  print(f'par_1 = {par_1}')
  print(f'par_2 = {par_2}')
  print(f'par_3 = {par_3}')

"""### Secuencia 1

Ingresar los valores:

| Valor |
| --- |
| 5 |
| 8 |
| 1 |
| -1 |
"""

e8_funcion(*e8_ingreso_datos())

"""### Secuencia 2

Ingresar los valores:

| Valor |
| --- |
| 5 |
| 8 |
| -1 |
"""

e8_funcion(*e8_ingreso_datos())

"""### Secuencia 3

Ingresar los valores:

| Valor |
| --- |
| 5 |
| 8 |
| 1 |
| 3 |
| -1 |
"""

e8_funcion(*e8_ingreso_datos())

"""### Secuencia 4

Ingresar los valores:

| Variable | Valor |
| --- | --- |
| par_1 | 5 |
| par_2 | 8 |
| par_3 | 1 |
| vacio o persionar enter |  |
"""

e8_funcion(**e8_ingreso_datos_nombre())

"""### Secuencia 5

Ingresar los valores:

| Variable | Valor |
| --- | --- |
| par_1 | 5 |
| par_2 | 8 |
| vacio o persionar enter |  |
"""

e8_funcion(**e8_ingreso_datos_nombre())

"""### Secuencia 6

Ingresar los valores:

| Variable | Valor |
| --- | --- |
| par_1 | 5 |
| par_2 | 8 |
| par_3 | 1 |
| par_4 | 2 |
| vacio o persionar enter |  |
"""

e8_funcion(**e8_ingreso_datos_nombre())

"""### Secuencia 7

Ingresar los valores:

| Variable | Valor |
| --- | --- |
| par_1 | 5 |
| par_2 | 8 |
| par_4 | 1 |
| vacio o persionar enter |  |
"""

e8_funcion(**e8_ingreso_datos_nombre())