# -*- coding: utf-8 -*-
"""Semana_04-05_Lambda.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MOAe0NIMFzmwUg9npuHk8Rdry1xSAETB

## Funciones lambda
Las funciones `lambda` o anónimas son un tipo de funciones en Python que típicamente se definen en una línea y cuyo código a ejecutar suele ser pequeño.

Resulta complicado explicar las diferencias, y para que te hagas una idea de ello te dejamos con la siguiente cita sacada de la documentación oficial.

> “Python lambdas are only a shorthand notation if you’re too lazy to define a function.”

Lo que significa algo así como, “las funciones lambda son simplemente una versión acortada, que puedes usar si te da pereza escribir una función”

Vamos a ver un ejemplo con la función `suma`.

Primero vamos a escribir la función como lo haríamos normalmente.
"""

def suma(a, b):
    return a + b

"""Se podría expresar en forma de una función `lambda` de la siguiente manera.


"""

lambda a, b : a + b

"""La primera diferencia es que una función lambda no tiene un nombre, y por lo tanto salvo que sea asignada a una variable, es totalmente inútil.

Vamos a asignarla a una variable.
"""

suma_lambda = lambda a, b: a + b

"""Una vez que tenemos la función, es posible llamarla como si de una función normal se tratase.


"""

print('El resultado de ejecutar la función lambda es: ', suma_lambda(2, 4))

"""Si es una función que solo queremos usar una vez, tal vez no tenga sentido almacenarla en una variable. Es posible declarar la función y llamarla en la misma línea.

Nótese que la primer parte `(lambda a, b: a + b)` en la definición de la función y la segunda parte `(2, 4)` son los argumentos que recibe dicha función.
"""

print('El resultado de ejecutar la función lambda es: ', (lambda a, b: a + b)(2, 4))

"""## Ejemplos

Una función lambda puede ser la entrada a una función normal.

En este caso vamos a definir  `mi_funcion` que recibe como argumento una función `lambda` y `mi_funcion` retorna la ejecución de la función lambda.
"""

def mi_funcion(lambda_func):
    return lambda_func(2,4)

print('El resultado de ejecutar la función lambda es: ', mi_funcion(lambda a, b: a + b))

"""Y una función normal también puede ser la entrada de una función lambda. Nótese que son ejemplo didácticos y sin demasiada utilidad práctica per se."""

def mi_otra_funcion(a, b):
    return a + b

print('El resultado de ejecutar la función lambda es: ', (lambda a, b: mi_otra_funcion(a, b))(2, 4))

"""A pesar de que las funciones lambda tienen muchas limitaciones frente a las funciones normales, comparten gran cantidad de funcionalidades. Es posible tener argumentos con valor asignado por defecto."""

print('El resultado de ejecutar la función lambda es: ', (lambda a, b, c=3: a + b + c)(1, 2) )

"""También se pueden pasar los parámetros indicando su nombre.


"""

print('El resultado de ejecutar la función lambda es: ', (lambda a, b, c: a + b + c)(a=1, b=2, c=3))

"""Al igual que en las funciones se puede tener un número variable de argumentos haciendo uso de `*`, lo conocido como tuple unpacking.


"""

print('El resultado de ejecutar la función lambda es: ', (lambda *args: sum(args))(1, 2, 3))

"""Y si tenemos los parámetros de entrada almacenados en forma de key y value como si fuera un diccionario, también es posible llamar a la función."""

print('El resultado de ejecutar la función lambda es: ', (lambda **kwargs: sum(kwargs.values()))(a=1, b=2, c=3) )

"""Por último, es posible devolver más de un valor."""

x = lambda a, b: (b, a)
print('El resultado de ejecutar la función lambda es: ', x(3, 9))