# -*- coding: utf-8 -*-
"""Semana_04-Practica_04_resuelta.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1V_ldG2CRFXnPShaFdq2MB-2fg6d3oSX-

`IMPORTANTE: Los datos deben ser ingresados por el usuario, no pueden ser fijos en variables.`

# Ejercicio 1

Escribir una función que calcule el área de un círculo.
"""



#@title Solución

from math import pi

def e1_ingreso_dato() -> float:
  """ Ingreso de datos.

  Returns:
    float: Retorna el valor ingresado.
  """
  return float(input('Ingrese el radio: '))

def e1_calculo_area(radio:float) -> float:
  """ Cálculo del área.

  Args:
    radio (float): Contiene el valor del radio.

  Returns:
    float: Returna el área de un círculo.
  """
  return pi*pow(radio,2)

print(f'El área es: {e1_calculo_area(radio=e1_ingreso_dato()):.2f}')

"""# Ejercicio 2

Escribir una función que determine si un número es par o impar.
"""



#@title Solución


def e2_ingreso_dato() -> int:
  """ Ingreso de datos.

  Returns:
    int: Retorna el valor ingresado.
  """
  return int(input('Ingrese un número: '))

def e2_verificar_impar(numero:int) -> bool:
  """ Verifica si el número es par.

  Args:
    numero (int): Contiene el número a verificar.

  Returns:
    bool: Retorna True si el número es impar.
  """
  # NOTA: el módulo siempre devuelve los valores 0 o 1
  # RECORDAR: bool(0) es False
  #           bool(1) es True
  # EJEMPLO:
  #          numero = 4 -> 4 % 2 = 0 -> bool(0) -> False
  #          numero = 5 -> 5 % 2 = 1 -> bool(1) -> True
  return numero % 2

numero = e2_ingreso_dato()

print(f'El número {numero} es {"IMPAR" if e2_verificar_impar(numero=numero) else "PAR"}')

"""# Ejercicio 3

Escribir una función que calcule la distancia entre dos puntos cartesianos.

Ayuda: $d = \sqrt[2]{((x_2-x_1)^2 + (y_2-y_1)^2)}$
"""



#@title Solución

def e3_ingreso_dato(coordenada:str) -> float:
  """ Ingreso de datos.

  Returns:
    float: Retorna el valor ingresado.
  """
  return float(input(f'Ingrese la coordenada {coordenada}: '))

def e3_ingreso_punto() -> tuple[float,float]:
  """ Ingreso de los datos de un punto.

  Returns:
    tuple[float,float]: Retorna una tupla con los valores de las coordenadas.
      (x, y)
  """
  return e3_ingreso_dato(coordenada='x'),e3_ingreso_dato(coordenada='y')

def e3_calculo_distancia(punto_1:tuple[float,float],
                         punto_2:tuple[float,float]) -> float:
    """ Calcula la distancia entre 2 puntos.

    Args:
      punto_1 (tuple[float,float]): Contiene un tupla con las coordenadas (x, y).
      punto_2 (tuple[float,float]): Contiene un tupla con las coordenadas (x, y).

    Returns:
      float: Retorna el cálculo de la distancia entre los 2 puntos.
    """
    return pow(pow((punto_2[0] - punto_1[0]), 2)
              + pow((punto_2[1] - punto_1[1]), 2), .5)
punto_1:tuple[float,float] = e3_ingreso_punto()
punto_2:tuple[float,float] = e3_ingreso_punto()
print(f'La distancia entre los puntos {punto_1} y {punto_2} es {e3_calculo_distancia(punto_1=punto_1, punto_2=punto_2):.3f}')

"""# Ejercicio 4

Escribir una función que devuelva el valor máximo y su posición de una lista de números positivos. Se debe desarrollar la función que encuentra el máximo, no se puede utilizar `max`.
"""



#@title Solución
def e4_ingreso_dato(posicion:int) -> float:
  """ Ingreso de datos.

  Args:
    posicion (int): Contiene la posición que estoy ingresando.

  Returns:
    float: Retorna el valor ingresado.
  """
  return float(input(f'Ingrese el valor de la posición {posicion} (-1 corta el ingreso de datos): '))

def e4_ingreso_datos() -> list[float]:
  """ Ingresa datos hasta que se encuentra un -1.

  Returns:
    list[float]: Retorna una lista de flotantes.
  """
  lista:list[float] = []
  posicion = 1
  valor:float = e4_ingreso_dato(posicion=posicion)
  while valor != -1:
    lista.append(valor)
    posicion += 1
    valor = e4_ingreso_dato(posicion=posicion)
  return lista

def e4_encontrar_maximo(lista:list[float]) -> tuple[int,float]:
  """ Busca el mayor número de una lista.

  Args:
    lista (list[float]): Contiene la lista de números.

  Returns:
    tuple[int,float]: Retorna una tupla con la posición y el máximo número.
  """
  respuesta:tuple[int,float] = 1,0
  for indice,valor in enumerate(lista):
    if valor > respuesta[1]:
      respuesta = indice+1,valor
  return respuesta

maximo:tuple[int,float] = e4_encontrar_maximo(lista=e4_ingreso_datos())

print(f'El máximo número es {maximo[1]} y se encuentra en la posición {maximo[0]}')

"""# Ejercicio 5

Escribir una función que agregue un elemento a una lista. Luego de cada ingreso se debe mostrar la lista completa.
"""



#@title Solución

def e5_ingreso_dato(posicion:int) -> float:
  """ Ingreso de datos.

  Args:
    posicion (int): Contiene la posición que estoy ingresando.

  Returns:
    float: Retorna el valor ingresado.
  """
  return float(input(f'Ingrese el valor de la posición {posicion} (-1 corta el ingreso de datos): '))

def e5_agregar_valor(lista:list[float], valor:float):
  """ Agrega un valor a una lista.

  Args:
    lista (list[float]): Contiene la lista de números.
    valor (float): Contiene el valor a agregar.

  """
  lista.append(valor)

def e5_ingreso_datos():
  """ Ingresa datos hasta que se encuentra un -1.
  """
  lista:list[float] = []
  posicion = 1
  valor:float = e5_ingreso_dato(posicion=posicion)
  while valor != -1:
    e5_agregar_valor(lista=lista, valor=valor)
    print('La lista contiene:', lista)
    posicion += 1
    valor = e5_ingreso_dato(posicion=posicion)

e5_ingreso_datos()

"""# Ejercicio 6

Completa la función `e6_funcion` para que imprima la cantidad variables que recibe como parámetros.
"""

def e6_ingreso_dato(posicion:int) -> float:
  """ Ingreso de datos.

  Args:
    posicion (int): Contiene la posición que estoy ingresando.

  Returns:
    float: Retorna el valor ingresado.
  """
  return float(input(f'Ingrese el valor de la posición {posicion} (-1 corta el ingreso de datos): '))

def e6_ingreso_datos() -> list[float]:
  """ Ingresa datos hasta que se encuentra un -1.
  """
  lista:list[float] = []
  posicion = 1
  valor:float = e6_ingreso_dato(posicion=posicion)
  while valor != -1:
    lista.append(valor)
    posicion += 1
    valor = e6_ingreso_dato(posicion=posicion)
  return lista

def e6_funcion(*args:float):
  """ Función que muestra por pantalla la cantidad de valores que recibe.

  Args:
    args (float): Valores flotantes.
  """
  ### COMPLETAR

e6_funcion(*e6_ingreso_datos())

#@title Solución
def e6_ingreso_dato(posicion:int) -> float:
  """ Ingreso de datos.

  Args:
    posicion (int): Contiene la posición que estoy ingresando.

  Returns:
    float: Retorna el valor ingresado.
  """
  return float(input(f'Ingrese el valor de la posición {posicion} (-1 corta el ingreso de datos): '))

def e6_ingreso_datos() -> list[float]:
  """ Ingresa datos hasta que se encuentra un -1.
  """
  lista:list[float] = []
  posicion = 1
  valor:float = e6_ingreso_dato(posicion=posicion)
  while valor != -1:
    lista.append(valor)
    posicion += 1
    valor = e6_ingreso_dato(posicion=posicion)
  return lista

def e6_funcion(*args:float):
  """ Función que muestra por pantalla la cantidad de valores que recibe.

  Args:
    args (float): Valores flotantes.
  """
  ### COMPLETAR
  print(f'La función recibio {len(args) + 1} parámetros')

e6_funcion(*e6_ingreso_datos())

"""# Ejercicio 7

Escribir una función que calcule la suma de una cantidad variable de números. La función no puede recibir una lista y no se puede utilizar la función `sum`.
"""



#@title Solución


def e7_ingreso_dato(posicion:int) -> float:
  """ Ingreso de datos.

  Args:
    posicion (int): Contiene la posición que estoy ingresando.

  Returns:
    float: Retorna el valor ingresado.
  """
  return float(input(f'Ingrese el valor de la posición {posicion} (-1 corta el ingreso de datos): '))

def e7_ingreso_datos() -> list[float]:
  """ Ingresa datos hasta que se encuentra un -1.
  """
  lista:list[float] = []
  posicion = 1
  valor:float = e7_ingreso_dato(posicion=posicion)
  while valor != -1:
    lista.append(valor)
    posicion += 1
    valor = e7_ingreso_dato(posicion=posicion)
  return lista

def e7_sumar(*args:float) -> float:
  """ Función que suma valores.

  Args:
    args (float): Valores flotantes.

  Returns:
    float: Retorna la suma de los valores.
  """
  suma:float = 0
  for valor in args:
    suma += valor
  return suma

valores:list[float] = e7_ingreso_datos()
print(f'La suma de la lista\n{valores}\nes: {e7_sumar(*valores)}')

"""# Ejercicio 8

Ejercutar el siguiente código con las siguientes secuencias y anotar que pasa en cada una.

Para cada secuencia responder:

> ¿Qué sucedió?

> Se mostraron los valores?

> Porqué?

> Comó lo podría solucionar?
"""

def e8_ingreso_dato(posicion:int, corte:str = '') -> float:
  """ Ingreso de datos.

  Args:
    posicion (int): Contiene la posición que estoy ingresando.
    corte (str): Contiene el mensaje de corte. Defaults to ''.

  Returns:
    float: Retorna el valor ingresado.
  """
  return float(input(f'Ingrese un número de la posición {posicion}{corte}: '))

def e8_ingreso_nombre(posicion:int) -> str:
  """ Ingreso de nombres de variables.

  Args:
    posicion (int): Contiene la posición que estoy ingresando.

  Returns:
    float: Retorna el nombre de una variable.
  """
  return input(f'Ingrese el nombre de la variable en la posición {posicion} (enter corta el ingreso de datos): ').strip()

def e8_ingreso_datos() -> list:
  """ Ingresa datos hasta que se encuentra un -1.
  """
  lista:list = []
  posicion = 1
  valor:float = e8_ingreso_dato(posicion=posicion, corte=' (-1 corta el ingreso de datos)')
  while valor != -1:
    lista.append(valor)
    posicion += 1
    valor = e8_ingreso_dato(posicion=posicion, corte=' (-1 corta el ingreso de datos)')
  return lista

def e8_ingreso_datos_nombre() -> dict:
  """ Ingresa datos hasta que se encuentra un -1.
  """
  diccionario:dict = {}
  posicion = 1
  variable:str = e8_ingreso_nombre(posicion=posicion)
  while variable != '':
    valor:float = e8_ingreso_dato(posicion=posicion)
    diccionario[variable] = valor
    posicion += 1
    variable = e8_ingreso_nombre(posicion=posicion)
  return diccionario

def e8_funcion(par_1, par_2, par_3):
  """ Función que recibe valores.

  Args:
    par_1: Parámetro 1.
    par_2: Parámetro 2.
    par_3: Parámetro 3.
  """
  print(f'par_1 = {par_1}')
  print(f'par_2 = {par_2}')
  print(f'par_3 = {par_3}')

"""### Secuencia 1

Ingresar los valores:

| Valor |
| --- |
| 5 |
| 8 |
| 1 |
| -1 |
"""

e8_funcion(*e8_ingreso_datos())

"""### Secuencia 2

Ingresar los valores:

| Valor |
| --- |
| 5 |
| 8 |
| -1 |
"""

e8_funcion(*e8_ingreso_datos())

"""### Secuencia 3

Ingresar los valores:

| Valor |
| --- |
| 5 |
| 8 |
| 1 |
| 3 |
| -1 |
"""

e8_funcion(*e8_ingreso_datos())

"""### Secuencia 4

Ingresar los valores:

| Variable | Valor |
| --- | --- |
| par_1 | 5 |
| par_2 | 8 |
| par_3 | 1 |
| vacio o persionar enter |  |
"""

e8_funcion(**e8_ingreso_datos_nombre())

"""### Secuencia 5

Ingresar los valores:

| Variable | Valor |
| --- | --- |
| par_1 | 5 |
| par_2 | 8 |
| vacio o persionar enter |  |
"""

e8_funcion(**e8_ingreso_datos_nombre())

"""### Secuencia 6

Ingresar los valores:

| Variable | Valor |
| --- | --- |
| par_1 | 5 |
| par_2 | 8 |
| par_3 | 1 |
| par_4 | 2 |
| vacio o persionar enter |  |
"""

e8_funcion(**e8_ingreso_datos_nombre())

"""### Secuencia 7

Ingresar los valores:

| Variable | Valor |
| --- | --- |
| par_1 | 5 |
| par_2 | 8 |
| par_4 | 1 |
| vacio o persionar enter |  |
"""

e8_funcion(**e8_ingreso_datos_nombre())

