# -*- coding: utf-8 -*-
"""Semana_04-04_Anotaciones_de_funciones.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JiSHQjLOm5MDaAtGwa6rKPeDALFnKVEc

# Anotaciones en Funciones

## Function Annotations en Python
Las anotaciones en funciones o function annotations de Python nos permiten añadir el tipo de los argumentos de entrada y salida de una función. A continuación podemos ver un ejemplo con la función suma(), que recibe dos argumentos a, b y cuyo tipo se espera que sea int.
"""

def multiplica_por_3(numero: int) -> int:
  """ Función que multiplica un número entero por 3

  Args:
    numero (int): Número entero a multiplicar

  Returns:
    (int): El número multiplicado por 3
  """
  return numero*3

print('El resultado de multiplicar 6 * 3 es: ', multiplica_por_3(6))

"""Sin embargo es muy importante notar que Python ignora las anotaciones. Es decir, son una mera nota en el código que indica el tipo esperado, pero el siguiente código no daría ningún error. Más adelante explicaremos cómo realizar el chequeo de tipos."""

print('El resultado de multiplicar "Cadena" * 3 es: ', multiplica_por_3("Cadena"))

"""Las anotaciones en funciones fueron introducidas en la [PEP3107](https://www.python.org/dev/peps/pep-3107/) para Python 3, y más adelante se introdujo la [PEP484](https://www.python.org/dev/peps/pep-0484/) especificando la semántica que se debe usar.

## Motivación y Necesidad de las Anotaciones
Python es un lenguaje de programación con tipado dinámico y duck typing, lo que significa que los tipos (int, str, etc) le dan igual. Precisamente esto es lo que hace que el siguiente código funcione. La función `print` puede ser llamada con cualquier tipo, ya que Python no realiza ninguna comprobación del tipo de var.
"""

resultado = multiplica_por_3(2)
print('El resultado de multiplicar 2 * 3 es: ', resultado, ' - el tipo del resultado es: ', type(resultado))
resultado = multiplica_por_3(3.0)
print('El resultado de multiplicar 3.0 * 3 es: ', resultado, ' - el tipo del resultado es: ', type(resultado))
resultado = multiplica_por_3("Cadena")
print('El resultado de multiplicar "Cadena" * 3 es: ', resultado, ' - el tipo del resultado es: ', type(resultado))

"""Sin embargo, en ciertas ocasiones esto nos puede traer problemas. ¿Y si queremos que la función `multiplica_por_3` sólo acepte que `numero` sea de un tipo concreto? Pues bien, las anotaciones en funciones o function annotations como acabamos de ver nos permiten especificar los tipos que se esperan recibir.

## Ejemplos de Function Annotations
Antes de nada es importante notar que las anotaciones en funciones no definen per se una semántica propia. Es decir, podemos escribir lo que se nos ocurra después de cada argumento. Las anotaciones pueden ser accedidas usando \_\_annotations\_\_.

Tener en cuenta que las comillas no son necesarias pero muchas veces para evitar redundancias cíclicas se utilizan las comillas, de esta forma python interpreta al tipo como un str. Lo más común de ver en las anotaciones son los tipos de datos básicos (int, float, str, tuple, set, dict, list, etc.).
"""

def suma(a: 'parametro 1', b: 'parametro 2') -> 'retorno':
    return a + b

print(suma.__annotations__)

"""Aunque como hemos dicho se puedan realizar anotaciones arbitrarias, suele ser común usar tipos de Python como int, str o float. En el siguiente ejemplo podemos ver como se combina una anotación con un valor por defecto []."""

def filtrar_pares(salida: list = []) -> 'list':
    return [i for i in salida if i%2 == 0]

print('El resultado de filtrar los pares es: ', filtrar_pares([1, 2, 3, 4, 5, 6]))

"""También es posible usar como anotaciones clases definidas por nosotros, como ClaseA.


"""

class ClaseA:
    pass

def funcion(a: ClaseA) -> ClaseA:
    return a

a = ClaseA()
funcion(a)

"""Por último, las anotaciones no están limitadas a los argumentos de las funciones, sino que también se pueden asignar a variables que declaremos."""

pi: float = 3.14

print('El valor de pi es: ', pi)

"""Sin embargo, como ya hemos visto anteriormente, Python no da error cuando los tipos no se corresponden como en el ejemplo anterior."""

# Ojo: No sería correcto, pero Python no da error
pi: int = 3.14

print('El valor de pi es: ', pi)

"""Entonces uno se puede preguntar, ¿y para que sirven las function annotation, si Python las ignora? Pues bien, aunque las ignore, tenemos herramientas que nos permiten saber cuando no se están respetando. Lo vemos a continuación con el análisis estático del código.

## Uso de mypy y Static Type Checking

Para la verificación de tipos estática podemos utilizar herramientas de terceros, en este caso utilizaremos `mypy` que realiza una verificación mediate la instalación de una librería y la posterior ejecución. Sin embargo el error que obtendríamos sería en tiempo de ejecución. Es decir, nos encontraríamos con el error una vez el código estuviera ejecutándose.

Para ampliar o conocer otras librerías relacionadas, leer la [nota](https://testdriven.io/blog/python-type-checking/).
"""

import traceback

# Nota: Ejemplo didáctico, no recomendado
def suma(a: int, b: int) -> int:
    if isinstance(a, suma.__annotations__['a']) and isinstance(b, suma.__annotations__['b']):
        return a + b
    else:
        raise ValueError("Error de tipos")

print('La suma de 7 + 3 es: ', suma(7, 3))

try:
  print('La suma de 7.0 + 3.0 es: ', suma(7., 3.))
except ValueError as e:
  traceback.print_exc()

"""Afortunadamente, tenemos herramientas como mypy que nos permiten hacer un chequeo estático de los tipos, obteniendo el error antes de que el código se ejecute. Lo podemos instalar de la siguiente manera."""

!pip install -q mypy

"""Y volviendo al ejemplo anterior de la suma, podemos ver como el siguiente código si que pasaría los checks de mypy."""

# Commented out IPython magic to ensure Python compatibility.
# %%writefile suma_correcta.py
# 
# # suma_correcta.py
# def suma(a: int, b: int) -> int:
#     return a + b
# 
# print('La suma de 7 + 3 es: ', suma(7, 3))
#

!mypy suma_correcta.py

"""Sin embargo si cambiamos los tipos de los parámetros de entrada, obtendremos un error.


"""

# Commented out IPython magic to ensure Python compatibility.
# %%writefile suma_incorrecta.py
# 
# # suma_incorrecta.py
# def suma(a: int, b: int) -> int:
#     return a + b
# 
# 
# try:
#   print('La suma de 7.0 + 3.0 es: ', suma(7., 3.))
# except ValueError as e:
#   traceback.print_exc()

!mypy suma_incorrecta.py

"""Como hemos indicado, la ventaja de mypy es que realiza un análisis estático, es decir, sin ejecutar el código. Esto es algo muy importante ya que si de verdad queremos reforzar que se verifiquen los tipos, no tendría mucho sentido hacerlo en tiempo de ejecución, ya que sería demasiado tarde y tendríamos un error."""