# -*- coding: utf-8 -*-
"""Semana_04-06_Recursividad.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1S9b2JsUlKJjzJxa5p9CY09Dl2vE3Wsqe

## Recursividad
¿En qué trabajas? Estoy intentando arreglar los problemas que creé cuando intentaba arreglar los problemas que creé cuando intentaba arreglar los problemas que creé. Y así nació la recursividad.

La recursividad o recursión es un concepto que proviene de las matemáticas, y que aplicado al mundo de la programación nos permite resolver problemas o tareas donde las mismas pueden ser divididas en subtareas cuya funcionalidad es la misma. Dado que los subproblemas a resolver son de la misma naturaleza, se puede usar la misma función para resolverlos. Dicho de otra manera, una función recursiva es aquella que está definida en función de sí misma, por lo que se llama repetidamente a sí misma hasta llegar a un punto de salida.

Cualquier función recursiva tiene dos secciones de código claramente divididas:

* Por un lado tenemos la sección en la que la función se llama a sí misma.
* Por otro lado, tiene que existir siempre una condición en la que la función retorna sin volver a llamarse. Es muy importante porque de lo contrario, la función se llamaría de manera indefinida.

Veamos unos ejemplos con el factorial y la serie de fibonacci.

## Calcular [factorial](https://es.wikipedia.org/wiki/Factorial)

Uno de los ejemplos mas usados para comprender la recursividad, es el cálculo del factorial de un número `n!`. El factorial de un número `n` se define como la multiplicación de todos sus números predecesores hasta llegar a uno. Con la particularidad de que `0!` es 1.

Por lo tanto `5!`, leído como cinco factorial, sería `5*4*3*2*1`.

Utilizando un enfoque tradicional no recursivo, podríamos calcular el factorial de la siguiente manera.
"""

def factorial_normal(n:int)->int:
  """ Función que calcula el factorial de un número n.

  Args:
      n (int): Número del que se quiere calcular el factorial.

  Returns:
      int: Factorial del número n.
  """
  if n == 0: return 1
  resultado:int = 1
  for i in range(1, n+1):
    resultado *= i
  return resultado

print('El factorial de 5 es: ', factorial_normal(5))

"""Dado que el factorial es una tarea que puede ser dividida en subtareas del mismo tipo (multiplicaciones), podemos darle un enfoque recursivo y escribir la función de otra manera."""

def factorial_recursivo(n:int) -> int:
    """ Función que calcula el factorial de un número n.

    Args:
        n (int): Número del que se quiere calcular el factorial.

    Returns:
        int: Factorial del número n.
    """
    if n == 0: return 1
    return n * factorial_recursivo(n-1)

print('El factorial de 5 es: ', factorial_normal(5))

"""Lo que realmente hacemos con el código anterior es llamar a la función factorial_recursivo() múltiples veces. Es decir,

| Número | Función | Resultado |
| --- | --- | --- |
| 5! | 5 * 4!| 5 \* 4 \* 3 \* 2 \* 1 \* 1 |
| 4! | 4 * 3!| 4 \* 3 \* 2 \* 1 \* 1 |
| 3! | 3 * 2!| 3 \* 2 \* 1 \* 1 |
| 2! | 2 * 1!| 2 \* 1 \* 1 |
| 1! | 1 * 0!| 1 \* 1 |
| 0! | | 1 |

Algo muy importante a tener en cuenta es que si realizamos demasiadas llamadas a la función, podríamos llegar a tener un error del tipo RecursionError. Esto se debe a que todas las llamadas van apilándose y creando un contexto de ejecución, algo que podría llegar a causar un stack overflow o desbordamiento de memoria. Es por eso por lo que Python lanza ese error, para protegernos de llegar a ese punto.

## Serie de [Fibonacci](https://es.wikipedia.org/wiki/Sucesi%C3%B3n_de_Fibonacci)

Otro ejemplo muy usado para ilustrar las posibilidades de la recursividad, es calcular la serie de fibonacci. Dicha serie calcula el elemento `n` sumando los dos anteriores `n-1 + n-2`. Se asume que los dos primeros elementos son `0` y `1`.
"""

def fibonacci_recursivo(n:int) -> int:
    """ Función que calcula el elemento n de la serie de fibonacci.

    Args:
        n (int): Número del que se quiere calcular el elemento de la serie de fibonacci.

    Returns:
        int: Elemento n de la serie de fibonacci.
    """
    if n == 0:
        return 0
    elif n == 1:
        return 1
    else:
        return fibonacci_recursivo(n-1) + fibonacci_recursivo(n-2)

"""Podemos ver que siempre que la n sea distinta de cero o uno, se llamará recursivamente a la función, buscando los dos elementos anteriores. Cuando la n valga cero o uno se dejará de llamar a la función y se devolverá un valor concreto.

| Número | Función | Resultado |
| --- | --- | --- |
| 7 | fibonacci_recursivo(6) + fibonacci_recursivo(5) | 8 + 5 |
| 6 | fibonacci_recursivo(5) + fibonacci_recursivo(4) | 5 + 3 |
| 5 | fibonacci_recursivo(4) + fibonacci_recursivo(3) | 3 + 2 |
| 4 | fibonacci_recursivo(3) + fibonacci_recursivo(2) | 2 + 1 |
| 3 | fibonacci_recursivo(2) + fibonacci_recursivo(1) | 1 + 1 |
| 2 | fibonacci_recursivo(1) + fibonacci_recursivo(0) | 1 + 0 |
| 1 | 1 |
| 0 | 0 |

Podemos calcular el elemento 7, que será 0,1,1,2,3,5,8,13, es decir, 13.


"""

print('La de fibonacci de 7 es: ', fibonacci_recursivo(7))