# -*- coding: utf-8 -*-
"""Semana_04-01_funciones.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1p0GWf6ImEI6iSjWo3v7SMRA0Lho1l7iI

## Funciones en Python

Anteriormente hemos usado funciones nativas que vienen con Python como len() para calcular la longitud de una lista, pero al igual que en otros lenguajes de programación, también podemos definir nuestras propias funciones. Para ello hacemos uso de def.

```
def nombre_función(argumentos_o_parámetros):
    código
    return retorno

```

Cualquier función tendrá un nombre, uno o más argumentos de entrada, un código a ejecutar y un parámetro de salida. Al igual que las funciones matemáticas, en programación nos permiten realizar diferentes operaciones con la entrada, para entregar una determinada salida que dependerá del código que escribamos dentro.

Por lo tanto, es totalmente análogo al clásico y=f(x) de las matemáticas.
"""

def funcion(x:int) -> int:
    return 2*x
x:int = 3
y:int = funcion(x)
print(f'Para el valor {x} obtenemos el valor {y}')

"""Algo que diferencia en cierto modo las funciones en el mundo de la programación, es que no sólo realizan una operación con sus entradas, sino que también parten de los siguientes principios:

* El principio de reusabilidad, que nos dice que si por ejemplo tenemos un fragmento de código usado en muchos sitios, la mejor solución sería pasarlo a una función. Esto nos evitaría tener código repetido, y que modificarlo fuera más fácil, ya que bastaría con cambiar la función.
* Y el principio de modularidad, el cual define que en vez de escribir largos trozos de código, es mejor crear módulos o funciones que agrupen ciertos fragmentos de código en funcionalidades específicas, haciendo que el código resultante sea más fácil de leer.

## Pasando argumentos de entrada

Empecemos por la función más sencilla de todas. Una función sin parámetros de entrada ni parámetros de salida.
"""

def di_hola():
    print("Hola")

"""Python permite pasar argumentos también de otras formas. A continuación las explicamos todas.

### Argumentos por posición

Los argumentos por posición o posicionales son la forma más básica e intuitiva de pasar parámetros. Si tenemos una función `resta()` que acepta dos parámetros, se puede llamar como se muestra a continuación.
"""

def resta(valor_1:int, valor_2:int) -> int:
    return valor_1 - valor_2
argumento_1:int = 5
argumento_2:int = 3
resultado:int = resta(argumento_1, argumento_2)

print(f'El resultado de la resta de {argumento_1} y {argumento_2} es {resultado}')

"""Al tratarse de parámetros posicionales, se interpretará que el primer parámetro (`argumento_1`) es asignado a `valor_1` y el segundo parámetro (`argumento_2`) es asignado a valor_2. El número de parámetros es fijo, por lo que si intentamos llamar a la función con solo uno, dará error.


"""

import traceback

try:
  resta(1)
except Exception:
  traceback.print_exc()

"""Tampoco es posible usar mas argumentos de los tiene la función definidos, ya que no sabría que hacer con ellos. Por lo tanto si lo intentamos, Python nos dirá que toma 2 posicionales y estamos pasando 3, lo que no es posible."""

try:
  resta(5,4,3)
except Exception:
  traceback.print_exc()

"""### Argumentos por nombre
Otra forma de llamar a una función, es usando el nombre del argumento con `=` y su valor. El siguiente código hace lo mismo que el código anterior, con la diferencia de que los argumentos no son posicionales sino que son nombrados. Esta es la forma más prolija de escribir código.
"""

resultado:int = resta(valor_1=argumento_1, valor_2=argumento_2)

print(f'El resultado de la resta de {argumento_1} y {argumento_2} es {resultado}')

"""Al indicar en la llamada a la función el nombre de la variable y el valor, el orden ya no importa, y se podría llamar de la siguiente forma.

Nótese que ahora los nombres de los parámetros están invertidos pero el resultado es el mismo porque los valores se reciben según el nombre.
"""

resultado:int = resta(valor_2=argumento_2, valor_1=argumento_1)

print(f'El resultado de la resta de {argumento_1} y {argumento_2} es {resultado}')

"""Como es de esperar, si indicamos un argumento que no ha sido definido como parámetro de entrada, tendremos un error."""

try:
  resta(valor_1=5, valor=4)
except Exception:
  traceback.print_exc()

"""### Argumentos por defecto
Tal vez queramos tener una función con algún parámetro opcional, que pueda ser usado o no dependiendo de diferentes circunstancias. Para ello, lo que podemos hacer es asignar un valor por defecto a la función. En el siguiente caso ǜalor_3` valdría cero salvo que se indique lo contrario.
"""

def suma(valor_1:int, valor_2:int, valor_3:int=0) -> int:
    return valor_1 + valor_2 + valor_3

argumento_1:int = 5
argumento_2:int = 5
argumento_3:int = 3
resultado:int = suma(argumento_1, argumento_2, argumento_3)

print(f'El resultado de sumar el {argumento_1} + {argumento_2} + {argumento_3} es {resultado}')

def por_defecto(valor_1:int, valor_2:int=0):
    pass

por_defecto(argumento_1)

"""Dado que el parámetro `valor_3` tiene un valor por defecto, la función puede ser llamada sin ese valor.


"""

resultado:int = suma(argumento_1, argumento_2)

print(f'El resultado de sumar el {argumento_1} + {argumento_2} es {resultado}')

"""Podemos incluso asignar un valor por defecto a todos los parámetros, por lo que se podría llamar a la función sin ningún argumento de entrada."""

def suma(valor_1:int=5, valor_2:int=5, valor_3:int=3) -> int:
    return valor_1 + valor_2 + valor_3

resultado:int = suma()

print(f'El resultado de ejecutar suma es {resultado}')

"""Las siguientes llamadas a la función también son válidas

"""

argumento_1:int = 5
argumento_2:int = 5
argumento_3:int = 3
resultado:int = suma(argumento_1)
print(f'El resultado de sumar el {argumento_1} + (5 por defecto + 3 por defecto) es {resultado}')

resultado:int = suma(argumento_1, argumento_2)
print(f'El resultado de sumar el {argumento_1} + {argumento_2} + (3 por defecto) es {resultado}')

resultado:int = suma(argumento_1, argumento_2, argumento_3)
print(f'El resultado de sumar el {argumento_1} + {argumento_2} + {argumento_3} es {resultado}')

"""O haciendo uso de lo que hemos visto antes y usando los nombres de los argumentos.


"""

resultado:int = suma(valor_1=argumento_1, valor_2=argumento_2)
print(f'El resultado de sumar el {argumento_1} + {argumento_2} + (3 por defecto) es {resultado}')

"""## Argumentos de longitud variable
En el ejemplo con argumentos por defecto, hemos visto que la función puede ser llamada con diferente número de argumentos de entrada, pero esto no es realmente una función con argumentos de longitud variable, ya que existe un número máximo.

Imaginemos que queremos una función `suma_argumentos_variables` como la de antes, pero en este caso necesitamos que sume todos los números de entrada que se le pasen, sin importar si son 3 o 100. Una primera forma de hacerlo sería con una lista.


"""

def suma_argumentos_variables(numeros:list) -> int|float:
    """ Función que suma n números

    Args:
      numeros (list): Lista de números

    Returns:
      (int|float): Suma de los números
    """
    total:int|float = 0
    for n in numeros:
        total += n
    return total

argumentos = [1,3,5,4]
resultado:int|float = suma_argumentos_variables(argumentos)
print(f'El resultado de sumar el {argumentos} es {resultado}')

"""La forma es válida y cumple nuestro requisito, pero realmente no estamos trabajando con argumentos de longitud variable. En realidad tenemos un solo argumento que es una lista de números.

En la siguiente entrega hablaremos de `args` y `kwargs` que son la forma correcta de implementar los argumentos variables.

## Sentencia return
El uso de la sentencia `return` permite realizar dos cosas:

Salir de la función y transferir la ejecución de vuelta a donde se realizó la llamada.

Devuelve uno o varios parámetros, fruto de la ejecución de la función.

En lo relativo a lo primero, una vez se llama a `return` se para la ejecución de la función y se vuelve o retorna al punto donde fue llamada. Es por ello por lo que el código que va después del `return` no es ejecutado en el siguiente ejemplo.
"""

def mi_funcion():
    print("Entra en mi_funcion")
    return
    print("No llega")
mi_funcion()

"""Por ello, sólo llamamos a return una vez hemos acabado de hacer lo que teníamos que hacer en la función.

Por otro lado, se pueden devolver parámetros. Normalmente las funciones son llamadas para realizar unos cálculos en base a una entrada, por lo que es interesante poder devolver ese resultado a quien llamó a la función.
"""

def di_hola():
    return "Hola"
print('El resultado de ejecutar la función di_hola es: ',di_hola())

"""También es posible devolver mas de una variable, separadas por `,`. En el siguiente ejemplo tenemos una función que calcula la suma y la media de tres números, y devuelve su resultado."""

def suma_y_media(a:int, b:int, c:int) -> tuple[int,float]:
    suma = a+b+c
    media = suma/3
    return suma, media
suma, media = suma_y_media(9, 6, 3)
print('El resultado de la suma de 9 + 6 + 3 es: ', suma)
print('El resultado de la media de 9 + 6 + 3 es: ', media)

"""## Documentación

Ahora que ya tenemos nuestras propias funciones creadas, tal vez alguien se interese en ellas y podamos compartírselas. Las funciones pueden ser muy complejas, y leer código ajeno no es tarea fácil. Es por ello por lo que es importante documentar las funciones. Es decir, añadir comentarios para indicar como deben ser usadas.
"""

def mi_funcion_suma(arguemnto_1:int, arguemnto_2:int = 3) -> int:
    """ Suma de enteros.

    Args:
      arguemnto_1 (int): Valor de entrada.
      arguemnto_2 (int): Valor de entrada. Por defecto 3.

    Returns:
      (int): Retorna la suma de 2 enteros.
    """
    return arguemnto_1 + arguemnto_2

"""Para ello debemos usar la triple comilla `'''` al principio de la función. Se trata de un de comentario que podemos usar para indicar como la función debe ser utilizada. No se trata de código, es un simple comentario un tanto especial, conocido como docstring.

Ahora cualquier persona que tenga nuestra función, podrá llamar a la función `help` y obtener la ayuda de como debe ser usada.
"""

help(mi_funcion_suma)

"""Otra forma de acceder a la documentación es la siguiente.


"""

print(mi_funcion_suma.__doc__)

"""Para saber más: Las descripciones de las funciones suelen ser un poco mas detalladas de lo que hemos mostrado. En la [PEP257](https://www.python.org/dev/peps/pep-0257/) se define en detalle como debería ser."""