# -*- coding: utf-8 -*-
"""Semana_04-09_Corrutinas.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FaRQY6NgaIQwXI-14B7Vh0WnrY91FU4S

## Corrutinas
Las corrutinas son similares a los generadores pero tienen ciertas diferencias. Las principales son las siguientes:

* Los generadores son productores de datos
* Las corrutinas son consumidores de datos

Antes de nada, vamos a revisar como se creaba un generador. Podemos hacerlo de la siguiente manera:
"""

def fib(iteraciones):
    a, b = 0, 1
    while True:
        yield a
        a, b = b, a+b
        iteraciones -= 1
        if iteraciones == 0:
            yield None

"""A modo de breve recordatorio, el uso de `yield` retorna de la función a donde fue llamada, pero si es vuelta a llamar continúa su ejecución inmediatamente después del `yield`.

Ahora podemos usarlo en un bucle for como se muestra a continuación:
"""

for i in fib(10):
    print('El valor obtenido es: ', i)
    if i == None:
      break

"""Es rápido y no consume demasiada memoria ya que genera los valores al vuelo (uno a uno) en vez de almacenarlos todos en una lista. Ahora, si usamos yield en el anterior ejemplo, tendremos una corrutina. Las corrutinas consumen los valores que le son enviados. Un ejemplo muy sencillo sería un grep en Python:"""

def encontrar(patron):
    """ Busca un patrón en la entrada.
    """
    print("Buscando", patron)
    while True:
        linea = (yield)
        if patron in linea:
            print(f'Se encontró el patrón {patron} en la línea {linea}')

"""Pero espera, ¿qué es lo que devuelve `yield`?

Bueno, en realidad lo que hemos hecho es convertirlo en una corrutina. No contiene ningún valor inicialmente, sino que proporcionamos esos valores externamente. Los valores son proporcionados usando el método `send`.

Aquí podemos ver un ejemplo:
"""

buscar = encontrar('corrutina')
next(buscar)
buscar.send("Prueba línea 1")
buscar.send("Esto es una función")
buscar.send("Estoy aprendiendo corrutinas")
buscar.send("Esto es perfecto!")
buscar.close()

"""Por lo tanto cuando enviamos una línea con `send`, si cumple con el `patrón`  que hemos indicado al llamar a la función `buscar` será impresa por pantalla.

Los valores enviados son accedidos por `yield`. Tal vez te preguntes sobre el uso de `next`. Es requerido para empezar la corutina. Al igual que los generators, las corutinas no empiezan inmediatamente, sino que se ejecutan en respuesta a los métodos `__next__` y `send`. Por lo tanto tienes que ejecutar `next` para que la ejecución avance hasta la expresión `yield`.

Por otro lado, podemos cerrar la corrutina llamando al método `close` como se muestra a continuación:
"""

buscar = encontrar('corrutina')
# ...
buscar.close()

"""Las coroutines van mucho más allá de lo que hemos explicado, por lo que te sugerimos que eches un vistazo a estar increíble [presentación](http://www.dabeaz.com/coroutines/Coroutines.pdf) de David Beazley."""