# -*- coding: utf-8 -*-
"""Semana_04-03_args_kwargs.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1u3anumU8WZ5yeULx2Fs5qW8kNTFhVNQQ

# Args y Kwargs en Python
Si alguna vez has tenido que definir una función con un número variable de argumentos y no has sabido como hacerlo, a continuación te explicaré cómo utilizar `args` y `kwargs` en Python.

Vamos a suponer que queremos una función que sume un conjunto de números, pero no sabemos a priori la cantidad de números que se quieren sumar. Si por ejemplo tuviéramos tres, la función sería tan sencilla como la siguiente.
"""

import traceback

def suma(a:int, b:int, c:int) -> int:
    """ Función que suma 3 números enteros.

    Args:
        a (int): Primer número a sumar.
        b (int): Segundo número a sumar.
        c (int): Tercer número a sumar.

    Returns:
        int: Suma de los tres números.
    """
    return a+b+c

resultado:int = suma(2, 4, 6)
print('El resultado de sumar  2 + 4 + 6 es ', resultado)

"""El problema surge si por ejemplo queremos sumar cuatro números. Como es evidente, la siguiente llamada a la función anterior daría un error ya que estamos usando cuatro argumentos mientras que la función sólo soporta tres.


"""

try:
  suma(2, 4, 6, 1)
except Exception as e:
  traceback.print_exc()

"""Introducida ya la problemática, veamos como podemos resolver este problema con `*args` y `**kwargs` en Python.

## Uso de \*args

Gracias a los `*args` en Python, podemos definir funciones cuyo número de argumentos es variable. Es decir, podemos definir funciones genéricas que no aceptan un número determinado de parámetros, sino que se “adaptan” al número de argumentos con los que son llamados.

De hecho, el args viene de arguments en Inglés, o argumentos. Haciendo uso de `*args` en la declaración de la función podemos hacer que el número de parámetros que acepte sea variable.
"""

def suma_args(*numeros:int|float) -> int|float:
    """ Función que suma un número variable de argumentos.

    Args:
        *numeros (int|float): Números a sumar.

    Returns:
        int|float: Suma de los números.
    """
    print('El tipo de dato del argumento es: ',type(numeros))
    total:int|float = 0
    for n in numeros:
        total += n
    return total

resultado:int|float = suma_args(1, 3, 5, 4)
print(f'El resultado de sumar el 1 + 3 + 5 + 4 es {resultado}')

resultado:int|float = suma_args(6, 4, 10, 20, 4, 6, 7)
print(f'El resultado de sumar el 6 + 4 + 10 + 20 + 4 + 6 + 7 es {resultado}')

"""Antes de nada, el uso del nombre args es totalmente arbitrario, por lo que podrías haberlo llamado como quisieras. Es una mera convención entre los usuarios de Python y resulta frecuente darle ese nombre. Lo que si es un requisito, es usar `*` junto al nombre.

En el ejemplo anterior hemos visto como `*args` puede ser iterado, ya que en realidad es una `tupla`. Por lo tanto iterando la tupla podemos acceder a todos los argumentos de entrada, y en nuestro caso sumarlos y devolverlos.

Nótese que es un mero ejemplo didáctico. En realidad podríamos hacer algo como lo siguiente, lo que sería mucho más sencillo.
"""

def suma_args(*numeros:int|float) -> int|float:
    """ Función que suma un número variable de argumentos.

    Args:
        *numeros (int|float): Números a sumar.

    Returns:
        int|float: Suma de los números.
    """
    print('El tipo de dato del argumento es: ',type(numeros))
    return sum(numeros)

resultado:int|float = suma_args(1, 3, 5, 4)
print(f'El resultado de sumar el 1 + 3 + 5 + 4 es {resultado}')

"""Con esto resolvemos nuestro problema inicial, en el que necesitábamos un número variable de argumentos. Sin embargo, hay otra forma que nos proporciona además un nombre asociado al argumento, con el uso de `**kwargs`. La explicamos a continuación.

## Uso de \*\*kwargs

Al igual que en `*args`, en `**kwargs` el nombre es una mera convención entre los usuarios de Python. Puedes usar cualquier otro nombre siempre y cuando respetes el `**`.

En este caso, en vez de tener una tupla tenemos un `diccionario`. Puedes verificarlo de la siguiente forma con `type`.

A diferencia de `*args`, los `**kwargs` nos permiten dar un nombre a cada argumento de entrada, pudiendo acceder a ellos dentro de la función a través de un diccionario.
"""

def suma_kwargs(**kwargs) -> int|float:
    print('El tipo de dato del argumento es: ',type(kwargs))

    suma:int|float = 0;
    for key, value in kwargs.items():
        print(f'El nombre del argumento es: {key} y el valor asociado es: {value}')
        suma += value
    return suma

resultado:int|float = suma_kwargs(argumento_1=5, argumento_2=20, argumento_3=23)
print(f'El resultado de sumar el 5 + 20 + 23 es {resultado}')

"""Como podemos ver, es posible iterar los argumentos de entrada con `items`, y podemos acceder a la clave key (o nombre) y el valor o value de cada argumento.

El uso de los `**kwargs` es muy útil si además de querer acceder al valor de las variables dentro de la función, quieres darles un nombre que de una información extra.

## Mezclando \*args y \*\*kwargs
Una vez eplicamos el uso de `*args` y `**kwargs`, podemos complicar las cosas un poco más. Es posible mezclar argumentos normales con `*args` y `**kwargs` dentro de la misma función. Lo único que necesitas saber es que debes definir la función en el siguiente orden:

Primero argumentos normales.
* Después los `*args`.
* Y por último los `**kwargs`.
* Veamos un ejemplo.
"""

def funcion(a, b, *args, **kwargs):
    print("a =", a)
    print("b =", b)
    for arg in args:
        print("args =", arg)
    for key, value in kwargs.items():
        print(key, "=", value)

funcion(10, 20, 1, 2, 3, 4, x="Hola", y="Que", z="Tal")

"""## Unpacking * o **

La acción `*` me permite extraer los valores de una `lista` o `tupla`, los cuales son pasados como argumentos a una función.

Por otro lado la acción `**` me permite extraer los valores de un `diccionario`, los cuales son pasados como argumentos a una función. En este caso la `key` del diccionario se convierte en el nombre del argumento y el `value` se convierte en el valor propiamente dicho.

Vamos a ver un ejemplo, tomando como base la función definida anteriormente.
"""

args = [1, 2, 3, 4]
kwargs = {'x':"Hola", 'y':"Que", 'z':"Tal"}

# esta es la llamda con el unpacking
funcion(10, 20, *args, **kwargs)

# esta es la llamada original
#funcion(10, 20, 1, 2, 3, 4, x="Hola", y="Que", z="Tal")

"""Como se puede observar al utilizar el `unpacking` nuestro código queda más sencillo y facíl de comprender."""