# -*- coding: utf-8 -*-
"""Semana_04-02_Paso_de_valores.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vbI-wPnEktYysUYhJ4xm5Qpjv7MG0AS_

# Paso por valor y referencia
En muchos lenguajes de programación existen los conceptos de paso por valor y por referencia que aplican a la hora de como trata una función a los parámetros que se le pasan como entrada. Su comportamiento es el siguiente:

* Si usamos un parámetro pasado por valor, se creará una copia local de la variable, lo que implica que cualquier modificación sobre la misma no tendrá efecto sobre la original.
* Con una variable pasada como referencia, se actuará directamente sobre la variable pasada, por lo que las modificaciones afectarán a la variable original.

En Python las cosas son un poco distintas, y el comportamiento estará definido por el tipo de variable con la que estamos tratando. Veamos un ejemplo de paso por valor.
"""

x:int = 10
print('Valor de la variable x original: ', x)
def funcion(entrada:int):
    entrada = 0
funcion(x)

print('En este caso la variable x no se ve afectada por la función: ', x)

"""Inicializamos la variable `x` a `10` y se la pasamos a `funcion`. Dentro de la función hacemos que la variable tome el valor de `0`. Dado que Python trata a los `int` como pasados por valor, dentro de la función se crea una copia local de `x`, por lo que la variable original no es modificada.

No pasa lo mismo si por ejemplo `x` es una lista como en el siguiente ejemplo.

En este caso Python lo trata como si estuviese pasada por referencia, lo que hace que se modifique la variable original. La variable original `x` ha sido modificada.
"""

x:list[int] = [10, 20, 30]
print('Valor de la variable x original: ', x)

def funcion(entrada:list[int]):
    entrada.append(40)

funcion(x)
print('En este caso la variable x no se ve afectada por la función: ', x)

"""El ejemplo anterior nos podría llevar a pensar que si en vez de añadir un elemento a `x`, hacemos `x=[]`, estaríamos destruyendo la lista original. Sin embargo esto no es cierto.


"""

x:list[int] = [10, 20, 30]
print('Valor de la variable x original: ', x)

def funcion(entrada:list[int]):
    entrada = []

funcion(x)
print('En este caso la variable x no se ve afectada por la función: ', x)

"""Una forma muy útil de saber lo que pasa por debajo de Python, es haciendo uso de la función `id`. Esta función nos devuelve un identificador único para cada objeto. Volviendo al primer ejemplo podemos ver como los objetos a los que “apuntan” `x` de entrada y salida son distintos."""

x:int = 10
print('Valor de la variable x original: ', x, ' - el id es: ', id(x))
def funcion(entrada:int):
    entrada = 0
    print('Valor de la variable entrada original: ', entrada, ' - el id es: ', id(entrada))

funcion(x)

"""Sin embargo si hacemos lo mismo cuando la variable de entrada es una lista, podemos ver que en este caso el objeto con el que se trabaja dentro de la función es el mismo que tenemos fuera."""

x:list[int] = [10, 20, 30]
print('Valor de la variable x original: ', x, ' - el id es: ', id(x))
def funcion(entrada:list[int]):
    entrada.append(40)
    print('Valor de la variable entrada original: ', entrada, ' - el id es: ', id(entrada))

funcion(x)

x:list[int] = [10, 20, 30]
print('Valor de la variable x original: ', x, ' - el id es: ', id(x))

def funcion(entrada:list[int]):
    entrada = []
    print('Valor de la variable entrada original: ', entrada, ' - el id es: ', id(entrada))

funcion(x)
print('En este caso la variable x no se ve afectada por la función: ', x, ' - el id es: ', id(x))

