# -*- coding: utf-8 -*-
"""Semana_02-06_break.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NxQlPlQOJqFQvPUjfU0bnHv1IeKrDBfC

# Sentencia break Python

## Introducción al break
La sentencia break nos permite alterar el comportamiento de los bucles while y for. Concretamente, permite terminar con la ejecución del bucle.

Esto significa que una vez se encuentra la palabra break, el bucle se habrá terminado.

## Break con bucles for
Veamos como podemos usar el `break` con bucles `for`. El `range(5)` generaría 5 iteraciones, donde la variable `i` toma los valores del 0 al 4. Sin embargo, al utilizar el `break` terminamos el bucle prematuramente en la primer iteración.

El `break` hace que al empezar el bucle, se rompa y se salga sin haber hecho nada, solo imprimir el primer de la iteración.
"""

for i in range(5):
    print(f'Iteración: {i}')
    break
print('Fuera del FOR! sin alcanzar las 5 iteraciones por utilizar la sentencia "break"')

"""Un ejemplo un poco más útil, sería el de buscar una letra en una palabra. Se itera toda la palabra y en el momento en el que se encuentra la letra que buscábamos, se rompe el bucle y se sale.

Esto es algo muy útil porque si ya encontramos lo que estábamos buscando, no tendría mucho sentido seguir iterando la lista, ya que desperdiciaríamos recursos.
"""

cadena = 'Python'
for letra in cadena:
    print(letra)
    if letra == 'h':
        print("Se encontró la 'h' y finalizamos el bucle")
        break

"""## Break con bucles while

El `break` también nos permite alterar el comportamiento del `while`. Veamos un ejemplo.

La condición `while True` haría que la sección de código se ejecutara indefinidamente, pero al hacer uso del break, el bucle se romperá cuando la variable `x` tome el valor igual a cero.
"""

x = 5
while True:
    x -= 1
    print(f'Valor: {x}')
    if x == 0:
        break
print("Fin del bucle WHILE!")

"""Por norma general, y salvo casos muy concretos, si ves un `while True`, es probable que haya un `break` dentro del bucle.

## Break y bucles anidados

Como hemos dicho, el uso de `break` rompe el bucle, pero sólo aquel en el que está dentro.

Es decir, si tenemos dos bucles anidados, el `break` romperá el bucle anidado, pero no el exterior.
"""

for i in range(0, 4):
    print(f'Valor i: {i}')
    for j in range(0, 4):
        print(f'\tValor j: {j}')
        if j == 2:
          break
    # El break no afecta a este for
    print('Combinación: ', i, j, '\n')

"""Notesé que la iteración anterior la variable `j` nunca alcanza el valor 3 pero la variable `i` si lo hace y esto se debe a que el `break` solo afecta al `for` de la variable `j`."""