# -*- coding: utf-8 -*-
"""Semana_02-05_match.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1c_10t7aJN2L8RsmM7EBdq8t4-JcyqS8i

# Match en Python
Python ofrece algo similar al switch de otros lenguajes de programación desde la versión 3.10.

Se trata del match. Cada `case` define un camino posible. El `_` es la opción por defecto, que se ejecuta si la entrada no coincide con ningún caso.
"""

hora = 8
match hora:
    case 8:
        print("Desayuno")
    case 14:
        print("Comida")
    case 21:
        print("Cena")
    case _:
        print("No toca comer")

"""El match nos permite realizar lo mismo que con múltiples if/elif como hemos visto anteriormente. Ambos códigos son equivalentes."""

hora = 8
if hora == 8:
  print("Desayuno")
elif hora == 14:
  print("Comida")
elif hora == 21:
  print("Cena")
else:
  print("No toca comer")

"""También podemos tener en nuestros case múltiples condiciones, donde `|` es interpretado como un `or`."""

mes = 4
match mes:
    case 12 | 1 | 2: print("Invierno")
    case 3 | 4 | 5: print("Primavera")
    case 6 | 7 | 8: print("Verano")
    case 9 | 10 | 11: print("Otoño")
    case _: print("Error")

"""Aunque no acaba ahí la cosa. Podemos hacer matching de prácticamente cualquier cosa como una tupla.


"""

coordenada = (0, 1)
match coordenada:
    case (0, 0):
        print("Coordenada en origen")
    case (x, 0):
        print(f"Coordenada en eje x: {x}")
    case (0, y):
        print(f"Coordenada en eje y: {y}")
    case (x, y):
        print(f"Coordenada en: {x}, {y}")
    case _:
        print("Error")

"""## Emulando match con un diccionario

Una forma de tener una especie de match en Python es haciendo uso de un diccionario (lo definiramos más adelante de forma completa).
"""

def comida(hora):
  return {
    '8': "Desayuno",
    '14': "Comida",
    '21': "Cena"
  }.get(hora, "No toca comer")

print(f'Que comida me corresponde? {comida(hora)}')

"""## Tiempo Ejecución match vs if vs diccionario

A continuación veremos varios experimentos donde analizaremos el tiempo de ejecución de dos opciones distintas.

Empecemos con un problema a resolver. Imaginemos que queremos convertir números de decimal a binario. Empecemos por definir las dos formas de hacerlo.

La primera forma es usando if y elif.
"""

def usa_if(decimal):
    if decimal == '0':
        return f"{decimal:03b}"
    elif decimal == '1':
        return f"{decimal:03b}"
    elif decimal == '2':
        return f"{decimal:03b}"
    elif decimal == '3':
        return f"{decimal:03b}"
    elif decimal == '4':
        return f"{decimal:03b}"
    elif decimal == '5':
        return f"{decimal:03b}"
    elif decimal == '6':
        return f"{decimal:03b}"
    elif decimal == '7':
        return f"{decimal:03b}"
    else:
        return "NA"

"""La segunda forma es usando diccionarios simulando un switch.


"""

tabla_funcion = {
        '0': f"{0:03b}",
        '1': f"{1:03b}",
        '2': f"{2:03b}",
        '3': f"{3:03b}",
        '4': f"{4:03b}",
        '5': f"{5:03b}",
        '6': f"{6:03b}",
        '7': f"{7:03b}",
    }
def usa_funcion(decimal):
    return tabla_funcion.get(decimal, "NA")

"""La tercer forma es usando el match."""

def usa_match(decimal):
    match decimal:
      case 0:
        return f"{decimal:03b}"
      case 1:
        return f"{decimal:03b}"
      case 2:
        return f"{decimal:03b}"
      case 3:
        return f"{decimal:03b}"
      case 4:
        return f"{decimal:03b}"
      case 5:
        return f"{decimal:03b}"
      case 6:
        return f"{decimal:03b}"
      case 7:
        return f"{decimal:03b}"
      case _:
        return "NA"

"""Las funciones usa_if, usa_match y usa_funcion realizan lo mismo, pero están implementadas de manera distinta. A continuación mediremos el tiempo de ejecución de ambas para saber cuál es más rápida. Vamos a crear primero un decorador (lo veremos más adelante en detalle) que nos permita medir el tiempo que una función tarda en ejecutarse."""

import time
def mide_tiempo(funcion):
    def funcion_medida(*args, **kwargs):
        inicio = time.time()
        c = funcion(*args, **kwargs)
        print(f"Entrada: {args[1]}. Tiempo: {time.time() - inicio}")
        return c
    return funcion_medida

"""Y ahora vamos a crear una función que llame miles de veces a otra. Esto es debido a que necesitamos realizar varias llamadas a la función para obtener un resultado fiable. Dado que si midiéramos una sola ejecución de un if, a penas tardaríamos unos microsegundos."""

@mide_tiempo
def repite_funcion(funcion, entrada):
    return [funcion(entrada) for i in range(10000000)]

"""Ahora que ya tenemos todo lo que necesitamos para el experimento, vamos a llamar a nuestra funciones con diferentes parámetros. Estos son los resultados:"""

print('Utilizando if')
for i in range(8):
    repite_funcion(usa_if, i)

print('Utilizando la función')
for i in range(8):
    repite_funcion(usa_funcion, i)

print('Utilizando el match')
for i in range(8):
    repite_funcion(usa_match, i)

"""Por lo tanto, podemos concluir lo siguiente:

* Usando if/match el tiempo de ejecución no es siempre el mismo, ya que dependiendo del valor (0-7) tendrán que evaluarse hasta 8 condiciones.
* Usando la función obtenemos un tiempo ligeramente mayor para el "0", pero el tiempo de ejecución apenas varía cuando cambiamos la entrada.

Visto esto, no se puede concluir que una forma sea mejor que otra, todo dependerá del problema que necesites resolver, pero la próxima vez que te enfrentes a un problema similar, ya tendrás las herramientas para tomar una decisión razonada al respecto.
"""