# -*- coding: utf-8 -*-
"""Semana_02-Practica_02.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16udM2QzpVrUXcXxRz9iCt4i7K74PJ2QP

# Ejercicio 01

Completar el siguientes script para realizar una iteración de los 10 primeros números naturales.
"""

for i in .....:
  print(i)

"""# Ejercicio 02

Con while realizar una iteración de los 10 primeros números naturales y mostrarlos por pantalla.
"""



"""# Ejercicio 03

Crear un script que muestre por pantalla los 10000 primeros números pares.

`No se puede utilizar el condicional if`
"""



"""# Ejercicio 4

Crear un script que muestre por separado los primeros 10000 números. La salida del programa debe ser la siguiente:
```
Número par: 0
Número impar: 1
---
Número par: 2
Número impar: 3
```
`No se puede utilizar el condicional if`
"""



"""# Ejercicio 5

Iterar la siguiente frase y mostrar por pantalla cada una de las letras con su posición.

La salida de tener el siguiente formato:
```
Posición 0 caracter: ¿
Posición 1 caracter: C
Posición 2 caracter: u
Posición 3 caracter: á
Posición 4 caracter: l
Posición 5 caracter:  
```

"""

# En La sociedad de la mente (1987).
frase = "¿Cuál es el truco mágico que nos hace inteligentes? El truco es que no hay truco. El poder de la inteligencia emana de nuestra vasta diversidad, no de un único y perfecto principio"

"""# Ejercicio 06

Utilizando iteradores anidados mostrar las tablas de multiplicación que van del 1 al 10.

Ejemplo de la salida:
```
Tabla del 1:
1x1=1
1x2=2
1x3=3
1x4=4
1x5=5
1x6=6
1x7=7
1x8=8
1x9=9
1x10=10

Tabla del 2:
2x1=2
2x2=4
2x3=6
2x4=8
2x5=10
2x6=12
2x7=14
2x8=16
2x9=18
2x10=20
```
"""



"""## Ejercicio 7

Escribir un bucle while que muestre los 10 primeros números naturales y que al finalizar muestre el mensaje `El while se ejecutó correctamente`.

El código debe contener la siguiente línea:
```
print('El while se ejecutó correctamente')
```
"""



"""## Ejercicio 8

Escribir un bucle while que itere los 10 primeros números naturales y que muestre los 3 valores primeros valores. Se debe utilizar la instrucción `break` y el código debe contener la siguiente línea que se muestra a continuación pero no se debe mostrar el mensaje.
```
print('El while se ejecutó correctamente')
```


"""

