# -*- coding: utf-8 -*-
"""Semana_02-09_iterar_enumerate.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yaJ-FaTo9QpHSX8Vv3dWt-Dysthd3hG3

# Enumerate en Python
El uso del `for` en Python nos permite iterar colecciones, recorriendo todos los elementos de la misma.
"""

lista = ["A", "B", "C"]

for l in lista:
    print(l)

"""Sin embargo, existen situaciones en las que no solo queremos acceder al elemento i-ésimo de la colección, sino que además queremos conocer el índice o la posición de cada elemento. Una forma de hacerlo sería la siguiente."""

lista = ["A", "B", "C"]

indice = 0
for l in lista:
    print('Índice: ',indice, ' - VAlor: ', l)
    indice += 1

"""Aunque se trata de una forma perfectamente válida, no es demasiado pythónica, y es precisamente donde entra en juego el `enumerate`. Su uso nos permite ahorrar alguna que otra línea de código, obteniendo un resultado mucho más limpio y claro."""

lista = ["A", "B", "C"]

for indice, l in enumerate(lista):
    print('Índice: ',indice, ' - VAlor: ', l)

"""Por último, es importante notar que su uso no se limita únicamente a bucles `for`. Podemos convertir el tipo enumerate en una lista de tuplas, donde cada una contiene un elemento de la colección inicial y el índice asociado."""

lista = ["A", "B", "C"]

en = list(enumerate(lista))
print(en)

"""Por lo tanto recuerda, la próxima vez que quieras acceder a los índices de una colección, piensa si tal vez enumerate puede resolver tu problema de manera más clara y con menos código.

En caso de necesitar que el índice comienze desde un valor distinto de `0` podemos utilizar el argumento `start` para indicarle el valor de inicio.
"""

lista = ["A", "B", "C"]

for indice, l in enumerate(lista, start=10):
    print('Índice: ',indice, ' - VAlor: ', l)