# -*- coding: utf-8 -*-
"""Semana_02-02_for.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GvBYusTAXsbSXqB9lKLomUG4eNecagzj

# Repetición incondicional for

A continuación explicaremos el bucle for y sus particularidades en Python, que comparado con otros lenguajes de programación, tiene ciertas diferencias.

El `for` es un tipo de bucle, repetición o iteración. Para este debo conocer de antemano la cantidad de veces a repetir un secuencia de sentencias, esto quiere decir que siempre se va a realizar sobre una secuencia o iterable (list, set, tuple, dict, etc.).

En el siguiente ejemplo vemos un bucle for que se ejecuta 5 veces, y donde la variable i incrementa su valor “automáticamente” en 1 en cada iteración.
"""

for i in range(0, 5):
    print(f'Iteración: {i}')

"""En Python se puede iterar prácticamente todo, como por ejemplo una cadena. En el siguiente ejemplo vemos como la i va tomando los valores de cada letra. Mas adelante explicaremos que es esto de los iterables e iteradores."""

for i in "Python":
    print(i)

"""## Iterables e iteradores

Para entender al cien por cien los bucles for, y como Python fue diseñado como lenguaje de programación, es muy importante entender los conceptos de iterables e iteradores. Empecemos con un par de definiciones:

* Los iterables son aquellos objetos que como su nombre indica pueden ser iterados, lo que dicho de otra forma es, que puedan ser indexados. Si piensas en un array (o una lista en Python), podemos indexarlo con lista por ejemplo, por lo que sería un iterable.
* Los iteradores son objetos que hacen referencia a un elemento, y que tienen un método `next()` que permite hacer referencia al siguiente.

Ambos son conceptos un tanto abstractos y que pueden ser complicados de entender. Veamos unos ejemplos.

Como hemos comentado, los iterables son objetos que pueden ser iterados o accedidos con un índice. Algunos ejemplos de iterables en Python son las listas, tuplas, cadenas o diccionarios. Sabiendo esto, lo primero que tenemos que tener claro es que en un for, lo que va después del in deberá ser siempre un iterable.

```
for <variable> in <iterable>:
    <Código>
```

Tiene bastante sentido, porque si queremos iterar una variable, esta variable debe ser iterable, todo muy lógico. Pero llegados a este punto, tal vez te preguntes ¿pero cómo se yo si algo es iterable o no?

Bien fácil, con la siguiente función `isinstance()` podemos saberlo. No te preocupes si no entiendes muy bien lo que estamos haciendo, fíjate solo en el resultado, `True` significa que es iterable y `False` que no lo es.
"""

from collections.abc import Iterable

lista = [1, 2, 3, 4]
cadena = "Python"
numero = 10
print("El valor esperado es True por la variable 'lista' es una lista y es iterable: ",
      isinstance(lista, Iterable), '\nValor de la variable: ', lista)
print("El valor esperado es True por la variable 'cadena' es un string y es iterable: ",
      isinstance(cadena, Iterable), '\nValor de la variable: ', cadena )
print("El valor esperado es False por la variable 'numero' es un número entero y NO es iterable: ",
      isinstance(numero, Iterable), '\nValor de la variable: ', numero)

"""Por lo tanto las listas y las cadenas son iterables, pero numero, que es un entero no lo es. Es por eso por lo que no podemos hacer lo siguiente, ya que daría un error."""

import traceback

try:
  numero = 10
  for i in numero:
      print(i)
except Exception:
  traceback.print_exc()

"""
Una vez entendidos los iterables, veamos los iteradores. Para entender los iteradores, es importante conocer la función `iter()` en Python.

Dicha función puede ser llamada sobre un objeto que sea iterable, y nos devolverá un iterador como se ve en el siguiente ejemplo."""

lista = [5, 6, 3, 2]
it = iter(lista)
print(it)
print(type(it))

"""Vemos que al imprimir `it` es un iterador, de la clase `list_iterator`.

Esta variable iteradora, hace referencia a la lista original y nos permite acceder a sus elementos con la función `next()`.

Cada vez que llamamos a `next()` sobre `it`, nos devuelve el siguiente elemento de la lista original. Por lo tanto, si queremos acceder al elemento 4, tendremos que llamar 4 veces a `next()`.

Nótese que el iterador empieza apuntando fuera de la lista, y no hace referencia al primer elemento hasta que no se llama a `next()` por primera vez.
"""

lista = [5, 6, 3, 2]
it = iter(lista)
print(f'Primera iteración y muestra el número: {next(it)}')
#     [5, 6, 3, 2]
#      ^
#      |
#     it
print(f'Segunda iteración y muestra el número: {next(it)}')
#     [5, 6, 3, 2]
#         ^
#         |
#        it
print(f'Tercera iteración y muestra el número: {next(it)}')
#     [5, 6, 3, 2]
#            ^
#            |
#           it

"""Existen otros iteradores para diferentes clases:

* `str_iterator` para cadenas
* `list_iterator` para lists.
* `tuple_iterator` para tuplas.
* `set_iterator` para sets.
* `dict_keyiterator` para diccionarios.

Dado que el iterador hace referencia a nuestra lista, si llamamos más veces a `next()` que la longitud de la lista, se nos devolverá un error `StopIteration`. Lamentablemente no existe ninguna opción de volver al elemento anterior.
"""

lista = [5, 6]
it = iter(lista)
print(f'Primera iteración y muestra el número: {next(it)}')
print(f'Segunda iteración y muestra el número: {next(it)}')
try:
  print(f'Tercera iteración y muestra el número: {next(it)}')
except Exception:
  print(f'La tercer iteración NO EXISTE porque la lista tiene 2 posiciones')
  traceback.print_exc()

"""Es perfectamente posible tener diferentes iteradores para la misma lista, y serán totalmente independientes. Tan solo dependerán de la lista, como es evidente, pero no entre ellos."""

lista = [5, 6, 7]
it1 = iter(lista)
it2 = iter(lista)
print(f'Primera iteración del iterador it1 y muestra el número: {next(it1)}')
print(f'Segunda iteración del iterador it1 y muestra el número: {next(it1)}')
print(f'Tercera iteración del iterador it1 y muestra el número: {next(it1)}')

print(f'Primera iteración del iterador it2 y muestra el número: {next(it2)}')

"""## For anidados

Es posible anidar los `for`, es decir, meter uno dentro de otro. Esto puede ser muy útil si queremos iterar algún objeto que en cada elemento, tiene a su vez otra clase iterable.

Podemos tener por ejemplo, una lista de listas, una especie de matriz.
"""

lista = [[56, 34, 1],
         [12, 4, 5],
         [9, 4, 3]]

"""Si iteramos usando sólo un `for`, estaremos realmente accediendo a la segunda lista, pero no a los elementos individuales."""

for i in lista:
    print(f'Fila que contiene los valores: {i}')

"""Si queremos acceder a cada elemento individualmente, podemos anidar dos for. Uno de ellos se encargará de iterar las columnas y el otro las filas."""

for fila in lista:
    print(f'Valores de la fila:', end=' ')
    for columna in fila:
        print(columna, end=', ')
    print()

"""## Ejemplos for

Iterando cadena al revés. Haciendo uso de `[::-1]` se puede iterar la lista desde el último al primer elemento.

Más adelante vamos a explicar el slicing que se refiere a este símbolo `[::-1]`.
"""

texto = "Python"
for i in texto[::-1]:
    print(i, end=', ')

"""Itera la cadena saltándose elementos. Con [::2] vamos tomando un elemento si y otro no."""

texto = "Python"
for i in texto[::2]:
    print(i, end=', ')

"""Un ejemplo de for usado con comprehensions lists."""

print('La suma de (0-9] es: ',sum(i for i in range(10)))