# -*- coding: utf-8 -*-
"""Semana_02-07_continue.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DmPyqVy35UnQL6iu4Lhvb2XFkeXmLVvS

# Sentencia continue

## Introducción al continue

El uso de `continue` al igual que el ya visto `break`, nos permite modificar el comportamiento de de los bucles `while` y `for`.

Concretamente, continue se salta todo el código restante en la iteración actual y vuelve al principio en el caso de que aún queden iteraciones por completar.

La diferencia entre el `break` y `continue` es que este último no rompe el bucle, si no que pasa a la siguiente iteración saltando el código que se encuentra debajo de él.

En el siguiente ejemplo vemos como al encontrar la letra h se llama al `continue`, lo que hace que se salte el `print()`. Es por ello por lo que no vemos la letra P impresa en pantalla.
"""

cadena = 'Python'
for letra in cadena:
    if letra == 'h':
        continue
    print(letra)

"""A diferencia del `break`, el `continue` no rompe el bucle sino que finaliza la iteración actual, haciendo que todo el código que va después se salte, y se vuelva al principio a evaluar la condición.

En el siguiente ejemplo podemos ver como cuando la variable `x` vale `3`, se llama al `continue`, lo que hace que se salte el resto de código de la iteración (el print()). Por ello, vemos como el número 3 no se imprime en pantalla.
"""

x = 5
while x > 0:
    x -= 1
    if x == 3:
       continue
    print(x)