# -*- coding: utf-8 -*-
"""Semana_02-03_range.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/157MVC4_uZIEb5mIVvi9gOe6v0nI8gdh-

# Range en Python

## Uso del range

Uno de las iteraciones mas comunes que se realizan, es la de iterar un número entre por ejemplo 0 y n. Si ya programas, estoy seguro de que estas cansado de escribir esto, aunque sea en otro lenguaje. Pongamos que queremos iterar una variable i de 0 a 5. Haciendo uso de lo que hemos visto anteriormente, podríamos hacer lo siguiente.
"""

for i in (0, 1, 2, 3, 4, 5):
    print(i, end=', ')

"""Se trata de una solución que cumple con nuestro requisito. El contenido después del `in` se trata de una clase que como ya hemos visto antes, es iterable, y es de hecho una tupla. Sin embargo, hay otras formas de hacer esto en Python, haciendo uso del `range()`."""

for i in range(6):
    print(i, end=', ')

"""El `range()` genera una secuencia de números que van desde 0 por defecto hasta el número que se pasa como parámetro menos 1.
Si tomamos el ejemplo anterior lo podemos ver como un intervalo matemático [0,6) el cual incluye los valores 0,1,2,3,4,5.

El range en realidad soporta hasta tres parámetros separados por coma:
- El primer es el inicio de la secuencia
- El segundo el final.
- El tercero el salto que se desea entre números.

Por defecto se empieza en 0 y el salto es de 1.

```
#range(inicio, fin, salto)
```

Por lo tanto, si llamamos a range() con (5,20,2), se generarán números de 5 a 20 de dos en dos. Un truco es que el range() se puede convertir en list.
"""

print(list(range(5, 20, 2)))

"""Y mezclándolo con el for, podemos hacer lo siguiente."""

for i in range(5, 20, 2):
    print(i, end=', ')

"""Se pueden generar también secuencias inversas, empezando por un número mayor y terminando en uno menor, pero para ello el salto deberá ser negativo."""

for i in range (5, 0, -1):
    print(i, end=', ')