# -*- coding: utf-8 -*-
"""Semana_02-08_iterar_zip.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YX-37K-UONYx1hs89y4-5Z1z_TSdtnDY

# Iterar con zip en Python

La función `zip` me permite agrupar variables iterables e iterarlas todas juntas en una sola pasada.

Dicho de otra manera, si por ejemplos pasamos dos listas a `zip` como entrada, el resultado será una tupla donde cada elemento tendrá todos y cada uno de los elementos i-ésimos de las pasadas como entrada.

Veamos un ejemplo. Como podemos ver, el resultado tras aplicar `zip` es una tupla con (a[0], b[0]) en el primer elemento y (a[1], b[1]) como segundo.
"""

a = [1, 2]
b = ["Uno", "Dos"]
c = zip(a, b)

print(list(c))

"""A priori puede parecer una función no muy relevante, pero es realmente útil combinada con un for para iterar dos listas en paralelo."""

a = [1, 2]
b = ["Uno", "Dos"]

for numero, texto in zip(a, b):
    print("Número: ", numero, " - Español: ", texto)

"""## zip con n argumentos
Ya hemos visto el uso de `zip` con dos listas, pero dado que está definida como zip(*iterables), es posible pasar un número arbitrario de iterables como entrada.

Veamos un ejemplo con varias listas. Es importante notar que todas tienen la misma longitud.
"""

numeros = [1, 2]
espanol = ["Uno", "Dos"]
ingles = ["One", "Two"]
frances = ["Un", "Deux"]

for n, e, i, f in zip(numeros, espanol, ingles, frances):
    print('Número: ', n, ' - Español: ', e, ' - Inglés: ', i, ' - Frances: ', f)

"""## zip() con diferentes longitudes

También podemos usar `zip` usando iterables de diferentes longitudes. En este caso lo que pasará es que cuando el iterador de la lista más pequeña se acabe, entonces se terminará la ejecución del zip.
"""

numeros = [1, 2, 3, 4, 5]
espanol = ["Uno", "Dos"]

for n, e in zip(numeros, espanol):
    print('Número: ', n, ' - Español: ', e)

"""Resulta lógico que este sea el comportamiento, porque de no ser así y se continuara, no tendríamos valores para usar.

## zip() con un argumento
Como cabría esperar, dado que `zip` está definido para un número arbitrario de parámetros de entrada, es posible también posible usar un único valor. El resultado son tuplas de un elemento.
"""

numeros = [1, 2, 3, 4, 5]
zz = zip(numeros)
print(list(zz))

"""## zip() con diccionarios
Hasta ahora nos hemos limitado a usar `zip` con listas, pero la función está definida para cualquier clase iterable. Por lo tanto podemos usarla también con diccionarios.

Si realizamos lo siguiente, a,b toman los valores de las key del diccionario. Tal vez algo no demasiado interesante.
"""

esp = {'1-esp': 'Uno', '2-esp': 'Dos', '3-esp': 'Tres'}
eng = {'1-eng': 'One', '2-eng': 'Two', '3-eng': 'Three'}

for a, b in zip(esp, eng):
    print('Key esp: ', a, ' - key eng: ', b)

"""Sin embargo, si hacemos uso de la función items, podemos acceder al key y value de cada elemento, por lo tanto cada posición de la tupla es una nueva tupla con los items de cada diccionario."""

esp = {'1': 'Uno', '2': 'Dos', '3': 'Tres'}
eng = {'1': 'One', '2': 'Two', '3': 'Three'}

for (k1, v1), (k2, v2) in zip(esp.items(), eng.items()):
    print('key esp: ', k1,' - value esp: ',  v1,' - key eng: ',  k2,' - value eng: ',  v2)

"""Nótese que en este caso ambas key k1 y k2 son iguales.

## Deshacer el zip()
Con un pequeño truco, es posible deshacer el zip en una sola línea de código. Supongamos que hemos usado `zip` para obtener c.


"""

a = [1, 2, 3]
b = ["One", "Two", "Three"]
z = zip(a, b)

print(list(z))

"""¿Es posible obtener a y b desde c? Sí, tan sencillo como:"""

c = [(1, 'One'), (2, 'Two'), (3, 'Three')]
a, b = zip(*c)

print('Lista a: ', a)
print('Lista b: ', b)

"""Nótese el uso de *c, lo que es conocido como unpacking en Python y que las variables `z` y `c` son iguales.


"""